### ISSUE TITLE
How to save graph?

### ISSUE THREAD

**Issue by mustaffa** [highfestiva/finplot#1]
Hello,
Thanks for the great work, I managed the plot my first graph easily by following the example. I just need to save the graph, how can I do that ?

Cheers.

**Comment by highfestiva** [comment]
It's a plotting library, and saving files is not a feature I value 
myself, as I only ever intended to be use for backtesting.

If you like to implement it yourself, you could look at this: 
https://stackoverflow.com/questions/24413385/pyqt4-qwidget-save-as-image?answertab=votes#tab-top
Also, if you also make me a pull request on github, I'll incorporate it 
and pipify.

Kind regards,
Jonas

------ Originalmeddelande ------
Från: "mustaffa" <notifications@github.com>
Till: "highfestiva/finplot" <finplot@noreply.github.com>
Kopia: "Subscribed" <subscribed@noreply.github.com>
Skickat: 2019-05-13 12:33:16
Ämne: [highfestiva/finplot] How to save graph? (#1)

**Comment by highfestiva** [comment]
There are other tools for visualizing, so this tool's only using is building trading algorithms. When doing so plots have little to no historical value. Closing this issue.
