### ISSUE TITLE
Vertical grid lines only for bottom row?

### ISSUE THREAD

**Issue by haimivan** [highfestiva/finplot#102]
The following code shows only for the sub-chart at the bottom vertical grid lines. 

My expectation would have been that vertical lines would be visible for all sub-charts.

Is it somehow possible to change this behaviour?

```python
import finplot as fplt
import numpy as np
import pandas as pd

np.random.seed(1)

ax1, ax2, ax3, ax4 = fplt.create_plot('title', rows=4)
ax1.showGrid(True, True)
ax2.showGrid(True, True)
ax3.showGrid(True, True)
ax4.showGrid(True, True)

dates = pd.date_range('01:00', '01:00:01.200', freq='1ms')
prices = pd.Series(np.random.random(len(dates))).rolling(30).mean() + 4
plt1 = fplt.plot(dates, 1 *  prices, width=3, ax=ax1)
plt2 = fplt.plot(dates, 2 * prices, width=3, ax=ax2)
plt3 = fplt.plot(dates, 3 * prices, width=3, ax=ax3)
plt4 = fplt.plot(dates, 4 * prices, width=3, ax=ax4)

fplt.show()
```

![Screenshot from 2021-01-02 00-17-38](https://user-images.githubusercontent.com/10325765/103447788-0f434300-4c90-11eb-906a-eb174acd4cdd.png)

**Comment by highfestiva** [comment]
Fix in https://github.com/highfestiva/finplot/commit/dcc4518972b1246e38984636b019563c01d62d31.

**Comment by haimivan** [comment]
Looks very good! Thank you so much!
