### ISSUE TITLE
Save Screenshot without generating plot

### ISSUE THREAD

**Issue by guanm326** [highfestiva/finplot#104]
Theres an example where you show how to save a screenshot. 

Is it possible to save screenshot in a loop? I am worried it will create hundreds of pop up windows.

Thanks

**Comment by highfestiva** [comment]
It is not necessary, see https://github.com/highfestiva/finplot/issues/71#issuecomment-742015927.

**Comment by guanm326** [comment]
Thanks for the reply.

Quick follow up question. In the above link, he seems to be saving images for a single dataframe but giving a different slices of that single data frame. Am I interpreting his question correctly?

For me, I have thousands of stocks and for each stock I must download the data separately via a call to an external API. The data comes in and after preprocessing it, I will than save it in to a plot. Is that possible? Is there an example? Thanks so much.

**Comment by highfestiva** [comment]
No such example, but more than you asking for it. Unfortunately not at the core of the lib, which is for backtesting. That said, it's possible to do it. You probably need to clear the internal data in the process. See https://github.com/highfestiva/finplot/issues/95#issuecomment-753408373 for info on how to do that.

**Comment by guanm326** [comment]
Simila to the individual in issue #71 I am saving it for future reference. Its a good way for me to visually look for new ideas to test.

**Comment by beglitis** [comment]
Same here, I have one process (automated via a scheduler) that generates plots with matplotlib that go back 1Y,2Y,5Y, 10Y etc with adjusted close price series with volume, volatility, some indicators, daily returns, returns distributions and so on. There is many reasons why I would like to be doing that, one example is to visually assess that the data are there for the name of interest. However I am doing this for thousands of names overnight. I would love to ditch matplotlib in favour of your library but I will need a way to generate these plots and store the screenshots in a less "interactive" way.

**Comment by highfestiva** [comment]
@beglitis I understand, but sorry to say that your use case falls out of scope for finplot: to have a trivial API for generating views of backtesting large time periods.

However, this does not mean it's impossible to do what you're asking. All it means is that that the exposed API won't suffice. You'll have to get your hands dirty and dig into the internals. Closing one window and opening a new one should be fairly fast, even with many candlesticks you could probably do a couple of thousand in an hour. Good luck!

**Comment by beglitis** [comment]
@highfestiva Thank you. This is excellent software and I will definitely integrate it somehow with the Quantopian based backtester I have in place. Many thanks for making the effort to put finplot together, it looks so good (and mplfinance is such a chore) that I thought I could use it for static plots too.
