### ISSUE TITLE
Adding legends to candlestick_ochl plots

### ISSUE THREAD

**Issue by BeeSee20Eye35** [highfestiva/finplot#107]
Hi
Thanks again for your help with https://github.com/highfestiva/finplot/issues/95#issue-774950311. This is working very well now. 

Following on from the above, now that I have different highlighting schemes, I would like to add a legend for the different highlighting series. However, the candlestick_ochl plots don't seem to have this functionality. Am I missing it? 

What would be the best way to do this please? Sorry of this is really obvious and I am being obtuse. 

Thanks
Vinton

**Comment by BeeSee20Eye35** [comment]
Here is the code snippet I have tried so far.


`self.plots.append(fplt.candlestick_ochl(datasrc=bullbars, candle_width=1.15))
self.plots[0].colors.update(dict(bull_body='#f0b', bull_shadow='#fda', bear_body='#185', bear_shadow='#000'))

fplt.add_legend(f'bull selected', self.plots[0])`


Or 

`self.plots.append(fplt.candlestick_ochl(datasrc=bullbars, candle_width=1.15))
self.plots[0].colors.update(dict(bull_body='#f0b', bull_shadow='#fda', bear_body='#185', bear_shadow='#000'))

fplt._create_legend(self.plots[0])`

**Comment by BeeSee20Eye35** [comment]
Both get the response:
"AttributeError: 'CandlestickItem' object has no attribute 'legend'"

**Comment by highfestiva** [comment]
Adding legend manually works like this: `fplt.add_legend('Info', ax=ax)`. It is currently not possible to add a legend specifically for a candlestick plot.

**Comment by BeeSee20Eye35** [comment]
Thanks for the clarification. I'll work out another way to make the bars identifiable. 
Cheers.
