### ISSUE TITLE
Cannot plot moving average

### ISSUE THREAD

**Issue by Engrico** [highfestiva/finplot#11]
Hi, I am new to Python and to finplot (just so you know). I found your package because I the alternatives produce mediocre candlestick plots, whereas yours produces super quality plots.

However, I cannot manage to add a moving average to a candlestick plot. I am using Anaconda3 disctibution of Python. I needed to fiddle a bit with the installation to get your package installed, don't know if this screwed up something.

Anyways, if you run the attached example (it uses yfinance to scrape data), you will not see the moving average displayed (at least I do not). If you comment out the plot candlestick line, then you will see the moving average (at least I do).

In all cases, good work and thanks for the package.
[yfinance_test.txt](https://github.com/highfestiva/finplot/files/4572374/yfinance_test.txt)

**Comment by Engrico** [comment]
Apologies I meant if you run the code as-is, you will see the moving average in the bottom subplot. If you change the moving average to the first set of axes, it will not appear (as an overlay of the candlesticks). Apolopgies.

**Comment by Engrico** [comment]
What do you know, if I write:

fplt.candlestick_ochl(candles, ax=ax)
fplt.plot(aapl[['Close']].rolling(25).mean().dropna(), ax=ax, color='#00f', legend='ma-25')

I do not see the moving average. However, if I inverse as:

fplt.plot(aapl[['Close']].rolling(25).mean().dropna(), ax=ax, color='#00f', legend='ma-25')
fplt.candlestick_ochl(candles, ax=ax)

I do see the moving average.

**Comment by highfestiva** [comment]
I can't seem to reproduce your error, try this:

	#!/usr/bin/env python3

	import finplot as fplt
	import pandas as pd
	import requests
	from io import StringIO
	from time import time

	end_t = int(time()) 
	start_t = end_t - 12*30*24*60*60 # twelve months
	symbol = 'AAPL'
	interval = '1d'
	url = 'https://query1.finance.yahoo.com/v7/finance/download/%s?period1=%s&period2=%s&interval=%s&events=history' % (symbol, start_t, end_t, interval)
	r = requests.get(url)
	aapl = pd.read_csv(StringIO(r.text))
	aapl['Date'] = pd.to_datetime(aapl['Date'])

	candles = aapl[['Date','Open','Close','High','Low']]
	fplt.candlestick_ochl(candles)
	fplt.plot(aapl['Close'].rolling(25).mean(), legend='ma-25')

	fplt.show()

Or send me a full example so I can reproduce the error.

**Comment by Engrico** [comment]
Hi,

When I run your code, I see the candles, but not the moving average plot. When I inverse the last few lines as such:

candles = aapl[['Date','Open','Close','High','Low']]
fplt.plot(aapl['Close'].rolling(25).mean(), legend='ma-25')
fplt.candlestick_ochl(candles)

I get the following errors:

Traceback (most recent call last):
  File "finplot_test.py", line 26, in <module>
    fplt.candlestick_ochl(candles)
  File "D:\Anaconda3\lib\site-packages\finplot\__init__.py", line 870, in candlestick_ochl
    _set_datasrc(ax, datasrc)
  File "D:\Anaconda3\lib\site-packages\finplot\__init__.py", line 1190, in _set_datasrc
    viewbox.datasrc.addcols(datasrc)
  File "D:\Anaconda3\lib\site-packages\finplot\__init__.py", line 157, in addcols
    self.df = pd.concat([df, newcols], axis=1)
  File "D:\Anaconda3\lib\site-packages\pandas\core\reshape\concat.py", line 284, in concat
    return op.get_result()
  File "D:\Anaconda3\lib\site-packages\pandas\core\reshape\concat.py", line 497, in get_result
    mgrs_indexers, self.new_axes, concat_axis=self.axis, copy=self.copy
  File "D:\Anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 2027, in concatenate_block_managers
    return BlockManager(blocks, axes)
  File "D:\Anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 139, in __init__
    self._verify_integrity()
  File "D:\Anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 334, in _verify_integrity
    construction_error(tot_items, block.shape[1:], self.axes)
  File "D:\Anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 1694, in construction_error
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (500, 4), indices imply (498, 4)

Now I will be honest with you, I had problems installing your package with Anaconda3 Python (I am new to Python, I come from the Matlab universe, but thought it was time to learn Python). Your package would not install because it needs PyQt5 5.13.0, but this would break Spyder IDE, which requires < 5.13.0.

Hence, I needed to update through “conda update --all", after which I needed to reinstall toml “pip install toml”, then I need to install your package “pip install finplot” (I needed to do the installation 2 times for the error messages to clear), then reinstall PyQtWebEngine “pip install pyqtwebengine”.

So, maybe this is just an installation error?

Thanks for your time,

Eric Martel

Provenance : Courrier pour Windows 10

De : Jonas Byström
Envoyé le :6 mai 2020 16:46
À : highfestiva/finplot
Cc : Engrico; Author
Objet :Re: [highfestiva/finplot] Cannot plot moving average (#11)

I can't seem to reproduce your error, try this:
#!/usr/bin/env python3

import finplot as fplt
import pandas as pd
import requests
from io import StringIO
from time import time

end_t = int(time()) 
start_t = end_t - 12*30*24*60*60 # twelve months
symbol = 'AAPL'
interval = '1d'
url = 'https://query1.finance.yahoo.com/v7/finance/download/%s?period1=%s&period2=%s&interval=%s&events=history' % (symbol, start_t, end_t, interval)
r = requests.get(url)
aapl = pd.read_csv(StringIO(r.text))
aapl['Date'] = pd.to_datetime(aapl['Date'])

candles = aapl[['Date','Open','Close','High','Low']]
fplt.candlestick_ochl(candles)
fplt.plot(aapl['Close'].rolling(25).mean(), legend='ma-25')

fplt.show()
Or send me a full example so I can reproduce the error.

**Comment by highfestiva** [comment]
Ah, the reason is you're using a bad PyQt version. Either use `pyqt5==5.9` or `pyqt5==5.13.0`. The reson you're not seeing any plots is that between those versions is that a line containing NaNs will not be plotted.

(The reason my example does not work when you reverse the order in which the plots are rendered, is that the second one relies on the timestamps from the first one. Note that no X-parameter is supplied in the MA plot, it uses the X - i.e. Date - from the first plot.)

**Comment by Engrico** [comment]
That explains everything!

Many thanks and keep up the excellent work!

Eric

Provenance : Courrier pour Windows 10

De : Jonas Byström
Envoyé le :7 mai 2020 03:21
À : highfestiva/finplot
Cc : Engrico; Author
Objet :Re: [highfestiva/finplot] Cannot plot moving average (#11)

Closed #11.
