### ISSUE TITLE
gap between candlesticks while refreshing

### ISSUE THREAD

**Issue by kmungantiwar** [highfestiva/finplot#112]
When I run the code, it starts perfectly but then at every minute when it refreshes the data, it creates a gap between every candlestick and volume bar. is there a fix?

<img width="960" alt="plot" src="https://user-images.githubusercontent.com/77494760/104733253-6bb06300-5764-11eb-9995-c54d6eae5b77.png">
[Reliance - MACD - 1minute auto refresh.zip](https://github.com/highfestiva/finplot/files/5820841/Reliance.-.MACD.-.1minute.auto.refresh.zip)

**Comment by highfestiva** [comment]
The bug is with you, you're passing in non-zero seconds in the last (realtime) candle. Also you want integers. Truncate like so:
````python
    df['Time'] = df['Time']//int(1e9)//60*int(1e9)*60 - (330*60*int(1e9))
````
Also, you don't want to create a new (unshown) plot each time you update. Place the `create_plot` call inside the if statement.
