### ISSUE TITLE
Creating multiple plots

### ISSUE THREAD

**Issue by buger** [highfestiva/finplot#113]
Hi! 

My goal is to analyze multiple pairs within one window, and I want to plot them separately, e.g. 4 different windows for each pair. Ideally, combine with https://github.com/highfestiva/finplot/blob/master/finplot/example-embed.py so it will be possible to give them a nice layout. 

Any recommendations? 

Thank you a lot for your work!

**Comment by highfestiva** [comment]
Have no ideas of what you're trying to accomplish, but maybe this can get you started:

````python
#!/usr/bin/env python3

import finplot as fplt
import yfinance as yf

data = [(instrument, yf.download(instrument, '2020-10-01')) for instrument in ('AAPL','GOOG','TSLA')]
for i,(instrument_a,dfa) in enumerate(data):
    for instrument_b,dfb in data[i+1:]:
        ax = fplt.create_plot(instrument_a+' vs. '+instrument_b+' (green/brown)', maximize=False)
        dfa['Open Close High Low'.split()].plot(kind='candle', ax=ax)
        pb = dfb['Open Close High Low'.split()].plot(kind='candle', ax=ax.overlay(scale=1.0))
        pb.colors['bull_body'] = '#0f0'
        pb.colors['bear_body'] = '#630'
fplt.show()
````
