### ISSUE TITLE
Volume profile xlim, alpha, overlaying profiles

### ISSUE THREAD

**Issue by karunkrishna** [highfestiva/finplot#114]
Few questions regarding volume profile implementation
The profiles have been created for the same time period

- The initial balance (IB) is between 9:30 AM and 10:30 AM
- The real trading hours (RTH) is between 9:30 AM and 4:00 PM

[1] Is there a way to set the xlim for volume profile in finplot?
- the IB volumes should be much less, however because it doesn't have the other volumes it visually looks bigger than it should be when plotted side by side 
- From the side by side comparison, you can see the true scale of ib vs rth profiles at end of day
- Is it possible to set the xlim for a volume profile? If I can supply a  "max xlim" it could act as a way of normalizing between volume profiles 
- I am thinking a similar implementation to how it's done on matplotlib (Image attached)

![image](https://user-images.githubusercontent.com/2157606/104857049-e5bb2600-58e3-11eb-90f9-4455a1c7f276.png)

![image](https://user-images.githubusercontent.com/2157606/104857647-f2da1400-58e7-11eb-8480-70f3f09affa5.png)

```
rth_ax.set_title('Real Trading Hour Volume')
volume_df.plot(kind='barh', stacked=True, width=0.8, ax=rth_ax)

ib_ax.set_title('Initial Balance Volume')
ib_volume_df.plot(kind='barh', stacked=True, width=0.8, ax=ib_ax)
ib_ax.set_xlim(rth_ax.get_xlim())
```

[2] Currently if I was to overlay the volume profile during the same time, it does not render
-  For example if I replace rth_date with ib_date and keep it the same value, the volume profile does not render
- Is there a way of overlay the volume profile and applying an alpha for each profile, so you can visually compare
- Is it possible to color the volume profile

```
    date = dt.datetime.utcfromtimestamp(date.astype('O') / 1e9)
    ib_date = date.replace(hour=9, minute=30)
    rth_date = date.replace(hour=10, minute=30)

    rth_volumes = [tuple(x) for x in rth_vols.reset_index().values]
    ib_volumes = [tuple(x) for x in ib_vols.reset_index().values]

    finplot_volume_profiles.append([pd.Timestamp(ib_date), ib_volumes])
    finplot_volume_profiles.append([pd.Timestamp(rth_date), rth_volumes])
```

**Comment by highfestiva** [comment]
Volume profiles work, but need some love. The API, scaling, internal data format, config & coloring are all pretty bad. If you have the time, I'd much appreciate a pull request. However, I suspect most things you're asking for can be solved in some ugly fashion.

[1] Yes, you can use the `draw_body` optional parameter to set the width of the thing. Default is `0.4`.
[2] You can just draw the smaller one on top of the wider one:

````python
fplt.horiz_time_volume(time_volume_profile, draw_va=0.7, draw_poc=1.0)
smaller_one = fplt.horiz_time_volume(time_volume_profile, draw_body=0.2)
smaller_one.colors['neutral_body'] = '#ff0'
smaller_one.colors['neutral_frame'] = '#f0f'
````
![image](https://user-images.githubusercontent.com/160303/104858160-a4e00300-591d-11eb-9fc4-9a68bf402fbf.png)
