### ISSUE TITLE
[Help] Synchronize crosshairs across multiple windows

### ISSUE THREAD

**Issue by mm-manu** [highfestiva/finplot#115]
I have multiple plot windows (using create_plot(...) for each window) to show candle plots of different timeframes (e.g. 5m and 1h) and would like to synchronize the crosshairs (at least the y coordinate). Do you think that's possible without rewriting too much code?

**Comment by highfestiva** [comment]
Yes, you probably could call `finplot._mouse_moved(other_window, transformed_event)` on all the other windows or something like that. Perhaps easier is to put your different axis with different resolutions in the same window?

**Comment by mm-manu** [comment]
ok, thanks. I'll try

**Comment by mm-manu** [comment]
modified ``_mouse_moved()`` to 

```
def _mouse_moved(master, evs, is_source_event=True, src_x=None, src_y=None):
    if hasattr(master, 'closing') and master.closing:
        return
    if not evs:
        evs = master_data[master]['last_mouse_evs']
        if not evs:
            return
    master_data[master]['last_mouse_evs'] = evs
    pos = evs[-1]
    # allow inter-pixel moves if moving mouse slowly
    y = pos.y()
    dy = y - master_data[master]['last_mouse_y']
    if 0 < abs(dy) <= 1:
        pos.setY(pos.y() - dy/2)
    master_data[master]['last_mouse_y'] = y
    # apply to all crosshairs

    for ax in master.axs:
        if ax.isVisible() and ax.crosshair:
            point = ax.vb.mapSceneToView(pos)
            if is_source_event:
                ax.crosshair.update(point)
            else:
                ax.crosshair.update(QtCore.QPointF(src_x, src_y))

    source_event_time = 0
    if is_source_event:
        ax = master.axs[0]
        point = ax.vb.mapSceneToView(pos)
        src_x, src_y = _clamp_xy(ax, point.x(), point.y())
        source_event_time,_,_,_,_ = ax.vb.datasrc.hilo(src_x, src_x)
    for w in windows:
        if w != master and is_source_event:
            diff = w.axs[0].vb.datasrc.df.iloc[:,0] - source_event_time
            try:
                transformed_x = np.where(diff>-w.axs[0].vb.datasrc.df.iloc[:,0].diff().median())[0][0]
            except IndexError:
                return
            _mouse_moved(w, evs, is_source_event=False, src_x=transformed_x, src_y=src_y)
```
works as intended!

**Comment by highfestiva** [comment]
Nice! I suggest you keep this method in your own code, and then do:
````python
finplot._mouse_moved = _mouse_moved
````

**Comment by mm-manu** [comment]
good idea, thanks!

**Comment by dshibanov** [comment]
Hi! I'm looking for the same functionality and  now I'm trying to replicate this and got 'NameError: name 'master_data' is not defined' in _mouse_moved().  How to fix?

**Comment by mpmX** [comment]
> Hi! I'm looking for the same functionality and now I'm trying to replicate this and got 'NameError: name 'master_data' is not defined' in _mouse_moved(). How to fix?

It's been a while, but masterdata is defined in `finplot/__init__.py`. So maybe it's enough to simply import it

**Comment by dshibanov** [comment]
`def _mouse_moved(master, evs, is_source_event=True, src_x=None, src_y=None):
    if hasattr(master, 'closing') and master.closing:
        return
    if not evs:
        evs = master_data[master]['last_mouse_evs']
        if not evs:
            return
    master_data[master]['last_mouse_evs'] = evs
    pos = evs[-1]`
    
    This error on last line: 
    

> pos = evs[-1]
> TypeError: 'FinViewBox' object is not subscriptable

**Comment by mpmX** [comment]
well, the `_mouse_moved` function has changed. see [here](https://github.com/highfestiva/finplot/blob/039b80924770bf12921125d49941a889faa389d1/finplot/__init__.py#L2730)
you need to adapt
