### ISSUE TITLE
Overlapping indexes produce flatline on overlay

### ISSUE THREAD

**Issue by jabowery** [highfestiva/finplot#116]
I find I need to run an intersection between the indexes and then restrict the dataframes to to that index to avoid a flat line appearing in an overlayed graph of multiple dataframes.

**Comment by highfestiva** [comment]
I'm still undecided on how to handle timestamps in general. Could you post an example of flatlining?

**Comment by highfestiva** [comment]
@jabowery I don't know how to reproduce.
