### ISSUE TITLE
On MacOS: Error saving plot: [Errno 2] No such file or directory: '/Users/User1/.finplot/Finance Plot.ini'

### ISSUE THREAD

**Issue by msarm** [highfestiva/finplot#117]
I'm not saving the plot feature however, getting the below error message on macOS.

`Error saving plot: [Errno 2] No such file or directory: '/Users/User1/.finplot/Finance Plot.ini'`

**Comment by highfestiva** [comment]
Using `finplot.autoviewrestore()` tries to save+load your zoom coordinates. For some reason saving the coordinates fails on Macs?

**Comment by highfestiva** [comment]
@msarm Are you running `autoviewrestore()` from some callback or so? Show me some code.

**Comment by msarm** [comment]
> @msarm Are you running `autoviewrestore()` from some callback or so? Show me some code.

Yes, you are right this happens only during callback. I'll prepare a sample code to demonstrate the behaviour.

**Comment by msarm** [comment]
> > @msarm Are you running `autoviewrestore()` from some callback or so? Show me some code.
> 
> Yes, you are right this happens only during callback. I'll prepare a sample code to demonstrate the behaviour.

I'm unable to replicate this issue anymore even with callback, so will close this issue.
