### ISSUE TITLE
New candlestick handling

### ISSUE THREAD

**Issue by beglitis** [highfestiva/finplot#119]
https://github.com/highfestiva/finplot/blob/1985f97d1db8a0131e44f7a392e499457e436d58/finplot/example-bitmex-ws.py#L88

Just a thought on this only because I am playing around with a similar implementation following yours as an example. Would it not make more sense for when a new candlestick is created for high/low/open/close to be equal (all of them) to the current price in the last message from the exchange? Then subsequent messages will adjust the candlesticks accordingly. The way it is done now effectively daisy-chains the candlesticks either on the low side or on the high side to the ones immediately to the left.

**Comment by highfestiva** [comment]
That is absolutely correct, thanks! Fixed it.
