### ISSUE TITLE
Close function

### ISSUE THREAD

**Issue by fjafferi** [highfestiva/finplot#121]
Hi there,
First of all, I wanted to say thank you for putting together this awesome project...so much better than some of the other libraries. After playing around with it for a bit and reading through the threads, I realized that this is intended for back testing and it definitely serves its purpose. However, I stumbled a scenario where I am looping through many different equities and found that there is no easy way to close the plot programatically, to get around it I ended up pulling a copy into my project and got it to work with an addition of close function (below) in __init__.py, I wanted to see if you its possible to include that into the project?

```python
def close():
    for win in windows:
        if isinstance(win, FinWindow):
                win.close()

```

Thank you.

**Comment by highfestiva** [comment]
Pehaps better with a
````python
try:
    win.close()
except:
    pass
````
? Put it in a pull request after the `create_plot_widget` function and I'll include it.

**Comment by fjafferi** [comment]
done, thank you.
