### ISSUE TITLE
qt.qpa.fonts error

### ISSUE THREAD

**Issue by raserux** [highfestiva/finplot#128]
Hello, I'm getting the following errors when I try to run the code below. I have tried opening up the regedit, but I don't know how to apply a default font.

Error:
qt.qpa.fonts: Unable to open default EUDC font: "EUDC.TTE"
IndexError: index 4 is out of bounds for axis 0 with size 4

Code:
ax,ax2 = fplt.create_plot(hist_symbol, rows=2)
candles = df[['open', 'close', 'high', 'low']]
fplt.candlestick_ochl(candles, ax=ax)

fplt.show()

**Comment by highfestiva** [comment]
If you only use `open, close, high, low`, you need to have time as index. Unless you supply time as index, you want that in your first column, like so:
````python
candles = df[['time', 'open', 'close', 'high', 'low']]
````
Good luck!

**Comment by raserux** [comment]
Ok that fixed the index error, but the plot is not showing up. Can you offer any help on this error: qt.qpa.fonts: Unable to open default EUDC font: "EUDC.TTE"
