### ISSUE TITLE
Putting labels of chars on chart will cause error

### ISSUE THREAD

**Issue by pangfat** [highfestiva/finplot#13]
https://github.com/highfestiva/finplot/blob/a084ac6af056ba37e78e1021c63688490bb75f5b/finplot/__init__.py#L1267

In the example code, labels are numbers in string type. When I use real chars, the code above will tell me can't compare number with string. So I added below parameter in the first max().

My pandas is 1.0.5. And the data source I passed in is a pd.DataFrame with 3 columns: date, high and 'A'.

if datasrc.df.iloc[:, 1:].max(**numeric_only=True**).max() > 1e8

Please let me know if my understanding is correct.

Thank you.

**Comment by highfestiva** [comment]
Thanks for your fix, pushed it to github!

------ Originalmeddelande ------
Från: "pangfat" <notifications@github.com>
Till: "highfestiva/finplot" <finplot@noreply.github.com>
Kopia: "Subscribed" <subscribed@noreply.github.com>
Skickat: 2020-06-23 16:22:29
Ämne: [highfestiva/finplot] Putting labels of chars on chart will cause 
error (#13)
