### ISSUE TITLE
Resizing plots

### ISSUE THREAD

**Issue by legendagain** [highfestiva/finplot#130]
Hi @highfestiva, first of all I'd like to say thank you very much for this library.

A quick question (if you know any workaround), is there a way to resize the different rows? The first row (price chart is always the largest), but I'd like to plot 2 time series, so ideally I'd like two rows of the same size.

Is there a way to do that?
Thank you!

**Comment by highfestiva** [comment]
https://github.com/highfestiva/finplot#scaling-plot-heights
