### ISSUE TITLE
Can't plot MA/Candlestick at the same time

### ISSUE THREAD

**Issue by JaroslavJakub** [highfestiva/finplot#135]
Hi, I encountered an issue while trying to plot candlestick chart with moving averages(BOLL).
I'm not sure if the issue occurs due to lack of my general coding/python knowledge or it's something with library source code.

Anyway, issue is I can plot candle sticks alone. Same with MA's but when I try to plot them together on one chart I'm only partly
successful. Or not at all.

My code:
`import finplot as fplt
import numpy as np
import pandas as pd
import requests
import datetime
fplt.display_timezone = datetime.timezone.utc

/# format it in pandas
symbol = 'USDT-BTC'
df = pd.read_csv('C:\\Users\\j4ros\\Binance\\Data\\Historical\\btc_bars.csv', 
                    parse_dates=['Open time'], date_parser=lambda epoch: pd.to_datetime(epoch, unit='ms'), nrows=200000)
df2 = pd.read_csv('C:\\Users\\j4ros\\Binance\\Data\\Historical\\btc_bars.csv', 
                    parse_dates=['Open time'], date_parser=lambda epoch: pd.to_datetime(epoch, unit='ms'), nrows= 200000)
df.set_index(df['Open time'], inplace=True)

/# create two axes
ax = fplt.create_plot(symbol, rows=1)

/# put an MA on the close price
r = df['Close'].rolling(25)
fplt.plot(r.mean().dropna(), ax=ax, legend='ma-20')
fplt.plot(r.mean().dropna() + 2*r.std().dropna(), ax=ax)
fplt.plot(r.mean().dropna() - 2*r.std().dropna(), ax=ax)

/# plot candle sticks
candles = df2[['Open time', 'Open','Close','High','Low']]
fplt.candlestick_ochl(candles, ax=ax)

/# we're done
fplt.show()`

When I run this code window appears, nothing renders and then it crash immediately without showing any errors.

If I comment out part with (#put an MA on the close price) and leave everything else without change. This is result...
![image](https://user-images.githubusercontent.com/79802138/109427139-406e9400-79f1-11eb-85d8-ad27ebb8ea4e.png)

So, everything as expected.
Commenting out part with candlestick I get this...
![image](https://user-images.githubusercontent.com/79802138/109427310-15d10b00-79f2-11eb-9518-a813b87f8bbc.png)
Works ass well.

Best result I managed to get is this and it's done by commenting out line "df.set_index(df['Open time'], inplace=True)" 
in (#format it in pandas) part of code.
As you can see on snippet dates of x axis on BOLL part of chart suddenly and for me surprisingly happen to set on 
"1.1.1970 00:00" for every line entry of data. I have no idea what caused this issue and I would really appreciate help.
Thank you in advance.

![image](https://user-images.githubusercontent.com/79802138/109427436-ba534d00-79f2-11eb-9879-2dfc00eb8e22.png)

**Comment by highfestiva** [comment]
If you're not sure what you're doing, I recommend using the same dataframe for all data. I.e. don't use both `df` and `df2`. The problem in your case is probably that you're mixing dataframes with a timestamped index, and one without. [KISS](https://en.wikipedia.org/wiki/KISS_principle).

**Comment by highfestiva** [comment]
If you want further help, post a complete example, including data — preferably in a .zip — and I'll see what I can do.
