### ISSUE TITLE
Using matplotlib concurrently with finplot

### ISSUE THREAD

**Issue by legendagain** [highfestiva/finplot#137]
Hello!

From my understanding, the finplot library modifies the behaviour of matplotlib. As a result, `df.plot()` doesn't work originally as it does. If I were to use finplot at first and want to use (vanilla) matplotlib later, how would I do it?

Many thanks!

**Comment by highfestiva** [comment]
Use `matplotlib.pyplot.plot` instead of `df.plot()` or run them in separate processes.
