### ISSUE TITLE
Resizing labels

### ISSUE THREAD

**Issue by legendagain** [highfestiva/finplot#138]
Hello! Apologies I have another question:

I am currently using the following code to plot labels to the right of the moving average indicators:
`fplt.labels(df_ma.index[-1], ma_series[-1], labels=ma_series.name, color=color)`

Is there a way I can resize the label? I have tried using

`label = fplt.labels(df_ma.index[-1], ma_series[-1], labels=ma_series.name, color=color)`
`label.setScale(2.0)`

...however this results in the plot not showing anything at all.

**Comment by highfestiva** [comment]
Hadn't thought of that, but added support for html labels in 6eaa0ff688a25468f9eb63462abbb2937b079acb. That way you can style each label individually. Example of how to do italic and font size in two different series:
```python
df['tdup'] = [('<i>%i</i>'%i if 0<i<10 else '') for i in tdup]
df['tddn'] = [('<span style="font-size:18px">%i</span>'%i if 0<i<10 else '') for i in tddn]
```

**Comment by highfestiva** [comment]
> (caveat being that labels with both `<` and `>` will be recognized as HTML... not an issue for me—but just in case)

True, but pragmatism wins over theory every time in my book. :)
