### ISSUE TITLE
Several embedded finplot windows in one layout

### ISSUE THREAD

**Issue by gryabov** [highfestiva/finplot#141]
Hi, thank you for the library. 

My question: can I have several emdedded  finplot windows into one layout. I have to see 30m and 1min at the same time, so I have to place two finplot widgets into one layout. Separate dataset for each panel.

**Comment by highfestiva** [comment]
Check out [this](https://github.com/highfestiva/finplot/issues/10#issuecomment-690131104) example.

**Comment by gryabov** [comment]
For embedded I use:
`       fp = finplot.FinWindow(title="chart")
        self.ax = finplot.create_plot_widget(fp, rows=2, init_zoom_periods=100)
        fp.ci.addItem(self.ax, row=0, col=0)
        layout.addWidget(fp, 1, 0, 1, 1)
        `

but self.ax.ax_widget does not exists

`   self.verticalLayout.addWidget(self.ax.ax_widget)
AttributeError: 'PlotItem' object has no attribute 'ax_widget'`

**Comment by highfestiva** [comment]
`FinWindow` does not support manual layouting, you need to create a window of your own. See example above.

**Comment by gryabov** [comment]
Thanks. finplot.set_time_inspector stopped working.

```python
finplot.set_time_inspector(self.update_legend_text, ax=self.ax, when='hover')
```

```python
   win.proxy_hover = pg.SignalProxy(win.scene().sigMouseMoved, rateLimit=15, slot=partial(_inspect_pos, ax, inspector))
AttributeError: 'NoneType' object has no attribute 'sigMouseMoved'
```

**Comment by highfestiva** [comment]
That's because your window does not have a `scene()` function. That functionality comes from `pyqtgraph`, but if you want to roll your own window, you might have to build your own time inspector. I'm not familiar with the details myself, so feel free to chuck in a pull request if fixes are needed in the finplot end.
