### ISSUE TITLE
change fill color based on conditions

### ISSUE THREAD

**Issue by madanweb30** [highfestiva/finplot#143]
Hi,
I want to change color of fill based on condition,like   dfc_c['HULL'] > dfc_c['HULL'].shift(2) then Green and dfc_c['HULL'] < dfc_c['HULL'].shift(2) the red .Please suggest how to do ??

plots.append(fplt.plot(dfc_c['DateTime'], dfc_c['HULL'], ax=ax, color='#4e4ef1'))
    plots.append(fplt.plot(dfc_c['DateTime'], dfc_c['HULL'].shift(2), ax=ax, color='#4e4ef1'))
    fplt.fill_between(plots[0], plots[1], color='#6CFF40')

**Comment by highfestiva** [comment]
Something like
```python
import numpy as np
h = dfc_c.set_index('DateTime')['HULL']
h_up,h_dn = h,h.copy()
h_up.loc[h_up< h_up.shift(2)] = np.nan
h_dn.loc[h_dn>=h_dn.shift(2)] = np.nan
fplt.plot(h_up, color='#0f0')
fplt.plot(h_dn, color='#f00')
```
might do the trick. Then you'd have to tinker some yourself to fill in the gaps, otherwise you'll get this:

![image](https://user-images.githubusercontent.com/160303/111532747-4e007980-8766-11eb-99b0-6d4f45cccd75.png)

**Comment by madanweb30** [comment]
line is working as expected, will try to do some trick for fill part
