### ISSUE TITLE
To install more than one click callback

### ISSUE THREAD

**Issue by pangfat** [highfestiva/finplot#15]
https://github.com/highfestiva/finplot/blob/a084ac6af056ba37e78e1021c63688490bb75f5b/finplot/__init__.py#L1081

I initialize win.proxy_click as [] and append proxy to it, so now I can install more callback. Not sure if this is the correct way to use.

win.proxy_click.append(pg.SignalProxy(win.scene().sigMouseClicked,                                    slot=partial(_time_clicked, ax, inspector)))

Thank you.

**Comment by highfestiva** [comment]
Hi pangfat,

I recommend you use

def your_callback(vars, x, y):
     print(vars)
     print(x)
     print(y)
     ...

fplt.set_time_inspector(functools.partial(your_callback, locals()))

Kind regards,
Jonas

------ Originalmeddelande ------
Från: "pangfat" <notifications@github.com>
Till: "highfestiva/finplot" <finplot@noreply.github.com>
Kopia: "Subscribed" <subscribed@noreply.github.com>
Skickat: 2020-06-23 16:46:11
Ämne: [highfestiva/finplot] To install more than one click callback 
(#15)

**Comment by pangfat** [comment]
Hi Jonas,

Do you mean it's better to keep as few SignalProxy as possible?

Thank you.

**Comment by highfestiva** [comment]
Don't use package internals if you can avoid it. API's are generally created to last longer. Myself I make an effort to change the API's as little as possible.
