### ISSUE TITLE
TypeError: _ax_set_visible() got an unexpected keyword argument 'xgrid' in example-analyze.py

### ISSUE THREAD

**Issue by AlexStox** [highfestiva/finplot#150]
Hi Jonas, I tried to run [example-analyze.py](https://github.com/highfestiva/finplot/blob/4a30ba28abd37a22155fef646f9003979ef61129/finplot/example-analyze.py) and got an error `TypeError: _ax_set_visible() got an unexpected keyword argument 'xgrid'`

How to fix this?

**Comment by highfestiva** [comment]
You want to update to the latest version with `pip install -U finplot`.
