### ISSUE TITLE
Creating custom fills for graphs

### ISSUE THREAD

**Issue by Elvis8409** [highfestiva/finplot#151]
Hi highfestiva,

THANK YOU for this awesome library.

I am busy creating Ichimoku graphs and would like to alternate between green fills and red fills between the 2 calculates span graphs. Matplotlib has this functionality with its fill_between method where the "where" kwargs can be used to specify when green is to be filled and when red is to be filled. Does finplot have something similiar, been through the source code and can't find any?

Example of what I am after, at this point I can only fill with one color:
![image](https://user-images.githubusercontent.com/81630086/112994729-d4f02180-916a-11eb-9afa-b8c38327e97c.png)

**Comment by highfestiva** [comment]
Hi Elvis, unfortunately you need to create two separate fills in finplot.
