### ISSUE TITLE
Green/Red chart background coloring

### ISSUE THREAD

**Issue by sarangab** [highfestiva/finplot#154]
Wondering if there's a way to alternate background colors of the charts to GREEN/RED based on whether there is a signal given

![image](https://user-images.githubusercontent.com/298736/113242429-f6dac880-927e-11eb-90f4-b2129432d3c2.png)

**Comment by highfestiva** [comment]
Nothing built-in unfortunately, but you can build it yourself if you like. It's a good idea, and if you make a pull request I'll gladly incorporate it.

**Comment by highfestiva** [comment]
You can use `fplt.add_rect()` included in 5c74ec12da64350a95f5613ebf08d2b6f84ae7be.
