### ISSUE TITLE
Plot a rectangle from [x1, y1] to [x2, y2]  (similar to issue #2)

### ISSUE THREAD

**Issue by workingshaw** [highfestiva/finplot#155]
Hi. You've made a great work. Thank you.

finplot already lets adding lines, as specified in issue #2. https://github.com/highfestiva/finplot/issues/2

line = fplt.add_line((dates[100], 4.4), (dates[1100], 4.6), color='#9900ff', interactive=True)

Thanks for that.
 

It would be also useful to be able to add rectangles, both, filled and outlined, with parameters for pen and brush colors.

Thanks in advance.

**Comment by highfestiva** [comment]
Good suggestion, that would actually solve two of the currently open issues. I'll do it in the next few weeks unless someone beats me to it... :)

**Comment by highfestiva** [comment]
It's added in 5c74ec12da64350a95f5613ebf08d2b6f84ae7be, see [example](https://github.com/highfestiva/finplot/commit/5c74ec12da64350a95f5613ebf08d2b6f84ae7be#diff-736aab5102254ace196d66d48d284e07d7d9a6da30d7c5946e88b2dc4bea486fR15).

**Comment by workingshaw** [comment]
Hey highfestiva, Thanks for this.

I'm sorry for bringing this up. In my view, a rectangle needs two colors, one for the contour (pen) and one for the fill (brush), because there are times when we don't want a filled rectangle. 

So, I was thinking that there are several aprroaches for this. The one I suggested seemed to me the most compatible with your existing code. I suggested using two color parameters, one for the pen, and the other for the brush. So having a QBrush = None could be interpreted as a noBrush style, which translates to a rectangle with no fill. 

The most complete approach would be having a pen object and a brush object as arguments. then there is control over every detail about them. 
For example: A QPen has color, width, style, CapStyle and JoinStyle, and from QBrush we are interested in its color and style. 

Again, I'm sorry for being that guy.

Thanks for your time and effort.

**Comment by highfestiva** [comment]
The rectangle with outline does not make much sense to me. Long gone are the times when I was the kind of guy who implemented things that might be useful. I try to keep finplot minimalistic while serving a breadth of functionality, this is just a small piece of that.

**Comment by workingshaw** [comment]
That's ok. Thanks.
