### ISSUE TITLE
Plot kills the kernel, having to force quit the process

### ISSUE THREAD

**Issue by kamkudla** [highfestiva/finplot#156]
I'm having a perplexing issue where finplot crashes the running python process. The chart shows up fine after I call `fplot.show()`. I then press ESC and the window closes, but the python process doesn't respond leaving me having to force quit and restart the kernel. It looks like it's 'ipykernel_launcher.py'. 

I'm running macOS 11.2.3, python 3.9.1 inside of a venv, finplot 1.6. 
I initially ran this in vscodium as a jupyter notebook, now tried it through the browser and same issue.

**Comment by highfestiva** [comment]
finplot plots native, and does [not](https://github.com/highfestiva/finplot#what-it-is-not) support web. Try running it outside of Jupyter.

**Comment by highfestiva** [comment]
@kamkudla ping

**Comment by kamkudla** [comment]
Hi @highfestiva, well that would certainly explain the behavior. I will try it outside of Jupyter and report back. Any plans to implement this to work alongside Jupyter?

**Comment by kamkudla** [comment]
Also, to clarify a point, I'm not using it in web rather using it within VScode. Though it still uses `ipykernel` I suppose.

**Comment by akarun2405** [comment]
@highfestiva why not? Jupyter notebook is very convenient way to iterate on algorithms. Can we not just have a way to export a png file and show it inline in jupyter?

**Comment by highfestiva** [comment]
@akarun2405 It requires rendering on-screen, taking a screenshot, closing the window. Far from an excellent way of doing things. Better have finplot do what it does well instead. At least that's my perspective as maintainer.
