### ISSUE TITLE
Can I open finplot window by clicking button?

### ISSUE THREAD

**Issue by hwjung92** [highfestiva/finplot#157]
The finplot is working well at the independent mode.
I would like to open it by clicking at the main window.
The below class was made for call.

===================================
class Ticker_Candlestick(QWidget):
    def __init__(self):
        super().__init__()

    def setupUI(self, MainWindow, ticker):
        self.ticker = ticker

================================

However, warning message was found and mouse hover is not working. 

**QCoreApplication::exec: The event loop is already running
Error sending hover exit event:**

Can you explain it how to open it by clicking button?
Thank you.

**Comment by highfestiva** [comment]
I'm not sure what's going on as you didn't add a minimal complete example, but perhaps you're calling `finplot.show()` when you should be calling `finplot.show(qt_exec=False)`?

**Comment by hwjung92** [comment]
Thank you. 
finplot.show(qt_exec=False) is working.

**Comment by hwjung92** [comment]
After closing the finplot winodw, I tried to open the finplot again. 
Whenever clicking a button ("show finplot") , the previouse finplot is shown again.
How can I destroy the finplot?

**Comment by highfestiva** [comment]
Unfortunately that is not supported by the API, so you'll have to hack some yourself. Try this when closing the window:
```python
fplt.windows.clear()
fplt.overlay_axs.clear()
fplt._clear_timers()
fplt.sounds.clear()
fplt.master_data.clear()
fplt.last_ax = None
```

**Comment by hwjung92** [comment]
Thank you. 
it works.
