### ISSUE TITLE
Using pandas_profiling and finplot in parallel fails

### ISSUE THREAD

**Issue by bm765** [highfestiva/finplot#158]
Hi,

thanks for bringing this software to life and maintaining it!

When I use `finplot` in parallel to `pandas_profiling`, an error occurs. Is there anything I can do myself to avoid this? 

Thanks in advance!

```python
import pandas as pd
import pandas_profiling
import finplot as fplt

df = pd.DataFrame({'a': [1,2,3]})
profile = pandas_profiling.ProfileReport(df, title='test' , explorative=True)
profile.to_file("export.html")

```

```
  File "/home/user/venv/myvenv/lib/python3.8/site-packages/finplot/pdplot.py", line 29, in plot
    return finplot.bar(_x, _y, **kwargs)
TypeError: bar() got an unexpected keyword argument 'figsize'
```

**Comment by highfestiva** [comment]
You have two options:
1. `pd.set_option('plotting.backend', None)` (or something like that to reset to matplotlib's backend).
2. Create a pull request where `finplot.bar` (and also `finplot.plot`) takes `**kwargs`.

**Comment by bm765** [comment]
Thanks!

```python
pd.set_option('plotting.backend', 'matplotlib')
```

does the job for suggestion 1.

**Comment by highfestiva** [comment]
I added support for unknown kwargs in ddd711a9e174007fbf3b554ef8e042d65fe4d49d.
