### ISSUE TITLE
qt trouble with spyder

### ISSUE THREAD

**Issue by alejivo** [highfestiva/finplot#16]
After install i got this error:
Error: spyder 4.1.3 has requirement pyqt5<5.13; python_version >= "3", but you'll have pyqt5 5.13.0 which is incompatible.

After it couldn't use spyder, the only solution was uninstall spyder and the library, next install spyder again.

I'm using conda with python 3.6 as it's the last supported by conda ta-lib.

**Comment by highfestiva** [comment]
Hi Alejandro,

One solution could be to install pyqt==5.9, as that does not have the 
bug of not rendering partial NaN curves.

Kind regards,
Jonas

------ Originalmeddelande ------
Från: "Alejandro" <notifications@github.com>
Till: "highfestiva/finplot" <finplot@noreply.github.com>
Kopia: "Subscribed" <subscribed@noreply.github.com>
Skickat: 2020-06-23 19:31:00
Ämne: [highfestiva/finplot] qt trouble with spyder (#16)

**Comment by alejivo** [comment]
TXS works now. It's an amazing Job!!
