### ISSUE TITLE
ModuleNotFoundError: No module named 'finplot'

### ISSUE THREAD

**Issue by lilly-chen** [highfestiva/finplot#161]
I am trying to install the library through: !pip install finplot

```
Collecting https://github.com/matplotlib/mpl_finance/archive/master.zip
  Downloading https://github.com/matplotlib/mpl_finance/archive/master.zip
Requirement already satisfied: matplotlib in c:\users\chenl\anaconda3\lib\site-packages (from mpl-finance==0.10.1) (3.2.1)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\chenl\anaconda3\lib\site-packages (from matplotlib->mpl-finance==0.10.1) (2.8.1)
Requirement already satisfied: cycler>=0.10 in c:\users\chenl\anaconda3\lib\site-packages (from matplotlib->mpl-finance==0.10.1) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\chenl\anaconda3\lib\site-packages (from matplotlib->mpl-finance==0.10.1) (2.1.4)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\chenl\anaconda3\lib\site-packages (from matplotlib->mpl-finance==0.10.1) (1.1.0)
Requirement already satisfied: numpy>=1.11 in c:\users\chenl\anaconda3\lib\site-packages (from matplotlib->mpl-finance==0.10.1) (1.15.4)
Requirement already satisfied: six in c:\users\chenl\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib->mpl-finance==0.10.1) (1.10.0)
Requirement already satisfied: setuptools in c:\users\chenl\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg (from kiwisolver>=1.0.1->matplotlib->mpl-finance==0.10.1) (27.2.0)
```

it seems successfully installed. how ever when i try to import: import finplot as fplt, it gives me the following error

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-16-e79273197bdf> in <module>
----> 1 import finplot as fplt

```
ModuleNotFoundError: No module named 'finplot'

**Comment by Trembles** [comment]
it should be in c:\users\chenl\anaconda3\lib\site-packages\finplot

**Comment by highfestiva** [comment]
Looks like you've tried `pip install mpl_finance`?

**Comment by highfestiva** [comment]
Yes, there are no dependencies on mpl_finance anywhere.

**Comment by lilly-chen** [comment]
Hi what should i do to able to import the finplot library? uninstall mpl_finance or something?

**Comment by highfestiva** [comment]
From your output which you pasted above, it doesn't look like you've installed `finplot`, but instead you've installed `mpl_finance`. Runing `pip install -U finplot` should be sufficient.

**Comment by highfestiva** [comment]
Also, the exclamation mark indicates you using Jupyter (?), which is [not supported](https://github.com/highfestiva/finplot#what-it-is-not).

**Comment by THuffam** [comment]
I am also having the same issue.  Have a python 3.7 environment in conda (anaconda) and used:
pip install finplot
Which installed fine.
Then tried to run the demo code on your home page and it fails with:
    import finplot as fplt
ModuleNotFoundError: No module named 'finplot'

I have tried installing it using -U option as you mention above but no change.
Any suggestions?

**Comment by highfestiva** [comment]
Sorry, haven't used conda myself.
