### ISSUE TITLE
Adding a line gives zero division error in interactive mode

### ISSUE THREAD

**Issue by aceffer** [highfestiva/finplot#166]
In the case of adding a line from (x0, **0.0**) to (x1, y1), when the interactive mode is enabled, line 2573 of init.py returns with 

> ZeroDivisionError: float division by zero

Code: `line = fplt.add_line((dates[100], 0.0), (dates[1100], 1.0), interactive=True)`

Line causing the error: `value = '%+.2f %%' % (100 * y1 / y0 - 100)`

**Comment by highfestiva** [comment]
Fixed in 39bd100e465895cb2fca7c10d9cf55a8cd031592.
