### ISSUE TITLE
Zoom rectangle appears at bad position when grids are enabled

### ISSUE THREAD

**Issue by aceffer** [highfestiva/finplot#167]
I ran embed.py in examples and when I added grids, the yellow zoom rectangle (right-click of the mouse) appears far from the cursor:

`ax.set_visible(xgrid=True, ygrid=True)`

When grids are disabled, the rectangle appears right next to the cursor.

**Comment by highfestiva** [comment]
Thanks, good catch! Fixed in 4d0b8d309c993e52f8b2346bdba97c364719e1c0.
