### ISSUE TITLE
Zoom stops working when one zoom in too much

### ISSUE THREAD

**Issue by aceffer** [highfestiva/finplot#168]
When someone uses the right-click zoom feature too much (e.g zooming in the graph too much ),  wheel zoom stops working and can't zoom out anymore. Not a very big deal, but sometimes I accidentally draw a too small rectangle and I can't go back.

I used analyze.py in the examples:

![cut](https://user-images.githubusercontent.com/83200710/116534804-498dbb80-a8e3-11eb-9fb3-7b11c5999e13.PNG)

Wheel zoom still works on the lower axes, but not on the upper one.

**Comment by highfestiva** [comment]
Fixed in 6031222.
