### ISSUE TITLE
module are deprecated in bitmex_ws

### ISSUE THREAD

**Issue by jbmustaq** [highfestiva/finplot#17]
module Instrument and constants are not available in bitmex websocket. Is it possible if you can update the code in https://github.com/highfestiva/finplot/blob/master/finplot/example-bitmex-ws.py

from bitmex_websocket import Instrument
from bitmex_websocket.constants import InstrumentChannels

**Comment by highfestiva** [comment]
This code works with bitmex-websocket-0.2.78, which is the most recent version. Update like so:

`pip install -U bitmex-websocket`
