### ISSUE TITLE
Update fplt.show()

### ISSUE THREAD

**Issue by DolbanutiyYoj** [highfestiva/finplot#170]
Hello! Please help me update the plot in real time. A window with one candle opens, after closing the window manually, a second window with two candles appears.

!!! - Timeout error. Try to reconnect.

![1](https://user-images.githubusercontent.com/46603761/116725764-d461d980-a9fb-11eb-9136-b137481845b0.PNG)
![2](https://user-images.githubusercontent.com/46603761/116725766-d4fa7000-a9fb-11eb-8b2f-1da979c5431e.PNG)

    import finplot as fplt
    import numpy as np
    import tinvest as ti
    import asyncio
    import pandas as pd

    TOKEN = "........................"

    d_1 = []
    c_1 = []
    o_1 = []
    h_1 = []
    l_1 = []
    v_1 = []
    plots = []

    async def main():
        async with ti.Streaming(TOKEN) as streaming:
            await streaming.candle.subscribe('BBG000N9MNX3', ti.CandleResolution.min1)
            async for event in streaming:
                d_1.append(event.time)
                c_1.append(float(event.payload.c))
                o_1.append(float(event.payload.o))
                h_1.append(float(event.payload.h))
                l_1.append(float(event.payload.l))
                v_1.append(float(event.payload.v))

                f1= {'Datetime': d_1,
                      'Close': c_1,
                      'Open': o_1,
                      'High': h_1,
                      'Low': l_1,
                      'Volume': v_1,
                      }

                cand = update_pl(f1)
                symbol = 'Apple'
                ax = fplt.create_plot(symbol)
                fplt.candlestick_ochl(cand, ax=ax)
                fplt.show()

    def update_pl(f1):
        df = pd.DataFrame(f1)
        df = df.rename(columns={'Datetime': 'time', 'Open': 'open', 'Close': 'close', 'High': 'high', 'Low': 'low',
                                                    'Volume': 'volume'})
        df.astype({'time': 'datetime64[ns]'})
        candlesticks = df[['time', 'open', 'close', 'high', 'low']]
        return candlesticks

    if __name__ == '__main__':
        try:
            task = asyncio.run(main())
        except KeyboardInterrupt:
            pass

//////////////////////////////////////////////////////////////

#f1= {'Datetime': d_1,
                  'Close': c_1,
                  'Open': o_1,
                  'High': h_1,
                  'Low': l_1,
                  'Volume': v_1,
                  }

{'Datetime': [datetime.datetime(2021, 4, 30, 16, 19, 35, 20224, tzinfo=datetime.timezone.utc)], 'Close': [702.64], 'Open': [702.21], 'High': [702.78], 'Low': [702.2], 'Volume': [5789.0]}
{'Datetime': [datetime.datetime(2021, 4, 30, 16, 19, 35, 20224, tzinfo=datetime.timezone.utc), datetime.datetime(2021, 4, 30, 16, 19, 43, 569066, tzinfo=datetime.timezone.utc)], 'Close': [702.64, 703.05], 'Open': [702.21, 702.21], 'High': [702.78, 703.05], 'Low': [702.2, 702.2], 'Volume': [5789.0, 8004.0]}
{'Datetime': [datetime.datetime(2021, 4, 30, 16, 19, 35, 20224, tzinfo=datetime.timezone.utc), datetime.datetime(2021, 4, 30, 16, 19, 43, 569066, tzinfo=datetime.timezone.utc), datetime.datetime(2021, 4, 30, 16, 19, 55, 823421, tzinfo=datetime.timezone.utc)], 'Close': [702.64, 703.05, 703.24], 'Open': [702.21, 702.21, 702.21], 'High': [702.78, 703.05, 703.39], 'Low': [702.2, 702.2, 702.2], 'Volume': [5789.0, 8004.0, 9673.0]}

////////////////////////////////////////////////////////////

#df = pd.DataFrame(f1)   
                          Datetime   Close    Open    High    Low  Volume
0 2021-04-30 16:19:35.020224+00:00  702.64  702.21  702.78  702.2  5789.0
                          Datetime   Close    Open    High    Low  Volume
0 2021-04-30 16:19:35.020224+00:00  702.64  702.21  702.78  702.2  5789.0
1 2021-04-30 16:19:43.569066+00:00  703.05  702.21  703.05  702.2  8004.0
                          169 Datetime   Close    Open    High    Low  Volume
0 2021-04-30 16:19:35.020224+00:00  702.64  702.21  702.78  702.2  5789.0
1 2021-04-30 16:19:43.569066+00:00  703.05  702.21  703.05  702.2  8004.0
2 2021-04-30 16:19:55.823421+00:00  703.24  702.21  703.39  702.2  9673.0

//////////////////////////////////////////////////////////////////

#candlesticks = (df[['time', 'open', 'close', 'high', 'low']])
                            time    open   close    high    low
0 2021-04-30 16:19:35.020224+00:00  702.21  702.64  702.78  702.2
                             time    open   close    high    low
0 2021-04-30 16:19:35.020224+00:00  702.21  702.64  702.78  702.2
1 2021-04-30 16:19:43.569066+00:00  702.21  703.05  703.05  702.2
                             time    open   close    high    low
0 2021-04-30 16:19:35.020224+00:00  702.21  702.64  702.78  702.2
1 2021-04-30 16:19:43.569066+00:00  702.21  703.05  703.05  702.2
2 2021-04-30 16:19:55.823421+00:00  702.21  703.24  703.39  702.2

**Comment by AlexStox** [comment]
I think something is happened with finplot.show() itself, because today I tried it on a new script and it didn't work. Then I tried to run the code that worked well previously, and it also failed. 

My error in finplot.show(): 
```
Traceback (most recent call last):

  File "<ipython-input-30-8027c277aae3>", line 146, in <module>
    fplt.show()

  File "C:\Users\Public\anaconda\lib\site-packages\finplot\__init__.py", line 1626, in show
    vb.pre_process_data()

  File "C:\Users\Public\anaconda\lib\site-packages\finplot\__init__.py", line 629, in pre_process_data
    self.y_max = df.max().max()

  File "C:\Users\Public\anaconda\lib\site-packages\pandas\core\generic.py", line 11468, in stat_func
    return self._reduce(

  File "C:\Users\Public\anaconda\lib\site-packages\pandas\core\series.py", line 4236, in _reduce
    return op(delegate, skipna=skipna, **kwds)

  File "C:\Users\Public\anaconda\lib\site-packages\pandas\core\nanops.py", line 129, in f
    result = alt(values, axis=axis, skipna=skipna, **kwds)

  File "C:\Users\Public\anaconda\lib\site-packages\pandas\core\nanops.py", line 873, in reduction
    result = getattr(values, meth)(axis)

  File "C:\Users\Public\anaconda\lib\site-packages\numpy\core\_methods.py", line 39, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)

TypeError: '<=' not supported between instances of 'numpy.ndarray' and 'str'
```

**Comment by AlexStox** [comment]
I;ve updated finplot to ver. 1.7 and seems like the flight is OK now :)

**Comment by highfestiva** [comment]
Those obscure marks are from the axes, those appearing in the middle belongs to the upper axis.

**Comment by DolbanutiyYoj** [comment]
> Эти неясные знаки-от осей, те, что появляются в середине, принадлежат верхней оси.

Please answer my question

**Comment by DolbanutiyYoj** [comment]
> Those obscure marks are from the axes, those appearing in the middle belongs to the upper axis.

Please answer my question

**Comment by highfestiva** [comment]
Yes. They are there for clarity.

**Comment by DolbanutiyYoj** [comment]
> Yes. They are there for clarity.

Sorry, I didn't ask two questions. These two questions are the author of AlexStox. Please help me solve my problem - the FIRST post.

//////////

"Hello! Please help me update the plot in real time. A window with one candle opens, after closing the window manually, a second window with two candles appears."

**Comment by DolbanutiyYoj** [comment]
I couldn't do that either

////////////////////////////

async def main():
    async def update_pl():
        async with ti.Streaming(TOKEN) as streaming:
            await streaming.candle.subscribe('BBG000N9MNX3', ti.CandleResolution.min1)
            async for event in streaming:
                d_1.append(event.time)
                c_1.append(float(event.payload.c))
                o_1.append(float(event.payload.o))
                h_1.append(float(event.payload.h))
                l_1.append(float(event.payload.l))
                v_1.append(float(event.payload.v))

                f1= {'Datetime': d_1,
                  'Close': c_1,
                  'Open': o_1,
                  'High': h_1,
                  'Low': l_1,
                  'Volume': v_1,
                  }
                print(f1)
                update_mu(f1)

    await update_pl()


def update_mu(f1):

    def update_rom(f1):
        df = pd.DataFrame(f1)
        return df

    def update():
        df = update_rom(f1)
        df = df.rename(columns={'Datetime': 'time', 'Open': 'open', 'Close': 'close', 'High': 'high', 'Low': 'low',
                            'Volume': 'volume'})
        df.astype({'time': 'datetime64[ns]'})
        candlesticks = df[['time', 'open', 'close', 'high', 'low']]
        symbol = 'USDT-BTC'
        ax = fplt.create_plot(symbol, rows=1)
        fplt.candlestick_ochl(candlesticks, ax=ax)


    update()
    fplt.timer_callback(update, 0.1)
    fplt.show()

**Comment by highfestiva** [comment]
`create_plot` should be called only once. `show` should be called only once. See examples.
