### ISSUE TITLE
multiple screen shot from several stocks 

### ISSUE THREAD

**Issue by raph1900** [highfestiva/finplot#171]
Hey, I know this question was already ask but I did not understand the answer. 
I am looking to screen-shot several stocks in a loop but it seems that `.show()` have to be written for the screen shot to be done.
I don't care that a plot is appearing but the loop wont continue to run until the plot is closed.   
is there a way to put the screen shot function into a loop? 
I need the screen-shots to mark entry/exit point that were made from a trading log. 
thanks! much appreciate

**Comment by highfestiva** [comment]
It *is* now possible, and especially so with an update I just made in 519ffe2:

```python
#!/usr/bin/env python3

import finplot as fplt
import numpy as np
import pandas as pd
from pyqtgraph import QtGui


timer = None
i = 0
def draw():
    global i
    if i >= 1:
        fplt.screenshot(open('screenshot-%04i.png'%i, 'wb'))
        fplt.close()
    i += 1
    fplt.winx = 0
    fplt.winy = 0
    # here you would load your data
    dates = pd.date_range('01:00', '01:00:01.200', freq='1ms')
    prices = pd.Series(np.random.random(len(dates))).rolling(30).mean() + 4
    fplt.plot(dates, prices)
    fplt.timer_callback(draw, 1, single_shot=True) # wait some until we're rendered
    fplt.show(qt_exec=False)


if __name__ == '__main__':
    draw()
    fplt.app = QtGui.QApplication.instance()
    fplt.app.exec_()
```

**Comment by raph1900** [comment]
hey. 
how exactly should I loop the code?  
```
    draw()
    fplt.app = QtGui.QApplication.instance()
    fplt.app.exec_()
```

**Comment by highfestiva** [comment]
You probably need a `show()` in every loop, and then close the window in between. I don't remember exactly, but it should be possible.
