### ISSUE TITLE
Memory leak when creating widget from FinPlot

### ISSUE THREAD

**Issue by d3v-S** [highfestiva/finplot#186]
Thank you for this amazing library.

I am having issues with memory leak with finplot. 

Here are the steps:
- create a QGraphicsView and attach created window (using create_plot_widget.ax_widget) to it 
- attach this graphicsview to a QVBoxlayout inside another QWidget.
-  after 30 seconds, remove this QGrpahicsView from the layout.
- Repeat this everytime creating a new graph.

When running gc.referrers, we can see that all the GraphicsView that have been attached to the finplot window. The list keeps on increasing and does not seem to be garbage collected. Manual deletion of graphicsview leads to error c/c++ object of FinViewBox has been deleted.

Similar error on manual deletion of plotItem and candleStick items

Is my design wrong or some error on my part? Or does finplot does it?

Current fix: Reuse the QGraphicsView.

```
 if gv is None:
        graphics_view = QGraphicsView() 
    else:
        graphics_view = gv
        
    if alignment == "horizontal":
        hbox = QHBoxLayout()
    else:
        hbox = QVBoxLayout()
    
    w = fplt.create_plot_widget(graphics_view.window(), 
                                rows=num_rows, 
                                init_zoom_periods=init_zoom_periods)
    list_axs = []  
    if num_rows == 1:
        list_axs = [w]
    else:
        for i in w:
            list_axs.append(i)

    for i in list_axs:
        hbox.addWidget(i.ax_widget)
        i.set_visible(crosshair=True, xaxis=True, yaxis=True, xgrid=True, ygrid=True)
           
    graphics_view.window().axs = list_axs       # finplot requres this property
    graphics_view.setLayout(hbox)
    return (graphics_view, w)      // freeing of these leads to Object deleted error.
```

**Comment by d3v-S** [comment]
seems to solved. Patch is in the pull request. Do tell me if I had approached the problem wrong.

**Comment by highfestiva** [comment]
Did you try using `fplt.reset()`?

**Comment by d3v-S** [comment]
I am sorry, there was no api for reset - ```fplt.reset``` AFAIK.

**Comment by highfestiva** [comment]
Sorry, my bad! Could you please post a minimal example to reproduce the error.

**Comment by d3v-S** [comment]
I did in pull request.

**Comment by highfestiva** [comment]
The zoom-thing is handled in the `examples/complicated.py`, no other restore functionality is required. I understand your problem in principle, and saw your almost-complete example in the pull request, but want a complete, minimal example.

**Comment by d3v-S** [comment]
Like I had said, ```complicated.py``` calls ```fplt.show()``` once at the end and it consists of one plot. I am talking about multiple widgets and plots, each of them independent of other with different creation times and deletions.  (like something I have shown in the uploaded picture)

That is the bare minimum things. I will try to post one example.

**Comment by d3v-S** [comment]
![app_error_update_data](https://user-images.githubusercontent.com/67001383/118462246-17ba8880-b71c-11eb-9b58-8ba309747d11.png)

This is one error I get when doing ```update_data``` and ```update_gfx```. At some places the plots are misplaced.
Hence, I sometimes prefer to destroy and re-create and zoom back to same location.

the ```autoviewrestore``` wont restore if the window has been changed.

**Comment by d3v-S** [comment]
I have a query? 

I am trying to plot different graphs in the same ```create_plot_widget```. ```update_data``` works if the x-axis is not different.

For example,
```create_plot_widget``` is called once. I can use ```update_data``` for changing from 'Apple' stocks to 'Google', on the same timeframe. But if I try to plot 'Apple' from 1 min to 3 min, using ```update_data```, plot is okay but x-axis remains the same, thus creating a lot of gaps. Can you point me to the api that is used to update the x-axis?

**Comment by highfestiva** [comment]
I'm referring to these lines:
```python
# save window zoom position before resetting
fplt._savewindata(fplt.windows[0])
...
# restores saved zoom position, if in range
fplt.refresh()
```
If you change timeframe, you want to call `ax.reset()`. Just like in `examples/embed.py`.
