### ISSUE TITLE
I see the README grows. Can I help to move everything to wiki ?

### ISSUE THREAD

**Issue by gryabov** [highfestiva/finplot#193]
Is it a good idea to move the description to wiki pages? I can help with it.

**Comment by highfestiva** [comment]
Absolutely, thank you!

**Comment by gryabov** [comment]
Please review a preliminary wiki https://github.com/gryabov/finplot/wiki . 

As I understand I cannot create a pull request for wiki.
The possible solution I found on SO is https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

**Comment by highfestiva** [comment]
Looks great! I don't know if this helps, but I added a Wiki page, which can be cloned from `https://github.com/highfestiva/finplot.wiki.git` and also github pages under `/root`. Feel free to play around with things or let me know if I can help!

**Comment by gryabov** [comment]
I've made as described in https://stackoverflow.com/a/11481887

Here the repo https://github.com/gryabov/finplot-wiki

**Comment by highfestiva** [comment]
Looking good, incorporated it. What do you think should be part of README.md? I guess it's best to link to the Wiki for most things? Also the [bug report template](https://github.com/highfestiva/finplot/tree/master/.github/ISSUE_TEMPLATE) says to read the README, but perhaps now it's best to read your [Snippets](https://github.com/highfestiva/finplot/wiki/Snippets) page.

**Comment by highfestiva** [comment]
Did some updates, added basic API doc and a tiny tutorial. I assume it's possible to make pull requests to [https://github.com/highfestiva/finplot.wiki.git](https://github.com/highfestiva/finplot.wiki.git)? This was a great idea! If you're up for it, fill in whatever you can think of that may help others.

**Comment by gryabov** [comment]
Hi, Is it ok I have permission to read the wiki https://github.com/highfestiva/finplot/wiki ?

I'm not sure how to edit the sidebar. Should I add API and Tutorial pages to the sidebar? 

> What do you think should be part of README.md?
I could be the same as wiki home page. And info the project has wiki.

**Comment by highfestiva** [comment]
You mean [https://github.com/highfestiva/finplot.wiki.git](https://github.com/highfestiva/finplot.wiki.git)? Does [this](https://github.com/highfestiva/finplot/wiki/_Sidebar/_edit) work?

**Comment by gryabov** [comment]
>Does this work?
Yes
