### ISSUE TITLE
It's crashing on colab as well as on Kaggle notebook.[BUG]

### ISSUE THREAD

**Issue by algopy** [highfestiva/finplot#194]
### Requirements (place an `x` in each of the `[ ]`)**
* [ ] I've read the [README](../README.md) and not found what I'm looking for.
* [ ] I've searched for any related issues and avoided creating a duplicate issue.
* [ ] I've updated finplot (`pip install -U finplot`).

### Code to reproduce

```python
import finplot as fplt
import pandas as pd
```

### Expected behavior
A clear and concise description of what you expected to happen instead.

#### Reproducible in:

*finplot version*:
*pyqtgraph version*:
*pyqt version*:

Not showing any kind of plot on Kaggle notebook even for the example plot.

![Screenshot_2021-05-22-09-45-35-57](https://user-images.githubusercontent.com/52496522/119214218-bcedac00-bae2-11eb-8c0d-51d34d6bef2b.jpg)

**Comment by highfestiva** [comment]
Closing, as user did not read the README, and would have found that web is not supported.
