### ISSUE TITLE
Question/Request: Convert time in Renko DataFrame to Normal Date

### ISSUE THREAD

**Issue by bergen288** [highfestiva/finplot#195]
### Requirements (place an `x` in each of the `[ ]`)**
* [x ] I realize finplot is not a web lib. (Hint: it's native!)
* [x ] I've read the [snippets](https://github.com/highfestiva/finplot/wiki/Snippets) and not found what I'm looking for.
* [x ] I've searched for any related issues and avoided creating a duplicate issue.
* [x ] I've updated finplot (`pip install -U finplot`).
* [x] I've supplied the required data to run my code below.

### Code to reproduce

```python
import finplot as fplt
import pandas as pd
import talib


ticket = 'SPY'
path = r'C:\Users\User\Documents\VSCode\Python\Data\\'
file_name = path + ticket + '.pickle'
df = pd.read_pickle(file_name)

ax, axv = fplt.create_plot(ticket, rows=2, maximize=False)
plot = fplt.renko(df[['Close','Volume']], ax=ax) # let renko transform volume by passing it in as an extra column
df_renko = plot.datasrc.df
df_renko['close1'] = df_renko['close'].shift()
df_renko['trix'] = talib.TRIX(df_renko['close'], timeperiod=3)
df_renko['obv'] = talib.OBV(df_renko['close'], df_renko['Volume'])
df_renko['sma1'] = talib.MA(df_renko['close'], timeperiod=5)
df_renko['sma2'] = talib.MA(df_renko['close'], timeperiod=15)
df_renko['rsi'] = talib.RSI(df_renko['close'], timeperiod=3)
print(df_renko[:20])
```

### Describe the bug
How to convert time below to normal date?

### Expected behavior
I pretty much love your Renko dataframe and would like to build a trading strategy with it.  However, I need to know the real time.  Can you help me out here?  It's the SPY data from 2010/01/02.

#### Screenshots
                    time   open  close   high    low     Volume  close1  trix            obv   sma1   sma2   rsi
0    1265241600000000000 115.17 108.77 115.17 108.77  356715700     NaN   NaN   356715700.00    NaN    NaN   NaN
1    1277769600000000000 108.77 102.37 108.77 102.37  373649500  108.77   NaN   -16933800.00    NaN    NaN   NaN
2    1312243199999999998 108.77 115.17 115.17 108.77  346653800  102.37   NaN   329720000.00    NaN    NaN   NaN
3    1312243199999999999 115.17 121.57 121.57 115.17  346653800  115.17   NaN   676373800.00    NaN    NaN 75.00
4    1312243200000000000 121.57 127.97 127.97 121.57  346653800  121.57   NaN  1023027600.00 115.17    NaN 81.82
5    1312761600000000000 121.57 115.17 121.57 115.17  702263900  127.97   NaN   320763700.00 116.45    NaN 45.00
6    1317600000000000000 115.17 108.77 115.17 108.77  365136800  115.17   NaN   -44373100.00 117.73    NaN 33.64
7    1318204800000000000 115.17 121.57 121.57 115.17  230666300  108.77  0.29   186293200.00 119.01    NaN 62.23
8    1319673600000000000 121.57 127.97 127.97 121.57  393220200  121.57  1.52   579513400.00 120.29    NaN 71.46
9    1340928000000000000 127.97 134.37 134.37 127.97  212250900  127.97  2.66   791764300.00 121.57    NaN 79.11
10   1352246400000000000 134.37 140.76 140.76 134.37  264304500  134.37  3.49  1056068800.00 126.69    NaN 85.10
11   1357084800000000000 140.76 147.16 147.16 140.76  192059000  140.76  3.99  1248127800.00 134.37    NaN 89.58
12   1365984000000000000 147.16 153.56 153.56 147.16  217259000  147.16  4.24  1465386800.00 140.76    NaN 92.82
13   1371686400000000000 153.56 159.96 159.96 153.56  321255900  153.56  4.32  1786642700.00 147.16    NaN 95.11
14   1381363200000000000 159.96 166.36 166.36 159.96  195955000  159.96  4.29  1982597700.00 153.56 130.10 96.69
15   1390521599999999999 166.36 172.76 172.76 166.36  208677100  166.36  4.21  2191274800.00 159.96 134.37 97.77
16   1390521600000000000 172.76 179.16 179.16 172.76  208677100  172.76  4.09  2399951900.00 166.36 139.49 98.50
17   1397088000000000000 179.16 185.55 185.55 179.16  172959000  179.16  3.96  2572910900.00 172.76 144.18 99.00
18   1406764800000000000 185.55 191.95 191.95 185.55  183479000  185.55  3.82  2756389900.00 179.16 148.87 99.33
19   1411603200000000000 191.95 198.35 198.35 191.95  150300000  191.95  3.69  2906689900.00 185.55 153.56 99.55

#### Reproducible in:

*OS*:  Windows 10
*finplot version*:  1.7
*pyqtgraph version*:  0.12.1
*pyqt version*: 5.15.4 (pyqt5)

**Comment by highfestiva** [comment]
Next time, please leave a running example, or code+data in a zip.
```python
import io
import finplot as fplt
import pandas as pd

data = ''',Time,Open,Close,High,Low,Volume,close1,trix,obv,sma1,sma2,rsi
0,1265241600000000000,115.17,108.77,115.17,108.77,356715700,NaN,NaN,356715700.00,NaN,NaN,NaN
1,1277769600000000000,108.77,102.37,108.77,102.37,373649500,108.77,NaN,-16933800.00,NaN,NaN,NaN
2,1312243199999999998,108.77,115.17,115.17,108.77,346653800,102.37,NaN,329720000.00,NaN,NaN,NaN
3,1312243199999999999,115.17,121.57,121.57,115.17,346653800,115.17,NaN,676373800.00,NaN,NaN,75.00
4,1312243200000000000,121.57,127.97,127.97,121.57,346653800,121.57,NaN,1023027600.00,115.17,NaN,81.82
5,1312761600000000000,121.57,115.17,121.57,115.17,702263900,127.97,NaN,320763700.00,116.45,NaN,45.00
6,1317600000000000000,115.17,108.77,115.17,108.77,365136800,115.17,NaN,-44373100.00,117.73,NaN,33.64
7,1318204800000000000,115.17,121.57,121.57,115.17,230666300,108.77,0.29,186293200.00,119.01,NaN,62.23
8,1319673600000000000,121.57,127.97,127.97,121.57,393220200,121.57,1.52,579513400.00,120.29,NaN,71.46
9,1340928000000000000,127.97,134.37,134.37,127.97,212250900,127.97,2.66,791764300.00,121.57,NaN,79.11
10,1352246400000000000,134.37,140.76,140.76,134.37,264304500,134.37,3.49,1056068800.00,126.69,NaN,85.10
11,1357084800000000000,140.76,147.16,147.16,140.76,192059000,140.76,3.99,1248127800.00,134.37,NaN,89.58
12,1365984000000000000,147.16,153.56,153.56,147.16,217259000,147.16,4.24,1465386800.00,140.76,NaN,92.82
13,1371686400000000000,153.56,159.96,159.96,153.56,321255900,153.56,4.32,1786642700.00,147.16,NaN,95.11
14,1381363200000000000,159.96,166.36,166.36,159.96,195955000,159.96,4.29,1982597700.00,153.56,130.10,96.69
15,1390521599999999999,166.36,172.76,172.76,166.36,208677100,166.36,4.21,2191274800.00,159.96,134.37,97.77
16,1390521600000000000,172.76,179.16,179.16,172.76,208677100,172.76,4.09,2399951900.00,166.36,139.49,98.50
17,1397088000000000000,179.16,185.55,185.55,179.16,172959000,179.16,3.96,2572910900.00,172.76,144.18,99.00
18,1406764800000000000,185.55,191.95,191.95,185.55,183479000,185.55,3.82,2756389900.00,179.16,148.87,99.33
19,1411603200000000000,191.95,198.35,198.35,191.95,150300000,191.95,3.69,2906689900.00,185.55,153.56,99.55'''

df = pd.read_csv(io.StringIO(data))
plot = fplt.renko(df[['Time','Close','Volume']]) # let renko transform volume by passing it in as an extra column
df_renko = plot.datasrc.df
print(pd.to_datetime(df_renko['time'], unit='ns'))
```
prints
```sh
0    2010-06-28 23:59:59.999999997
1    2010-06-28 23:59:59.999999998
2    2010-06-28 23:59:59.999999999
3    2010-06-29 00:00:00.000000000
4    2011-08-01 23:59:59.999999993
                  ...
66   2014-07-30 23:59:59.999999999
67   2014-07-31 00:00:00.000000000
68   2014-09-24 23:59:59.999999998
69   2014-09-24 23:59:59.999999999
70   2014-09-25 00:00:00.000000000
Name: time, Length: 71, dtype: datetime64[ns]
```

**Comment by bergen288** [comment]
Ok, the key is to have the following line:
```
df_renko['date'] = pd.to_datetime(df_renko['time']+1000, unit='ns').dt.date
```
Some lines have a few 'ns' short before midnight.  Is it safe to add 1000 ns to round up to correct date?

Thanks.

**Comment by highfestiva** [comment]
I have no idea.
