### ISSUE TITLE
Not all dates are labeled correctly in the plot by fplt.volume_ocv

### ISSUE THREAD

**Issue by bergen288** [highfestiva/finplot#196]
### Requirements (place an `x` in each of the `[ ]`)**
* [x ] I realize finplot is not a web lib. (Hint: it's native!)
* [x ] I've read the [snippets](https://github.com/highfestiva/finplot/wiki/Snippets) and not found what I'm looking for.
* [x ] I've searched for any related issues and avoided creating a duplicate issue.
* [x ] I've updated finplot (`pip install -U finplot`).
* [x ] I've supplied the required data to run my code below.

### Code to reproduce

```python
import finplot as fplt
import talib
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

ticket = 'SPY'
path = r'C:\Users\User\Documents\VSCode\Python\Data\\'
file_name = path + ticket + '.pickle'
df = pd.read_pickle(file_name)

w = fplt.foreground = '#eef'
b = fplt.background = fplt.odd_plot_background = '#242320'
fplt.candle_bull_color = fplt.volume_bull_color = fplt.candle_bull_body_color = fplt.volume_bull_body_color = '#352'
fplt.candle_bear_color = fplt.volume_bear_color = '#810'
fplt.cross_hair_color = w+'a'
plt.figure(figsize=(6,4))
ax, axt, axv = fplt.create_plot(ticket, rows=3, maximize=False)
plot = fplt.renko(df[['Close','Volume']], ax=ax) # let renko transform volume by passing it in as an extra column
df_renko = plot.datasrc.df
fplt.volume_ocv(df_renko[['time','open','close','Volume']], ax=axv)
plt.savefig("spy.png")
df_renko['datetime'] = pd.to_datetime(df_renko['time'], unit='ns')
df_renko['date0'] = pd.to_datetime(df_renko['time'], unit='ns').dt.date
df_renko['date1'] = pd.to_datetime(df_renko['time']+1000, unit='ns').dt.date
print(df_renko[:20])
fplt.show()
```

### Describe the bug
This is related with my closed issue 195.  As you can see below, the datetime is 1-2 ns before 2010/8/2 for lines 2 and 3.  The date0 is 2010/8/1; while the date1, with 1000 ns added, is 2010/8/2.  It's the common sense that date should be 2010/8/2 for lines 2 and 3.  Unfortunately, the plot by fplt.volume_ocv(df_renko[['time','open','close','Volume']], ax=axv) labels them as 2010/8/1.  Line 15 has the same issue.

By the way, how to save ax plot correctly?  My plt.savefig("spy.png") gives me nothing.  No error, no PNG file.
### Expected behavior
1. Correct date label in the plot by fplt.volume_ocv(df_renko[['time','open','close','Volume']], ax=axv).
2. Save plot correctly.

#### Screenshots
                   time        open       close        high         low     Volume                      datetime       date0       date1
0   1265241600000000000  115.171199  108.772799  115.171199  108.772799  356715700 2010-02-04 00:00:00.000000000  2010-02-04  2010-02-04
1   1277769600000000000  108.772799  102.374399  108.772799  102.374399  373649500 2010-06-29 00:00:00.000000000  2010-06-29  2010-06-29
2   1312243199999999998  108.772799  115.171199  115.171199  108.772799  346653800 2011-08-01 23:59:59.999999998  2011-08-01  2011-08-02
3   1312243199999999999  115.171199  121.569599  121.569599  115.171199  346653800 2011-08-01 23:59:59.999999999  2011-08-01  2011-08-02
4   1312243200000000000  121.569599  127.967999  127.967999  121.569599  346653800 2011-08-02 00:00:00.000000000  2011-08-02  2011-08-02
5   1312761600000000000  121.569599  115.171199  121.569599  115.171199  702263900 2011-08-08 00:00:00.000000000  2011-08-08  2011-08-08
6   1317600000000000000  115.171199  108.772799  115.171199  108.772799  365136800 2011-10-03 00:00:00.000000000  2011-10-03  2011-10-03
7   1318204800000000000  115.171199  121.569599  121.569599  115.171199  230666300 2011-10-10 00:00:00.000000000  2011-10-10  2011-10-10
8   1319673600000000000  121.569599  127.967999  127.967999  121.569599  393220200 2011-10-27 00:00:00.000000000  2011-10-27  2011-10-27
9   1340928000000000000  127.967999  134.366399  134.366399  127.967999  212250900 2012-06-29 00:00:00.000000000  2012-06-29  2012-06-29
10  1352246400000000000  134.366399  140.764799  140.764799  134.366399  264304500 2012-11-07 00:00:00.000000000  2012-11-07  2012-11-07
11  1357084800000000000  140.764799  147.163199  147.163199  140.764799  192059000 2013-01-02 00:00:00.000000000  2013-01-02  2013-01-02
12  1365984000000000000  147.163199  153.561599  153.561599  147.163199  217259000 2013-04-15 00:00:00.000000000  2013-04-15  2013-04-15
13  1371686400000000000  153.561599  159.959999  159.959999  153.561599  321255900 2013-06-20 00:00:00.000000000  2013-06-20  2013-06-20
14  1381363200000000000  159.959999  166.358399  166.358399  159.959999  195955000 2013-10-10 00:00:00.000000000  2013-10-10  2013-10-10
15  1390521599999999999  166.358399  172.756799  172.756799  166.358399  208677100 2014-01-23 23:59:59.999999999  2014-01-23  2014-01-24
16  1390521600000000000  172.756799  179.155199  179.155199  172.756799  208677100 2014-01-24 00:00:00.000000000  2014-01-24  2014-01-24
17  1397088000000000000  179.155199  185.553599  185.553599  179.155199  172959000 2014-04-10 00:00:00.000000000  2014-04-10  2014-04-10
18  1406764800000000000  185.553599  191.951999  191.951999  185.553599  183479000 2014-07-31 00:00:00.000000000  2014-07-31  2014-07-31
19  1411603200000000000  191.951999  198.350399  198.350399  191.951999  150300000 2014-09-25 00:00:00.000000000  2014-09-25  2014-09-25

[SPY.zip](https://github.com/highfestiva/finplot/files/6549618/SPY.zip)
![spy_renko](https://user-images.githubusercontent.com/65607761/119731138-8f876200-be44-11eb-9d7b-2319e70dbf2f.png)

**Comment by highfestiva** [comment]
One nanosecond before midnight is still not a new day. The screenshot save is done in a callback, as in the line example.

**Comment by bergen288** [comment]
I am not sure if short of a few "ns" is due to floating error or what.  If you don't think it's a mislabel,  I am fine with it.  

Can you give me an example to save finplot plot?

Thanks.

**Comment by bergen288** [comment]
In my example above, I added ```fplt.screenshot('SPY')``` immediately before ```fplt.show()```.  But I got ```ERROR: screenshot must be callbacked from e.g. timer_callback()```.  Any clue?
Thanks.

**Comment by bergen288** [comment]
Ok, it works in following way:
```
def save():
    fplt.screenshot(open('SPY.png', 'wb'))
fplt.timer_callback(save, 0.5, single_shot=True) # wait some until we're rendered
```
Unfortunately, it won't allow me to change output file name dynamically.  I tried following way:
```
def save(file):
    file=file+'.png'
    print(file)
    fplt.screenshot(open(file, 'wb'))
fplt.timer_callback(save('SPY'), 0.5, single_shot=True) # wait some until we're rendered
```
It gives me following error:
```
SPY.png
ERROR: screenshot must be callbacked from e.g. timer_callback()
Traceback (most recent call last):
  File "c:\Users\User\Documents\VSCode\Python\General\fin_renko.py", line 78, in <module>
    fplt.timer_callback(save('SPY'), 0.5, single_shot=True) # wait some until we're rendered
  File "C:\Users\User\anaconda3\lib\site-packages\finplot\__init__.py", line 1672, in timer_callback
    timer.timeout.connect(update_func)
TypeError: argument 1 has unexpected type 'NoneType'
```

Is there any way to allow me to change output "png" file name dynamically?
Thanks.

**Comment by highfestiva** [comment]
You're doing it wrong. Start by learning some basic programming instead of filing this as a bug in the library when it's only you who don't know what you're doing. In your code you're calling `save()` right away. The function call to `save()` happens _before_ `timer_callback()`. You really want something like this instead:
```python
fplt.timer_callback(lambda: save('SPY'), 0.5, single_shot=True) # wait some until we're rendered
```
