### ISSUE TITLE
[How To] Single Horizontal Volume Profile based on candles visible on the plot

### ISSUE THREAD

**Issue by pramitbiswas** [highfestiva/finplot#199]
[Issue #21](https://github.com/highfestiva/finplot/issues/21) answer shows Horizontal Volume Profile based on predefined const freq. But, How to plot a single Horizontal Volume Profile plot that dynamically changes based on time (candles) visible on the plot?

**Comment by highfestiva** [comment]
Keep a cache int of # of buckets. When it changes, remove the old horizontal volume and create a new one. The horizontal volume has an update function, but not sure I ever tested it.

**Comment by highfestiva** [comment]
This calculates your highest and lowest `y` in `ax`:
```python
x0,x1,y0,y1,cnt = ax.vb.datasrc.hilo(ax.vb.targetRect().left(), ax.vb.targetRect().right())
```
