### ISSUE TITLE
Plot a line from [x1, y1] to [x2, y2]

### ISSUE THREAD

**Issue by namankumar** [highfestiva/finplot#2]
Hey, this library is great and super easy to use. Thanks for writing it!

I'm now trying to draw a line between two coordinates but can't seem to get it working. Any recommendations how I can do this easily? Happy to send a PR if it comes to that.

I've tried a few things but none of them are satisfactory. Ideally, the interface would be similar to add_band(), it could be something like add_line(ax, [x1, y1], [x2, y2], width, color). 

Here is what I've tried so far:

Added the code below to the example in the README but this only works if I comment out the calls to fplt.PandasDataSource and candlestick_ochl. If I don't comment these lines, then the code below does not work.

`line = fplt.pg.LineSegmentROI([[0,0], [1100, 200]], pen=(255,9,0), movable=False)              
line.setZValue(60)                                                                             
ax2.addItem(line)`

Also tried `fplt.addline` and `fplt.pg.LineROI` but they show the same behavior as above.

How do I draw a line between two coordinates? Thanks!

**Comment by highfestiva** [comment]
Hi Naman,

Sorry for the late reply. I just added the feature you requested, fetch 
it by pip install -U finplot. I also included an example: 
https://github.com/highfestiva/finplot/blob/master/finplot/example-line.py. 
Good luck!

/Jonas

------ Originalmeddelande ------
Från: "Naman Kumar" <notifications@github.com>
Till: "highfestiva/finplot" <finplot@noreply.github.com>
Kopia: "Subscribed" <subscribed@noreply.github.com>
Skickat: 2019-06-26 08:18:22
Ämne: [highfestiva/finplot] Plot a line from [x1, y1] to [x2, y2] (#2)

**Comment by highfestiva** [comment]
Feature added.

**Comment by namankumar** [comment]
Hi Jonas, 

Thanks for this! Do you mind showing me an example that uses add_line with on the same plot as a candlestick graph? I can't get that to work. 
```
candle_src = fplt.PandasDataSource(df[['time','open','close','high','low']])
fplt.candlestick_ochl(candle_src, ax=ax)
```

I'm trying to draw the same line as you show in your screenshot, i.e., line with the label '+1.73%'
https://raw.githubusercontent.com/highfestiva/finplot/master/screenshot.jpg

Cheers, 
Namaan

**Comment by highfestiva** [comment]
Hi,

I just added support for adding interactive lines programatically (of 
the type you get when manually drawing one yourself with Ctrl+mouse 
drag). For a candle stick chart simply do something like:

importfinplotasfpltimportnumpyasnpimportpandasaspddates=pd.date_range('01:00','21:30',freq='1min')df=pd.DataFrame(np.random.random((len(dates),4)),index=dates).rolling(4).mean()+4hilo=df.apply(lambdar:r.sort_values().reset_index(drop=True),axis=1)df[2]=hilo[3]df[3]=hilo[0]plot=fplt.candlestick_ochl(df)line=fplt.add_line(plot.ax,(dates[100].timestamp(),4.4),(dates[1100].timestamp(),4.6),color='#9900ff',interactive=True)#fplt.remove_line(plot.ax, line)text=fplt.add_text(plot.ax,(dates[500].timestamp(),4.6),"I'm here alright!",color='#bb7700')#fplt.remove_text(plot.ax, text)fplt.show()
Good luck!

Kind regards,
Jonas

------ Originalmeddelande ------
Från: "Naman Kumar" <notifications@github.com>
Till: "highfestiva/finplot" <finplot@noreply.github.com>
Kopia: "Jonas Byström" <highfestiva@gmail.com>; "State change" 
<state_change@noreply.github.com>
Skickat: 2019-07-11 10:51:24
Ämne: Re: [highfestiva/finplot] Plot a line from [x1, y1] to [x2, y2] 
(#2)

**Comment by namankumar** [comment]
@highfestiva thanks I finally have it working! If I could request one more change, it would be to allow add_line to accept the same unit of time for plotting the x axis. Every other function in this library plots x axis in epoch in nanoseconds (pandas default) but add_line only accepts the epoch in seconds. 

Cheers. Awesome library!
Naman

**Comment by highfestiva** [comment]
Good catch Naman, thanks for letting me know instead of letting it 
slide! :)

Fixed, pushed, pipified.

/J

------ Originalmeddelande ------
Från: "Naman Kumar" <notifications@github.com>
Till: "highfestiva/finplot" <finplot@noreply.github.com>
Kopia: "Jonas Byström" <highfestiva@gmail.com>; "Mention" 
<mention@noreply.github.com>
Skickat: 2019-07-12 22:58:09
Ämne: Re: [highfestiva/finplot] Plot a line from [x1, y1] to [x2, y2] 
(#2)

**Comment by namankumar** [comment]
Works great, cheers!
