### ISSUE TITLE
finplot Real time Update

### ISSUE THREAD

**Issue by mohammadtirex** [highfestiva/finplot#200]
Hi
when I use finplot for ploting Candlestick and MACD simultaneously in a figure with 2 rows, it can't update the length of x axis for macd and the macd at below candles find delay candle by candle and it's position in the figure remain the same as the beginning while it's value is updating
I upload the fig. 

what should I do???
![delayd](https://user-images.githubusercontent.com/85229539/120471326-d1bb2100-c3b9-11eb-84b3-9bb6e8d4f3ea.JPG)

**Comment by highfestiva** [comment]
It would have been easier to follow if there was code. For instance, using the bug template. If it's a bug, file it as such. Otherwise use the discussions tab. Closing this for now.

**Comment by mohammadtirex** [comment]
import pandas as pd
import finplot as fplt
import requests

def update():
    Crypto  = 'BTCUSDT'
    Type    = '1min'
    url     = ('https://api.coinex.com/v1/market/kline?market=' + Crypto + '&' + 'type=' + Type)
    table   = requests.get(url).json()
    df      = pd.DataFrame(table['data'] ,columns='time open close high low amount volume market'.split())
    df      = df['time open close high low amount volume'.split()]
    df      = df.apply(pd.to_numeric) # COnvert all DataFrames to Numeric
    macd    = df.close.ewm(span=12).mean() - df.close.ewm(span=26).mean()
    signal  = macd.ewm(span=9).mean()
    df['macd_diff'] = macd - signal
    
    candlesticks = df['time open close high low'.split()]
    volumes = df['time open close volume'.split()]

    if not plots:
        global ax,ax2
        plots.append(fplt.candlestick_ochl(candlesticks))
        plots.append(fplt.volume_ocv(volumes, ax=ax.overlay()))
        plots.append(fplt.volume_ocv(df[['time','open','close','macd_diff']], ax=ax2, colorfunc=fplt.strength_colorfilter))
        plots.append(fplt.plot(macd, ax=ax2, legend='MACD'))
        plots.append(fplt.plot(signal, ax=ax2, legend='Signal'))
    else:
        # every time after we just update the data sources on each plot
        plots[0].update_data(candlesticks)
        plots[1].update_data(volumes)
        plots[2].update_data(df[['time','open','close','macd_diff']])
        plots[3].update_data(macd)
        plots[4].update_data(signal)
        
plots = []
ax,ax2 = fplt.create_plot('Realtime Bitcoin/USDT TF (Coinex)' , maximize=False ,rows = 2)
update()
fplt.timer_callback(update, 5) # update (using synchronous rest call) every N seconds

fplt.show()

**Comment by mohammadtirex** [comment]
Thank You Very Much
This is my code

**Comment by highfestiva** [comment]
See tutorial on Wiki. You should use this in the beginning:
```python
df = df.set_index('time')
```
and not pass the time around everywhere, as you don't understand what it means. So for instance:
```python
candlesticks = df['open close high low'.split()]
...
plots.append(fplt.volume_ocv(df[['open','close','macd_diff']], ax=ax2, colorfunc=fplt.strength_colorfilter))
```

**Comment by mohammadtirex** [comment]
Brilliants!! It's Work
Really Thank you, Do not criticize me. I'm a beginner in python and need help of big man like you
