### ISSUE TITLE
[How To] drag Y-axis up/down without zooming in/out

### ISSUE THREAD

**Issue by pramitbiswas** [highfestiva/finplot#201]
As mentioned in the title, how to drag Y-axis up/down without zooming in/out (similar to tradingview chart)?

**Comment by highfestiva** [comment]
Ctrl+ScrollWheel

**Comment by pramitbiswas** [comment]
Not what I required, but it is workable for my need. Thank you.

**Comment by khnh123** [comment]
Mac: Command+ScrollWheel
