### ISSUE TITLE
finplot time index set as local time not UTC time

### ISSUE THREAD

**Issue by mohammadtirex** [highfestiva/finplot#204]
Hi 
When I plot candlesticks, it appear as local time in x axis aka it shift by some value and is different to the real candlesticks corresponding timestamps
How Can back finplot time to It's Referenced value i.e UTC?
Below I showed What Happened.

![gg](https://user-images.githubusercontent.com/85229539/120926183-224fb880-c6f1-11eb-9b60-7c5d92566078.jpg)

**Comment by highfestiva** [comment]
https://github.com/highfestiva/finplot/wiki/Snippets#time-zone

**Comment by mohammadtirex** [comment]
**Thanks A lot...**
