### ISSUE TITLE
[BUG] Complicated.py Example websocket's on_message is never called.

### ISSUE THREAD

**Issue by shujaatak** [highfestiva/finplot#205]
While playing with complicated.py example I noticed that websocket's on_message is never called although websocket gets connected to the binance stream.

```
websocket connecting to wss://fstream.binance.com/stream...
websocket connected
```

Due to this bug the chart is never updated.

I have put print statement in the on_message function which never gets executed even though I waited for about 5 minutes or so although I had selected 1m timeframe.

**Comment by shujaatak** [comment]
on_message takes two arguments while only one `msg` is given, changing the on_message function to this solved the issue:
`def on_message(self, ws, msg):`

**Comment by highfestiva** [comment]
Thanks, my websocket lib was outdated. Fix in 2eaa4296e5ad37db0dc1e978e57fc9c9fd14b8f7. Next time, feel free to send in a pull request with the fix. :)

**Comment by JamesKBowler** [comment]
Hi,
This breaks the live updates. If you look at the `WebSocketApp` method named `_callback()` the first if block is called because the `self.on_message` is inspected with `ismethod`.

Snipping..

```python
    def _callback(self, callback, *args):
        if callback:
            try:
                if inspect.ismethod(callback):
                    callback(*args)
                else:
                    callback(self, *args)
```

removing the `ws` fixed it for me.

Versions installed are.
websockets: 0.57.0
finplot: 1.7

**Comment by highfestiva** [comment]
Yeah, the bitmex-ws example requires websocket-client 0.53.0. Dependency hell, not sure what to do about it. BitMEX's websocket is always dragging. Once I sent in a tiny pull request to them which took months to get approved, so don't know what to do exactly as I want the examples to be concise (and not compatible with every version out there).
