### ISSUE TITLE
[enhancement] Use manual zoom, panning

### ISSUE THREAD

**Issue by publine2** [highfestiva/finplot#210]
Would be good to have an option to disable automatic zooming/scaling/centering behavior while moving the chart back and forth. Automatic stuff sometimes making technical analysis harder.

**Comment by publine2** [comment]
sorry... I did not find the way how to change "bug" label to "enhancement" label.....

**Comment by highfestiva** [comment]
Please verify if your second bullet is not the same as exemplified in examples/embed.py? From my meager PyQt knowledge it seems close. If not, open a different enhancement for that, and remove the second bullet to this one. Also add some kinda name to the title.

**Comment by highfestiva** [comment]
Is Ctrl+MWheel not sufficient? Please supply an example of when that is not good enough.

**Comment by highfestiva** [comment]
If you're unwilling to supply an example, I'm unwilling to fix.
