### ISSUE TITLE
[enhancement] Dockable widgets

### ISSUE THREAD

**Issue by publine2** [highfestiva/finplot#211]
When we using multiple charts (like fplt.create_plot(..., rows=2, ...)), would be good to use pyqtgraph.dockarea system for each chart - that will make charts sizable, closeable, movable, attachable, detachable, .....

**Comment by publine2** [comment]
...still cannot get how to attach correct label here....

**Comment by highfestiva** [comment]
Example added by @ATILIUS-REGULUS.
