### ISSUE TITLE
[BUG] Plotting more than once removes background grid and all other plots except OCHL candles

### ISSUE THREAD

**Issue by roadtorunway** [highfestiva/finplot#213]
### Requirements (place an `x` in each of the `[ ]`)**
* [x] I realize finplot is not a web lib. (Hint: it's native!)
* [x] I've read the [snippets](https://github.com/highfestiva/finplot/wiki/Snippets) and not found what I'm looking for.
* [x] I've searched for any related issues and avoided creating a duplicate issue.
* [x] I've updated finplot (`pip install -U finplot`).
* [x] I've supplied the required data to run my code below.

Thank you for your extensive effort on creating this library and giving a very clean yet immersive framework to plot. I'm developing a small interface for running my strategies / ideas and its hardly been a few days since I started using Python. 

There was once other instance where a user had mentioned this issue which was resolved by updating all the libraries. But I've only installed the entire software a few days back so I'm sure all the libraries are updated. I don't realize where my code has gone wrong or is there something inherent in Python / libraries.

### Code to reproduce
```import finplot as fplt
import yfinance as yf
import easygui as eg
from tkinter import *

tickername = []
chartData = []

def ysource():
    global chartData
    global tickername
    msg1 = "Enter the name of the Index / Stock / Commodity"
    title1 = "Yahoo Finance"
    tickername = eg.enterbox(msg1, title1, "AAPL")
    tickerdata = yf.Ticker(tickername)
    chartData = tickerdata.history(period = '1mo', interval = '15m')
    return chartData, tickername

def plotchart(df, ax):
    fplt.candlestick_ochl(df[['Open', 'Close', 'High', 'Low']])
    df['Close'].ewm(span=9).mean().plot(ax=ax, legend='EMA')
    fplt.show()

window = Tk()
ax = fplt.create_plot('%s' % tickername)
ax.set_visible(xgrid=True, ygrid=True)
button1 = Button(window, text = 'Source Data - Yahoo Finance', command = ysource)
button1.place(x=20,y=25)
button2 = Button(window, text = 'Plot Chart', command = lambda: plotchart(chartData,ax))
button2.place(x=20,y=65)
window.mainloop()
```

### Describe the bug
Plotting the chart the **first time** is a breeze and has **no errors / omissions**. However, when I close the finplot window, click to plot again, the grid in the background and any other plots (Indicators) that I have added in the code are not displayed.

### Expected behavior
Once the finplot window is closed, could we not change the source data / other indicator settings and plot the chart again? 
I have tried using:
fplt._ax_reset(ax)
fplt.refresh()
fplt.windows.clear()
fplt.close()
but haven't got any success in getting the issue resolved.

#### Screenshots
This is the first time I plot the chart.
![image](https://user-images.githubusercontent.com/86202413/122764755-6a5c0700-d2bd-11eb-9add-d1b5fd235d68.png)
![image](https://user-images.githubusercontent.com/86202413/122764876-8b245c80-d2bd-11eb-971e-7bf1bd050af5.png)
![image](https://user-images.githubusercontent.com/86202413/122764948-a1321d00-d2bd-11eb-9ccd-093c9737ca10.png)

This is the second time I plot the chart.
![image](https://user-images.githubusercontent.com/86202413/122765044-b73fdd80-d2bd-11eb-9753-1502b45c24e6.png)

This are the libraries updated.
![image](https://user-images.githubusercontent.com/86202413/122766043-b491b800-d2be-11eb-9ee2-163be1ab125a.png)

#### Reproducible in:

*OS*: Windows 10
*finplot version*: 1.7
*pyqtgraph version*: 0.12.1
*pyqt version*: 5.15.4

**Comment by highfestiva** [comment]
This is because the first time you create the window explicitly, and enable showing the grid in your startup code. The next time, the window is created automatically for you, as no window exists. To fix it, move the `create_plot()` function along with the grid stuff to inside of your `plotchart()` function, and it should work smoothly.

**Tip:** learn some basic programming, it will save you tons of time in the next few months.

**Comment by roadtorunway** [comment]
Hey! it worked as I put the two lines inside the function. Thanks for the quick solve :) Have a lot to learn ahead.
