### ISSUE TITLE
Orderflow (footprint) example?

### ISSUE THREAD

**Issue by IvaOsi** [highfestiva/finplot#218]
Hello! It would be very cool to have an example of a Footprint graphic

(they use about the same data as in the examples) but how to make them I do not know, could you add an example?

some example what i mean

![Screenshot_32](https://user-images.githubusercontent.com/17671542/124177832-70ba6200-dab9-11eb-8f40-a03ad99f92f7.png)
Note that at the bottom there is a table whose data depend on the graph and this table moves with the graph
One cell of the table = one timeframe on the chart

**Comment by highfestiva** [comment]
I don't know where to get that kind of data. On the volume profile I did do, I just used high-res data and aggregated that. But that's not the actual numbers, just a (bad?) approximation.

**Comment by IvaOsi** [comment]
> I don't know where to get that kind of data. On the volume profile I did do, I just used high-res data and aggregated that. But that's not the actual numbers, just a (bad?) approximation.

I found the data and for me the problem is now to draw these tables, maybe you could help me.

Data can be taken from api bitmech.

It provides a last bid ask option.

**Comment by highfestiva** [comment]
Could you please provide URL where I can get the data?

**Comment by IvaOsi** [comment]
> Could you please provide URL where I can get the data?
Sure
https://www.bitmex.com/api/explorer/#!/Trade/Trade_get

**Comment by highfestiva** [comment]
You'd probably use [this URL](https://www.bitmex.com/api/v1/quote/bucketed?binSize=1m&symbol=XBT&count=200&startTime=2021-06-25), and then you'd have to (in the current implementation) plot the red bars first, by adding the blue ones, then plot the blue ones using the same timeframe and buckets on top of the red ones. That should get you what you're looking for.

**Comment by highfestiva** [comment]
Before I make a full-fledged example, could you verify that you're looking for something like this?
![image](https://user-images.githubusercontent.com/160303/132327439-e4ad1761-01f7-4b90-9019-462a60d3a549.png)

**Comment by IvaOsi** [comment]
> Before I make a full-fledged example, could you verify that you're looking for something like this?
> ![image](https://user-images.githubusercontent.com/160303/132327439-e4ad1761-01f7-4b90-9019-462a60d3a549.png)

It looks very cool! awesome work. 

Only instead of candles there should be lists:

![image](https://user-images.githubusercontent.com/17671542/132329134-1a1aa0d6-2ae3-40d3-9557-e4a3615df457.png)

It would also be very convenient to sign the tables at the bottom of the side

**Comment by highfestiva** [comment]
That part is an entirely new feature, which is too time consuming for me unfortunately. May I suggest volume profiles as an alternative? It's not identical, but displays similar data.

**Comment by IvaOsi** [comment]
> That part is an entirely new feature, which is too time consuming for me unfortunately. May I suggest volume profiles as an alternative? It's not identical, but displays similar data.

whats about not volume profile but tpo chart 
![image](https://user-images.githubusercontent.com/17671542/132360761-cfbd9c6c-b30d-4dcc-97a8-47534720fde4.png)

**Comment by arul67800** [comment]
Volume profile like real time candle which shows the order book fight would
be awesome😊

**Comment by highfestiva** [comment]
Sorry, but no. If you can contribute one yourself in some well-written code I'd be happy to accept your pull request though.
