### ISSUE TITLE
Is it possible to connect with line between dumb markers in the second example

### ISSUE THREAD

**Issue by guanlin123** [highfestiva/finplot#22]
Hello, 
Is it possible to connect with line between dumb mark in the second example?

the code is as below, just copy this from GitHub,

# place some dumb markers on low wicks
lo_wicks = df[['open','close']].T.min() - df['low']
df.loc[(lo_wicks>lo_wicks.quantile(0.99)), 'marker'] = df['low']
fplt.plot(df['time'], df['marker'], ax=ax, color='#4a5', style='^', legend='dumb mark')

Thanks

**Comment by highfestiva** [comment]
That's easy, try `fplt.plot(df.time, df.marker.interpolate())` on the line after.

**Comment by guanlin123** [comment]
Thanks, it's great.
