### ISSUE TITLE
Transaction Bubble Plot

### ISSUE THREAD

**Issue by JamesKBowler** [highfestiva/finplot#221]
Hello,

Is it possible to plot bubbles on the chart like this [example](https://www.cryptodatadownload.com/data/bitstamp/)?

![image](https://user-images.githubusercontent.com/24221328/124834530-d99d5080-df77-11eb-96dc-8599e9a2b477.png)

The data would come from the L2 Orderbook websocket, such as `timestamp, price, ordersize and buy or sell`.

Would be a cool indicator on the `complicated.py` example

Thanks

**Comment by highfestiva** [comment]
Yeah, but the sizes of the bubbles would have to come in different buckets, as each time series has a specific size. But apart from that, it's just to use scatter plot with `fplt.plot(..., style='o', color='#f00')`.

**Comment by highfestiva** [comment]
Not ideal perhaps, but see [bubble-table.py](https://github.com/highfestiva/finplot/blob/master/finplot/examples/bubble-table.py) example.
