### ISSUE TITLE
How to make crosshair disappear when the mouse leaves the finplot?

### ISSUE THREAD

**Issue by shujaatak** [highfestiva/finplot#224]
I am searching for a way to show crosshair only when the mouse is inside the finplot otherwise hide it.

**Comment by shujaatak** [comment]
When [this pull request](https://github.com/highfestiva/finplot/pull/229) gets merged, this issue can safely be closed.

**Comment by highfestiva** [comment]
I recommend using application code for this (i.e. adding a listener and show/hide the crosshair).
