### ISSUE TITLE
Is there a way to draw k line legend for every candle 

### ISSUE THREAD

**Issue by guanlin123** [highfestiva/finplot#23]
Hello, 
Is there a way to draw k line legend for every candle as below picture?
Thanks

<img width="308" alt="image" src="https://user-images.githubusercontent.com/57237649/89746136-b1e50480-daea-11ea-989b-c70b55b7b014.png">

**Comment by highfestiva** [comment]
I'm not sure I understand the question but if you just want to update the legend when mouse hovering, look at example-snp500.py.

**Comment by guanlin123** [comment]
Nice solution. This does help and thank you.
