### ISSUE TITLE
How to draw Rectangles as shown in the screenshot in the finplot's readme file.

### ISSUE THREAD

**Issue by shujaatak** [highfestiva/finplot#230]
I wonder how to draw rectangles as shown in the screenshot in the finplot's readme file:
![image](https://user-images.githubusercontent.com/14161646/126036536-6696b8ae-d314-4b36-ae12-6724f76b0e34.png)

I want to draw such rectangles of different colors dynamically in real-time graph.
**I want the rectangle to resize as new data comes in. If the price increases I will fill the rectangle with green color else with red color.**

**Comment by highfestiva** [comment]
See the microsoft/google example. Think it's called 'overlay' or something like that.
