### ISSUE TITLE
Is the log - log scale plot possibble ? 

### ISSUE THREAD

**Issue by MateKristof** [highfestiva/finplot#231]
I would like plot the Bitcoin price to log - log scale chart.
Similar to this:
```
import finplot as fplt
import numpy as np
from matplotlib import pyplot as plt

df = fplt.pd.read_csv("BLX.csv", parse_dates=['time'], index_col='time').sort_index()
x = np.arange(0, len(df["close"]))

plt.loglog(x, df["close"])
plt.grid(True, which="both", ls="-")
plt.show()
```
![BLX](https://user-images.githubusercontent.com/9765439/126310934-04b11d5e-f56b-4d4a-9034-acbd18f2b6f8.jpg)
Matplotlib is good but not as powerful as finplot. Is it possiple to plot log - log scale chart with finplot ?

**Comment by highfestiva** [comment]
I think it might be, but you'd have to use some pyqtgraph calls (finplot's api does not support it). I'd try something like this:

1. Replace the bottom axes with a `pg.AxisItem`.
2. Set log X- and Y-scale on your axis, `ax.setLogMode(x=True, y=True)`

GL!

**Comment by highfestiva** [comment]
The effect of log in "small ranges," such as 2000-2020 is slight (and not very useful for backtesting). Closing this.
