### ISSUE TITLE
about background settings

### ISSUE THREAD

**Issue by eternalranger** [highfestiva/finplot#24]
def create_plot(title='Finance Plot', rows=1, init_zoom_periods=1e10, maximize=True, yscale='linear'):
    global windows, last_ax
    pg.setConfigOptions(foreground=foreground, background="#333333")

if background color settings could be a parameter of create_plot function, it will be better. thanks !

**Comment by highfestiva** [comment]
There are almost a hundred settings already, so I think these things are better handled in some other way. For now you can do:

````python
fplt.foreground = '#fff'
fplt.background = '#333'
fplt.create_plot()
fplt.show()
````

There are also a bunch of other color settings you can and should change if you want dark mode. Good luck!

**Comment by eternalranger** [comment]
Great！I tried your suggestions, that's exactly the dark mode i want. Now anybody who use my project can easily plot pictures contain kline and indicators. Thanks finplot !
