### ISSUE TITLE
[BUG] Examples dockable.py and embed.py can't be launched. ImportError.

### ISSUE THREAD

**Issue by Resumane** [highfestiva/finplot#240]
(base) H:\-\Finplot>python dockable.py
Traceback (most recent call last):
  File "embed.py", line 6, in <module>
    from PyQt5.QtGui import QApplication, QGridLayout
ImportError: cannot import name 'QApplication' from 'PyQt5.QtGui' (C:\Users\-\anaconda3\lib\site-packages\PyQt5\QtGui.pyd)

(base) H:\-\Finplot>python embed.py
Traceback (most recent call last):
  File "embed.py", line 6, in <module>
    from PyQt5.QtGui import QApplication, QGridLayout
ImportError: cannot import name 'QApplication' from 'PyQt5.QtGui' (C:\Users\-\anaconda3\lib\site-packages\PyQt5\QtGui.pyd)

I'm using Windows 10, typical Anaconda installation, exact same error on my laptop which has a very recent installation with no customization at all.

**Comment by highfestiva** [comment]
Thanks! Adapted to new PyQt5 class moves in commit 0a3a19a.
