### ISSUE TITLE
Y-axis values with correct significant decimals

### ISSUE THREAD

**Issue by shujaatak** [highfestiva/finplot#241]
Finplot **doesn't show** correct significant decimals on y-axis. In the following screenshot you can see that any trailing zeros are not printed. Note: I have used **LINAUSDT** as the symbol whose value is well below 1USDT.

![image](https://user-images.githubusercontent.com/14161646/130607509-5d395d3c-8b3b-445b-854c-17785d703232.png)

**Comment by highfestiva** [comment]
Good point, I'll look into it.
