### ISSUE TITLE
Index error when trying to plot from a csv file

### ISSUE THREAD

**Issue by cmarian5** [highfestiva/finplot#243]
Hi, 

I am trying to plot candlestick chart using csv as source but I am getting the following error:  
`IndexError: index 4 is out of bounds for axis 0 with size 4`

My code looks like:
`import finplot as fplt
import pandas as pd

df = pd.read_csv("2020.csv")

df= df[1000:3000]

fplt.candlestick_ochl(df[['OPEN', 'CLOSE', 'HIGH', 'LOW']])
fplt.show()
`

Dataframe structure is the following:
`                  DATE                OPEN     HIGH      LOW    CLOSE
1000  2020-01-02 09:40  1.11779  1.11780  1.11747  1.11756
1001  2020-01-02 09:41  1.11756  1.11767  1.11743  1.11752
1002  2020-01-02 09:42  1.11753  1.11753  1.11724  1.11724
1003  2020-01-02 09:43  1.11726  1.11728  1.11712  1.11718
1004  2020-01-02 09:44  1.11719  1.11737  1.11717  1.11724
1005  2020-01-02 09:45  1.11724  1.11745  1.11724  1.11744
1006  2020-01-02 09:46  1.11743  1.11744  1.11725  1.11731
1007  2020-01-02 09:47  1.11728  1.11740  1.11728  1.11739
1008  2020-01-02 09:48  1.11738  1.11746  1.11712  1.11712
1009  2020-01-02 09:49  1.11712  1.11731  1.11711  1.11725`

I have the following modules installed:
`argon2-cffi==20.1.0
astroid==2.5.1
attrs==21.2.0
backcall==0.2.0
bleach==4.0.0
certifi==2021.5.30
cffi==1.14.6
charset-normalizer==2.0.4
colorama==0.4.4
debugpy==1.4.1
decorator==5.0.9
defusedxml==0.7.1
entrypoints==0.3
finplot==1.7
idna==3.2
ipykernel==6.2.0
ipython==7.26.0
ipython-genutils==0.2.0
isort==5.8.0
jedi==0.18.0
Jinja2==3.0.1
jsonschema==3.2.0
jupyter-client==7.0.1
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
lazy-object-proxy==1.6.0
lxml==4.6.3
MarkupSafe==2.0.1
matplotlib-inline==0.1.2
mccabe==0.6.1
mistune==0.8.4
multitasking==0.0.9
nbclient==0.5.4
nbconvert==6.1.0
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.4.3
numpy==1.21.2
packaging==21.0
pandas==1.3.2
pandocfilters==1.4.3
parso==0.8.2
pickleshare==0.7.5
plotly==5.2.1
prometheus-client==0.11.0
prompt-toolkit==3.0.20
pycparser==2.20
Pygments==2.10.0
pylint==2.7.2
pyparsing==2.4.7
PyQt5==5.15.4
PyQt5-Qt5==5.15.2
PyQt5-sip==12.9.0
pyqtgraph==0.12.2
pyrsistent==0.18.0
python-dateutil==2.8.2
pytz==2021.1
pywin32==301
pywinpty==1.1.3
pyzmq==22.2.1
requests==2.26.0
Send2Trash==1.8.0
six==1.16.0
tenacity==8.0.1
terminado==0.11.1
testpath==0.5.0
tornado==6.1
traitlets==5.0.5
urllib3==1.26.6
wcwidth==0.2.5
webencodings==0.5.1
wrapt==1.12.1
yfinance==0.1.63`

I also attached the csv file.
[2020.csv](https://github.com/highfestiva/finplot/files/7066507/2020.csv)

**Comment by highfestiva** [comment]
You need a column, or index, for timestamps.
