### ISSUE TITLE
Move the chart to the far left of the screen for lines

### ISSUE THREAD

**Issue by SARPSARP090** [highfestiva/finplot#247]
I have to end the lines where the graphics end. I want to draw the graphic up to the left side of the area, creating empty space and drawing in the empty space. Can you help me ?

Example Picture : https://www.resimupload.org/r/1zeea

**Comment by highfestiva** [comment]
So you want the candlestick plot to the left, and then plot something on the right-hand side? Either you create two separate plots, one being the candle plot on the left, and the one on the right is your plot. Or you use a large value for `fplt.right_margin_candles`. Or you can create an overlay to plot something on top of the right side of the existing plot. It pretty much depends on what you want to accomplish.

**Comment by SARPSARP090** [comment]
As it turns out, I want to pull the candles on a single floor to the left and extend the trend line further than the graph. In other words, I want to be able to move the line to the right much further than the graph, so that the line I have drawn does not end where the graph ends.
