### ISSUE TITLE
Coordinates of the Line I Draw Manually

### ISSUE THREAD

**Issue by SARPSARP090** [highfestiva/finplot#248]
Hello there. I am using your example in the link below. I want to generate a "Buy Signal" when prices go above the line I drew manually. Therefore, how can I perceive that the prices are above the line I drew? Is there a certain coordinate of the line or something?

https://github.com/highfestiva/finplot/blob/master/finplot/examples/complicated.py

**Comment by highfestiva** [comment]
Hi! You can find all the RoIs you've drawn in the list `ax.vb.rois`. The manually drawn line is made up of segements, see `finplot.FinPolyLine` for more details.
