### ISSUE TITLE
Would you please tell me how to plot negative volume?

### ISSUE THREAD

**Issue by lijiatin** [highfestiva/finplot#249]
```python
import pandas as pd 
import finplot as fplt 
import datetime
fplt.display_timezone = datetime.timezone.utc

df = pd.read_pickle(r'C:\Users\l\Desktop\fdoge2108m')
df['datetime'] = pd.to_datetime(df.index).astype('int64')
df.set_index(df['datetime'],inplace=True)

fplt.volume_ocv(df[['high','low','sell_volume']])#high and low just for same color
fplt.plot(df['sell_volume']*-1)

fplt.show()
```
Hi! I tried to plot sell volume (market maker is the seller,define in negative),but all bars just didn't show up(below the x-axis,tried the snp500 macd example,just didn't work). Some advice will be appreciated. Best wishes!

**Comment by lijiatin** [comment]
Sorry don't know some how I added the bug label(not very familiar with github operations), just closed the issue,still looking for help..

**Comment by highfestiva** [comment]
Please also post a little of your data (preferably in a zip), so it's easy for me to test.

**Comment by lijiatin** [comment]
https://github.com/lijiatin/file/blob/main/BTCUSDT827.zip 

After decompression use pd.read_pickle，should be look like [https://imgurl.org/img/e71d44bbd1edea22](url)

**Comment by highfestiva** [comment]
Forget it, not loading your untrusted pickle.
