### ISSUE TITLE
second row always be white background

### ISSUE THREAD

**Issue by eternalranger** [highfestiva/finplot#25]
```
fplt.foreground = '#FFFFFF'
fplt.background = '#333333'
self.__ax, self.__ax2, self.__ax3 = fplt.create_plot(symbol, rows=3)
```
when i create more than 1 rows, second row always be white background, how can i make it be a dark mode like other rows.

**Comment by highfestiva** [comment]
`finplot.odd_plot_background` perhaps? Look at the first few lines in finplot/__init__.py.
