### ISSUE TITLE
If the manually drawn line is less than the candle closing value

### ISSUE THREAD

**Issue by SARPSARP090** [highfestiva/finplot#250]
Hello there. Thank you for an excellent library. But what I want to do is: I want to detect whether the line I have drawn manually is not less than or greater than the closing value of the candle. In this respect
- I tried getting the line segments. I failed.
- When I try to get the line values ​​manually, the value is constantly variable. Can I ask you for an example of a line symbolizing whether it is less than or greater than the candle closing value?

**Comment by highfestiva** [comment]
Please post a minimal code example.

**Comment by SARPSARP090** [comment]
Can you do your sizing below?
What I'm asking is, if the price closes on a line I've drawn manually, can you make a classic print function?

Url: https://github.com/highfestiva/finplot/blob/master/finplot/examples/complicated.py

Example picture : [Click Please](https://resmim.net/i/aaaaaa.Q3HAn)

**Comment by highfestiva** [comment]
```python
#!/usr/bin/env python3

import finplot as fplt
import numpy as np
import pandas as pd


dates = pd.date_range('01:00', '01:00:01.200', freq='1ms')
prices = pd.Series(np.random.random(len(dates))).rolling(30).mean() + 4

ax = fplt.create_plot()
fplt.plot(dates, prices, width=3, ax=ax)

def check_lines():
    for roi in ax.vb.rois:
        try:
            handle = roi.handles[-1]
            if handle['pos'].y() > prices.iloc[-1]:
                print('endpoint above last price')
            else:
                print('last price above endpoint')
        except:
            pass

fplt.timer_callback(check_lines, 2.0)
fplt.show()
```
To check if above line you need a tiny bit of math. I support the plotting framework, not your algorithm.

**Comment by SARPSARP090** [comment]
You are a perfect person. If only you knew for a great good... The good that was too much has passed. I am a Muslim Turk. I want to thank you in the language of my religion.
GOD BLESS YOU!!!!
