### ISSUE TITLE
Programmatically extending manually drawn line

### ISSUE THREAD

**Issue by SARPSARP090** [highfestiva/finplot#253]
How can I make the manually drawn line auto-extend? How can I make my manual line extend to the new segment at the opening of the new candle?

**Comment by highfestiva** [comment]
You can move the last segment of the currently drawn line. If you see that `ax.vb.draw_line != None`, there is a line you can use. You can move the last handle (-1) by `ax.vb.draw_line.movePoint(-1, my_new_pos)`. GL!

**Comment by SARPSARP090** [comment]
Unfortunately I don't have my computer with me right now. So I can't wait to try your suggestion on Monday. I must say I am grateful to you.

**Comment by SARPSARP090** [comment]
Sorry, I'm still new. ax.vb.movePoint(-1, 4.6) and ax.vb.movePoint(-1, p1+1) fail. The program terminates itself. When I assign a number (int and float) to the variable p1 on MovePoint or set a combination of p1+1, the program exits. What could be the reason?

**Comment by highfestiva** [comment]
The reason could be that you're not supplying a point, and that you're trying to add one to a point. I'm here to support finplot, not to teach you Python.
