### ISSUE TITLE
How to zoom-in Symbols like the Candlestick

### ISSUE THREAD

**Issue by crazysurajit** [highfestiva/finplot#255]
I stumbled upon this just yesterday, and I'm blown away by its simplicity and power -- especially the Cursor (wasted hundreds of hours trying to achieve the same using Matplotlib). **Keep up the great work!**

Now, I want the Symbols (`symbol = {'v':'t', '^':'t1', '>':'t2', '<':'t3'}`) to zoom-in as well together with the Candlestick's rectangles, is there a way?
![image](https://user-images.githubusercontent.com/12027492/132966762-92a45209-7fad-4850-902b-a33448f085ec.png)

**Comment by highfestiva** [comment]
You *can* zoom in on their positions, but you *can't* make their sizes larger. Which is a good thing, as 10 visible glyphs in a 1M candlestick set would become ridiculously large if you zoom in to 100 candles. Like 100,000,000 times larger area. I don't think I'd like that.

**Comment by crazysurajit** [comment]
Yes, actually realized the same after I had commented -- it's a good thing. Anyway thanks a lot.
