### ISSUE TITLE
Twin Axes

### ISSUE THREAD

**Issue by crazysurajit** [highfestiva/finplot#263]
I want to create a Twin Axes (sharing the x-axis) similar to `ax.twinx()` in matplotlib.
I'm using `ax.overlay(scale=1, yaxis=True)` to achieve the same.
However when the max date (in x-axis) is different in the two data sets, overlaid graph do not share the parent's x-axis.
For e.g. in this image Blue line's max date available was 2021-09-27 and Red line's max date is 2021-09-28, but both got plotted on for the date 2021-09-28
![image](https://user-images.githubusercontent.com/12027492/135057918-117c9ed6-48e6-459d-9cbc-1cc05fc487e8.png)

Also when there's a label overlap in the y-axis I get this warning
`QGridLayoutEngine::addItem: Cell (0, 1) already taken`

**Comment by crazysurajit** [comment]
Just found if I merge the two data sets into one dataframe then it plots correctly.

**Comment by highfestiva** [comment]
Please show me the code that fails so I can correct for it.

**Comment by crazysurajit** [comment]
Not sure if this helps -- I usually download csv using _yfinance_ and read it back.
```
df1 = pd.read_csv('data/A.csv', parse_dates=[0], index_col=0)
df2 = pd.read_csv('data/B.csv', parse_dates=[0], index_col=0)
df3 = pd.read_csv('data/C.csv', parse_dates=[0], index_col=0)
df4 = pd.read_csv('data/D.csv', parse_dates=[0], index_col=0)

ax = fplt.create_plot('Twin Axes')
fplt.plot(df1[['Adj Close']], ax=ax, color='r', width=1.5)

axo = ax.overlay(scale=1, yaxis=True)
fplt.plot(df2[['Adj Close']], ax=axo, color=0)

axo = ax.overlay(scale=1, yaxis=False)  # if label overlaps (yaxis=True) throws the QGridLayoutEngine warning
fplt.plot(df3[['Adj Close']], ax=axo, color=1)

axo = ax.overlay(scale=1, yaxis=False)
fplt.plot(df4[['Adj Close']], ax=axo, color=2)

fplt.show()
```

**Comment by crazysurajit** [comment]
Not sure if this is right -- I usually download csv using _yfinance_ and read it back.
```
df1 = pd.read_csv('data/A.csv', parse_dates=[0], index_col=0)
df2 = pd.read_csv('data/B.csv', parse_dates=[0], index_col=0)
df3 = pd.read_csv('data/C.csv', parse_dates=[0], index_col=0)
df4 = pd.read_csv('data/D.csv', parse_dates=[0], index_col=0)

ax = fplt.create_plot('Twin Axes')
fplt.plot(df1[['Adj Close']], ax=ax, color='r', width=1.5)

axo = ax.overlay(scale=1, yaxis=True)
fplt.plot(df2[['Adj Close']], ax=axo, color=0)

axo = ax.overlay(scale=1, yaxis=False)  # if label overlaps (yaxis=True) throws the QGridLayoutEngine warning
fplt.plot(df3[['Adj Close']], ax=axo, color=1)

axo = ax.overlay(scale=1, yaxis=False)
fplt.plot(df4[['Adj Close']], ax=axo, color=2)

fplt.show()
```

**Comment by highfestiva** [comment]
Either inline a pinch of data or zip the data and a working example and upload here.

**Comment by crazysurajit** [comment]
there's some issue with the data, sorry, nothing to do with finplot
