### ISSUE TITLE
[BUG] black screenshot 

### ISSUE THREAD

**Issue by sademakn** [highfestiva/finplot#268]
I added these lines to my code 
```
def save():
    fplt.screenshot(open('screenshot.png', 'wb'))
fplt.timer_callback(save, 0.5, single_shot=True) # wait some until we're rendered```

but the screenshot is totaly black . 
Isn't a simple way to write figure to png file ??

**Comment by highfestiva** [comment]
Please add a full bug report according to the template. This doesn't tell me anything. Did you try the line.py example?

**Comment by highfestiva** [comment]
@sademakn ping

**Comment by highfestiva** [comment]
Follow the bug template, what OS are you on, what versions of dependant libraries are you using?

**Comment by sademakn** [comment]
finplot 1.7
Ubuntu 20.04

right now it's not a big deal for me. I've done my job with taking screen-shots. 
thanks for the great library.

**Comment by highfestiva** [comment]
So, do you know why they were black, and now they're not?

**Comment by highfestiva** [comment]
I'm only on Windows, so I can't debug this unfortunately. Do you think the screenshotting might be taking place in another virtual screen, or something like that? If you have the opportunity to move the window to the upper-left or lower-left corner of the first virtual screen before taking the screenshot, that might be helpful. If that doesn't help, and you can't or don't want to help, I'm forced to close this unforunately.
