### ISSUE TITLE
Installing Finplot in Anaconda

### ISSUE THREAD

**Issue by Dogsbreath1** [highfestiva/finplot#269]
I am trying to install Finplot in Anaconda and get:

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\Python1\\anaconda3\\Lib\\site-packages\\PyQt5\\QtCore.pyd'
Consider using the `--user` option or check the permissions.

Any ideas what I should do? I want to use it with the Spyder in Anaconda. I did experiment a bit, didn't have any success and ended up having to reinstall Anaconda.....

**Comment by highfestiva** [comment]
"Access is denied" sounds like that folder's permissions need fixing, not like a finplot bug.
