### ISSUE TITLE
[BUG] When using pyinstaller to create exe, errors with the plotting backend 

### ISSUE THREAD

**Issue by noclipper** [highfestiva/finplot#274]
I am using pyinstaller to create an exe of a script that uses finplot but keep experiencing the following error:

`ValueError: Could not find plotting backend 'finplot.pdplot'. Ensure that you've installed the package providing the 'finplot.pdplot' entrypoint, or that the package has a top-level `.plot` method.`

the finplot _init_ file, around ~2650, this occurs:
`# use finplot instead of matplotlib
pd.set_option('plotting.backend', 'finplot.pdplot')`

which then sets off an error for pandas: 
pandas\plotting\_core.py,  in _load_backend

------------------------------------------------

A quick way to recreate the issue I am having is to take 
https://github.com/highfestiva/finplot/blob/master/finplot/examples/analyze.py
and create a single exe with 
`python -m PyInstaller -F analyze.py`
Then run the .exe created from cmd and you will see the issue above.

**Comment by highfestiva** [comment]
Either explicitly add the `finplot.pdplot` module to your build, or simply comment out the `pd.set_option` line line in `finplot/__init__.py`. Or, if you find some nice way of making the depencency explicit in finplot's code (which I'm sure there is), please send a pull request.

**Comment by noclipper** [comment]
I got it working with a combination of your suggestions -> 
Commented out:
>`pd.set_option` line line in `finplot/__init__.py`.

and then imported pdplot.py into my main file (before finplot) and used the `pd.set_option` in my main file near the top. 

Thank you so much

**Comment by doohun** [comment]
or you can use  --hiddenimport=finplot.pdplot option in pyinstaller
