### ISSUE TITLE
Issue with Alpaca API

### ISSUE THREAD

**Issue by Srithar-ccs** [highfestiva/finplot#275]
Hi,
Can you shown an example with alpaca api pls, I have been breaking my head with the api and also converted the data to datetime64[ns] and still doesn't display the time on x-axis

Alpaca link - https://alpaca.markets/docs/api-documentation/api-v2/market-data/alpaca-data-api-v2/historical/#quotes

```
ax = fplt.create_plot('MACD - Pivots', rows=1)
        prices['timestamp'] = pd.to_datetime(prices['timestamp'])
        prices['timestamp'] = prices['timestamp'].dt.tz_localize(None)
        prices = prices.rename(columns={'timestamp': 'time'})
        # prices.index = prices['time']
        print(prices['time'])
        prices['hist'] = hist
        candles = prices[['time', 'open', 'close', 'high', 'low']]
        fplt.candlestick_ochl(candles, ax=ax)
fplt.show()
```
![image](https://user-images.githubusercontent.com/8614905/139612607-d1ed10cf-be2f-4520-8b69-5569db862cfb.png)

**Comment by highfestiva** [comment]
Post a complete, minimal example and I'll have a look.

**Comment by Srithar-ccs** [comment]
Hi Thank you for your reply, I finally found out the issue. My data has duplicate time records because it has different ohlc for that exact same timestamp and so your library doesn't complain about the issue and just plots the sequence. Just a feature request: it would be great if you throw a runtime warning like duplicate time records found hence falling back to sequence! that would be great.
