### ISSUE TITLE
[BUG]  index 4 is out of bounds for axis 0 with size 4

### ISSUE THREAD

**Issue by sunjar2020** [highfestiva/finplot#278]
### Requirements (place an `x` in each of the `[ ]`)**
* [x ] I realize finplot is not a web lib. (Hint: it's native!)
* [x] I've read the [snippets](https://github.com/highfestiva/finplot/wiki/Snippets) and not found what I'm looking for.
* [x] I've searched for any related issues and avoided creating a duplicate issue.
* [x] I've updated finplot (`pip install -U finplot`).
* [x] I've supplied the required data to run my code below.

### Code to reproduce
```python
import finplot as fplt
import pandas as pd
df = pd.read_csv(r"i:\aapl.csv") #also tried use df = yfinance.download('AAPL')
fplt.candlestick_ochl(df[['Open', 'Close', 'High', 'Low']])
fplt.show()
```

### Describe the bug
I used simplest example code, the local file 'aapl.csv' is from the data I read with yfinance and saved to the hard disk with df.to_csv saved. 

Regardless of whether it is read using yfinance or pd.read(df) method, as long as fplt.show() is executed, the following error will occur. Once I turned off Idle window and turned it on again, the fplt.show() works normally, but then it didn’t work anymore with aht error messages. I saw on stackoverflow that someone also mentioned this ‘index 4 is out of bounds…” issue. (https://stackoverflow.com/questions/53697655/how-to-plot-candlesticks-in-python)

aapl.csv download link:
https://xfl.jp/BW1VIj

------ error message ------
Traceback (most recent call last):
  File "I:\fp.py", line 6, in <module>
    fplt.show()
  File "C:\Users\PCPC\AppData\Local\Programs\Python\Python37\lib\site-packages\finplot\__init__.py", line 1705, in show
    refresh()
  File "C:\Users\PCPC\AppData\Local\Programs\Python\Python37\lib\site-packages\finplot\__init__.py", line 1698, in refresh
    vb.update_y_zoom(datasrc.init_x0, datasrc.init_x1)
  File "C:\Users\PCPC\AppData\Local\Programs\Python\Python37\lib\site-packages\finplot\__init__.py", line 880, in update_y_zoom
    _,_,hi,lo,cnt = datasrc.hilo(x0, x1)
  File "C:\Users\PCPC\AppData\Local\Programs\Python\Python37\lib\site-packages\finplot\__init__.py", line 332, in hilo
    v = self.cache_hilo[query] = self._hilo(x0, x1)
  File "C:\Users\PCPC\AppData\Local\Programs\Python\Python37\lib\site-packages\finplot\__init__.py", line 347, in _hilo
    valcols = df.columns[self.scale_cols]
  File "C:\Users\PCPC\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexes\base.py", line 4307, in __getitem__
    result = getitem(key)
IndexError: index 4 is out of bounds for axis 0 with size 4

-----------------------

#### Reproducible in:

*OS*: Windows7 and Ubuntu 20.04
*finplot version*:  1.7
*pyqtgraph version*: 0.12.3
*pyqt version*:5.15.6

**Comment by highfestiva** [comment]
When you read it from csv, you're not passing the timestamp. Either add the `Date` column first in the call to create the candlesticks, or better yet, make it the index by `df = df.set_index('Date')` first.

**Comment by sunjar2020** [comment]
> When you read it from csv, you're not passing the timestamp. Either add the `Date` column first in the call to create the candlesticks, or better yet, make it the index by `df = df.set_index('Date')` first.

Hi, highfestiva :+1: 
Thanks a lot, problem resolved.
