### ISSUE TITLE
Headless and PNG exports to BytesIO

### ISSUE THREAD

**Issue by k1mbl3** [highfestiva/finplot#28]
What is best approach to run finplot in a headless environment (docker, for instance)? Since it will be a HTTP server, how could i dump the entire plot to a BytesIO object to serve it later in a request? Thanks.

**Comment by highfestiva** [comment]
I just added support for saving a screenshot to file (https://github.com/highfestiva/finplot/blob/master/finplot/example-line.py#L16).

Do this to save screen shot to memory:
````python
...
def save():
    import io
    f = io.BytesIO()
    fplt.screenshot(f)
    do_something(f)
fplt.timer_callback(save, 0.5, single_shot=True) # wait some until we're rendered
fplt.show()
````

**Comment by k1mbl3** [comment]
Sorry the late reply. Thank you so much!

**Comment by engineertree5** [comment]
Hello HighFestiva,

I'm trying to save the file as a png. and i'm not sure I follow the above example or the one that you linked to saving as a file. I'm following along through the screenshot example and the one you linked to on Sep the 5th. i'm getting a blank image with zero bytes. Any thoughts here? I'm thinking the save function is not passing the right data back to the `timer_callback` or something.

I have this running as a class.

```python
class stock_list(object):

def __init__(self, stock_pick, time_length ):
        self.stock_pick = stock_pick #creates an attribute called stock and is assigned to value of stock
        self.time_length = time_length

def get_stocks(self):
    #pull list of stocks from user and begin to perform TA and FA
        stock_pick = self.stock_pick
        for stock in stock_pick:
            company = yf.Ticker(stock)
            self.get_ta(company,time_length)

def get_ta(self, company, time_length):
        """
        Method for performing technical analysis on given companies.
        Values needed are the company & time length of market data.
        """
        self.company = company
        self.time_length = time_length
        today = stock_list.today
        end = dt.datetime(today.year, today.month,today.day)
        start = dt.datetime(today.year -1, today.month,today.day)

        short_name = company.get_info()['shortName']
        company_symbol = company.get_info()['symbol']

       dates = pd.date_range('01:00', '01:00:01.200', freq='1ms')
       prices = pd.Series(np.random.random(len(dates))).rolling(30).mean() + 4
       fplt.plot(dates, prices, width=3)
       line = fplt.add_line((dates[100], 4.4), (dates[1100], 4.6), color='#9900ff', interactive=True)
       text = fplt.add_text((dates[500], 4.6), "I'm here alright!", color='#bb7700')
        fplt.timer_callback(self.save, 0.5, single_shot=True) # wait some until we're rendered

    def save(self):
        # import io
        # f = io.BytesIO()
        # fplt.screenshot(f)
        fplt.screenshot(open('screenshot.png', 'wb'))

```

Everything works that I was able to test and i'm loving this module! but the screenshot save is giving me a hard time. Its more than likely something i'm overlooking within the magic behind the code that takes the screenshot. 

link to code here if you are having trouble reading: https://github.com/engineertree5/tree5_treehouse/blob/master/tree_types/100/pyetf.py#L104-L153

Thanks for your time

**Comment by highfestiva** [comment]
You're not calling `show()`?

**Comment by engineertree5** [comment]
🙃 that is embarassing....I made the assumption that it would save the image without needing to show the graph, like a `plt.savefig()` function. Ok so this is taking an ACTUAL screenshot of what is on the screen. I need to go the headless route to get this fully automated. 

I need to do more testing on my raspberry pi before coming back. I commented a bit prematurely, my bad on that and thanks for responding.

 The end goal is to loop through a list of stocks, apply technical indicators, and post to the web for the commuinty to analyze. I'm currently doing this headless via cronjob and my pi ([my bot](https://twitter.com/FiliTheTester)).

**Comment by nek06** [comment]
I have a telegram bot for the channel, and there I implemented the function of displaying a graph in the bot via your fin plot. Everything is fine, the graph is drawn according to the user parameters, but there is no sending until I close the Fin Plot graph window. how can I solve it? fplt. close () does not work

**Comment by highfestiva** [comment]
What happens when you try `fplt.close()`? Did you put it right after the screenshot save call?

**Comment by nek06** [comment]
Yes, absolutely right, I did it as you have in the examples. But closing the window for some reason does not happen with the graf

**Comment by nek06** [comment]
def save():

  fplt.screenshot(open('screenshot.png', 'wb'))
fplt.timer_callback(save, 0.5, single_shot=True)

fplt.show()
time.sleep(5)
fplt.close()

**Comment by nek06** [comment]
I found a solution, added a closing function:
def save():

 fplt.screenshot(open('screenshot.png',` 'wb'))
fplt.timer_callback(save, 0.5, single_shot=True)
def close():   !!!!!
    fplt.close()
fplt.timer_callback(close, 1, single_shot=True)
fplt.show()

Thank you!!!! But i have another questions, how can i change colour for cnadlestik?

**Comment by highfestiva** [comment]
See snp500 example, as well as others.
