### ISSUE TITLE
Monthly Overlay to Daily Candles

### ISSUE THREAD

**Issue by mcmillinre3** [highfestiva/finplot#281]
Hi, I have been trying to overlay monthly candles over daily OCHL candles. I have gotten this to work for weekly candles by following a previous question here: https://github.com/highfestiva/finplot/issues/27 (changing the offset to 2.1 works after resetting the timezone to utc with yfinance daily data). However, since the months do not have standard spacing (e.g. 5 days for weekly), is there a way to use a list of candle widths? I tried but got a "TypeError: can't multiply sequence by non-int of type 'float'" in line 1029 of the __innit__ file for finplot. it seems there is not a way to accept a list currently, is there  a workaround?

**Comment by highfestiva** [comment]
Strange, `float` is supported in `x_offset`, as demonstrated by the overlay example. It would help if you sent me the callstack that breaks, instead of just the line, as you're using an old version. Try updating with `pip install -U finplot` too.
