### ISSUE TITLE
Four questions about finplot

### ISSUE THREAD

**Issue by sunjar2020** [highfestiva/finplot#282]
I am a newbie to finplot. After several days of programming and reading example and issue on github, I have made my own beautiful plot. But I still have four questions about beautifying the plotting.

Q1. Regarding adjusting the size of each axis(plot window/viewbox) individually, I have read issue-56, but I don't understand the meaning of followed scale factors.
```
fplt.windows[0].ci.layout.setRowStretchFactor(0, 1)
fplt.windows[0].ci.layout.setRowStretchFactor(1, 2)
fplt.windows[0].ci.layout.setRowStretchFactor(2, 3)
```
 I have tried a lot and still haven't found their regularity. I currently have 5 axis. The first one is a candlestick, which occupies about half the width of the screen. I hope the 2nd and 3rd axis can be larger than the 4th and 5th. But I tried for a long time and couldn't make it by adjusted those few parameters(0,1;1,2;2,3 etc). Can you tell me the detailed meaning of those parameters?

Q2. Can each axis(viewbox) be framed(add a bold line)?

Q3. Regarding the color settings, I saw:
```
background = '#fff'
odd_plot_background = '#fff'
candle_bull_color = '#26a69a'
```

I understand that this 6-digit number represents the color definition, but I am not sure about the 3-digit number. Is it 16(R)×16(G)×16(B) colors? 

Q4. The last question is whether the label/legend font can be changed.

Thank you very much for your excellent work and such an amazing library.

**Comment by highfestiva** [comment]
Q1. Unfortunately not, I remember experiencing something similar. You'd have to look into the eminent `pyqtgraph`, which is the underlying library that handles this.

Q2. I guess so, but this is part of `pyqtgraph` too.

Q3. There are tree, four, six or eight hex digits in a color code. If four or eight, the last part is for alpha channel. You are correct in your assumption about RGB. It's a web standard.

Q4. I'm sure it can, same as Q2.

GL and post a screenshot so we can see what you've accomplished in your beautification! :)

**Comment by sunjar2020** [comment]
Hi, highfestiva:

Thanks for your reply. Unfortunately, I have no any experience with pyqt at all. It seems that I need to find some time to study pyqt. If I can complete my final user interface, I will be happy to upload a picture, it all depends on the finplot.

Thank you again for your comments anyway.
