### ISSUE TITLE
Bar statics example ?

### ISSUE THREAD

**Issue by CRY-D** [highfestiva/finplot#285]
Hello, first of all, let me say i'm really in love with finplot and i would say thank you, because of this library I don't use the ugly (ploty, mplfinance..) any more.

It would be very cool to have an example of a Bar statics
i would to know how to make it, I do not know how to start, could you add an example **or some hints to do** ?

here some example what i mean
**One cell of the table = one candle**

![DeepinScreenshot_select-area_20211214153959](https://user-images.githubusercontent.com/16564491/146028445-1fce319c-a226-4564-8cf6-19d5abefb645.png)

**here the project i'm working on.**

![Annotate-a-local-image](https://user-images.githubusercontent.com/16564491/146029031-5e1ea351-78fe-47f5-b036-9ff354b8b24b.png)

**Comment by highfestiva** [comment]
I actually have one in the making, will add it to the examples when I looked into it a bit further. Don't know if the API will fit nicely in, and don't have the time to do it today. Ping me if I forget! :)

**Comment by highfestiva** [comment]
See [bubble-table.py](https://github.com/highfestiva/finplot/blob/master/finplot/examples/bubble-table.py) example.

**Comment by CRY-D** [comment]
done.
thank you s much
