### ISSUE TITLE
Getting exception AppWindowAtom' object has no attribute 'axs'

### ISSUE THREAD

**Issue by rajendrasp** [highfestiva/finplot#289]
Hi
I have placed finplot inside a QWidget like below

        self.tab1.fplt_widget = pg.PlotWidget(plotItem=fplt.create_plot_widget(self.window()))

        self.tab1.btn = QPushButton("Press me")

        # pull some data
        symbol = 'USDT-BTC'
        url = 'https://bittrex.com/Api/v2.0/pub/market/GetTicks?marketName=%s&tickInterval=fiveMin' % symbol
        data = requests.get(url).json()

        # format it in pandas
        df = pd.DataFrame(data['result'])
        df = df.rename(columns={'T':'time', 'O':'open', 'C':'close', 'H':'high', 'L':'low', 'V':'volume'})
        df = df.astype({'time':'datetime64[ns]'})
        candles = df[['time','open','close','high','low']]

        fplt.candlestick_ochl(candles)

When I pan the chart using mouse drag, I get following error

AttributeError: 'AppWindowAtom' object has no attribute 'axs'

'AppWindowAtom' is my QMainWindow. What do I need to do set solve this error?
I can share the minimal working code if you want to take a look

**Comment by highfestiva** [comment]
See [embed.py:25](https://github.com/highfestiva/finplot/blob/master/finplot/examples/embed.py#L25). (The `axs` property is required for `finplot` to find all the axes in all viewboxes which are rendered.)
