### ISSUE TITLE
Using finplot with a tkinter GUI

### ISSUE THREAD

**Issue by Ioanni5** [highfestiva/finplot#29]
Hello, 

I am trying to make a tkinter GUI that will launch a finplot chart once an item in a list is selected and a button is pressed. 

The action works, but only once. 
If I close the finplot window and I press the button again the chart is not launched again.
So in effect I cannot select another item from the list and chart it, unless I restart the app.

If you can assist in what I am missing it would be greatly appreciated.

Below is my code

https://github.com/Ioanni5/python-examples/blob/7e52d70cc5d13064338e8737c060ddac3e9fd067/y%20finance%20tkinter%20and%20finplot.py

**Comment by highfestiva** [comment]
Hi Ioanni5,

seems as though you're using an old version? Try

pip install -U finplot

to update to v1.0. This code works for me:

#!/usr/bin/env python3importyfinanceimportpandasaspdfromtkinterimport*importfinplotasfplt


myList = ['ES=F', 'NQ=F']
fileNames = []

for name in myList:
     df = yfinance.download(name, start='2019-01-01' )
     fileName = name +'.csv'
     df.to_csv(fileName)
     fileNames.append(fileName)


defdrawChart():
     index = listbox1.curselection()[0]
     df = pd.read_csv(fileNames[index], index_col='Date', parse_dates=True )
     fplt.candlestick_ochl(df[['Open', 'Close', 'High', 'Low']])
     fplt.show()


classWindow:
     def__init__(self, root, title, geometry, message):
         self.root = root
         self.root.title(title)
         self.root.geometry(geometry) # input, size x size
         Label(self.root, text=message).grid(row=0, column=0)
         self.root.mainloop()
         pass


root = Tk()

var = StringVar(value=myList)
listbox1 = Listbox(root, listvariable = var, width=10, height =5)
listbox1.grid(row=1, column=0)

button1 = Button(root, text='Draw Chart', command = drawChart)
button1.grid(row =5, column=0)

window1 = Window(root, 'My new Window', '300x300', 'Select Ticker')

Kind regards,
Jonas

------ Originalmeddelande ------
Från: "Ioanni5" <notifications@github.com>
Till: "highfestiva/finplot" <finplot@noreply.github.com>
Kopia: "Subscribed" <subscribed@noreply.github.com>
Skickat: 2020-09-10 22:23:33
Ämne: [highfestiva/finplot] Using finplo (#29)

**Comment by Ioanni5** [comment]
Good morning Jonas,

you are absolutely right ! I was missing the 
fplt.show() 
after creating the object. 

Thanks for your help
Ioanni5

**Comment by highfestiva** [comment]
I just added support for using Qt for the kind of thing you're experimenting with. See this [example](https://github.com/highfestiva/finplot/blob/master/finplot/example-embed.py#L10), if it's of interest to you.

**Comment by blazedforever** [comment]
hey thanks for this! would be cool to have the finplot frame packed into the tkinter window though

**Comment by highfestiva** [comment]
That seems hard, and is not going to happen unless you do it yourself. Would gratefully accept a pull request.

**Comment by white-seolpyo** [comment]
Try this package.

It provides a fast, simple, and movable slider.\
It can be used in connection with tkinter as well as other GUIs other than pyqt.

https://pypi.org/project/seolpyo-mplchart/

![seolpyo-mplchart](https://raw.githubusercontent.com/white-seolpyo/seolpyo-mplchart/refs/heads/main/images/with%20tkinter.gif)
