### ISSUE TITLE
Dynamic range on the y-axis (not a bug)

### ISSUE THREAD

**Issue by sunjar2020** [highfestiva/finplot#293]
When I tried to draw a line chart with 5 sets of data on one axis at the same time, and I found that when the values of two sets of data were two orders of magnitude larger than the rest, the chart did not fully display. For example, my df has 6 columns, the smallest data in the four columns is 7e-5, the largest is 3e-6, and the largest value in the last two columns is 1e-8, so the data in the first four columns cannot be seen.

I made a sample program and got similar results, where the RND4, RND5 data of df3 only appeared at the top of the window. Is there any way or parameter to solve this problem? Because I need to plot several sets of data with a large range of values on one axis at the same time.

Here's my code:

import pandas as pd
import numpy as np
import finplot as fplt

data_small = np.random.randint(100,120000,size=(1000,3))
data_big = np.random.randint(100000,1000000,size=(1000,2))
 
df1 = pd.DataFrame(data_small, columns=['RND1', 'RND2', 'RND3'])
df2 = pd.DataFrame(data_big, columns=['RND4', 'RND5'])
df3 = pd.concat([df1, df2], axis=1)

ax,ax1 = fplt.create_plot('test', rows=2)
fplt.plot(df3['RND1'], ax =ax, color='#0000ff', legend = 'RND1')
fplt.plot(df3['RND2'], ax =ax, color='#00ff00', legend = 'RND2')
fplt.plot(df3['RND3'], ax =ax, color='#00ffff', legend = 'RND3')
fplt.plot(df3['RND4'], ax =ax, color='#ff0000', legend = 'RND4')
fplt.plot(df3['RND5'], ax =ax, color='#ff0000', legend = 'RND5')

fplt.show()

btw, this is not Bug report, but I don't know how to remove "bug" tag from issue. Sorry.

**Comment by highfestiva** [comment]
It was a bug, but on the X-axis (as you hadn't supplied any X). Commit 2b675cc fixes that.

**Comment by sunjar2020** [comment]
Hi,highfestiva:

I tried what you said (modified __init__.py file) but it didn't work. If my data is date indexed, I get the following error:

'Traceback (most recent call last):
  File "M:\smp.py", line 9, in <module>
    fplt.plot(df['SMB'], ax =ax, color='#0000ff', legend = 'SMB')
  File "C:\Users\PPCC\AppData\Local\Programs\Python\Python37\lib\site-packages\finplot\__init__.py", line 1555, in plot
    datasrc = _create_datasrc(ax, x, y)
  File "C:\Users\PPCC\AppData\Local\Programs\Python\Python37\lib\site-packages\finplot\__init__.py", line 2080, in _create_datasrc
    datasrc = do_create(iargs)
  File "C:\Users\PPCC\AppData\Local\Programs\Python\Python37\lib\site-packages\finplot\__init__.py", line 2078, in do_create
    return PandasDataSource(pd.concat(args, axis=1))
  File "C:\Users\PPCC\AppData\Local\Programs\Python\Python37\lib\site-packages\finplot\__init__.py", line 224, in __init__
    if type(df.index) == pd.DatetimeIndex or df.index[-1]>1e7 or '.RangeIndex' not in str(type(df.index)):
TypeError: '>' not supported between instances of 'str' and 'float''

If I remove the sentence of setting the index, the plot can wrok, but there is the same situation as before, only the two red lines can be displayed.

I uploaded a sample of the data, could you please test it with it? Thank you so much.

New Code:
import pandas as pd
import numpy as np
import finplot as fplt

df = pd.read_csv("i:sample.csv")
df = df.set_index('Date')

ax,ax1 = fplt.create_plot('test', rows=2)
fplt.plot(df['SMB'], ax =ax, color='#0000ff', legend = 'SMB')
fplt.plot(df['SMS'], ax =ax, color='#0000FF',  style='--', legend = 'SMS')
fplt.plot(df['MEDB'], ax =ax, color='#00ff00', legend = 'MEDB')
fplt.plot(df['MEDS'], ax =ax, color='#00FF00',  style='--', legend = 'MEDS')
#fplt.plot(df['LARGEB'], ax =ax, color='#ff0000', legend = 'LARGEB')
#fplt.plot(df['LARGES'], ax =ax, color='#ff0000',  style='--', legend = 'LARGES')


fplt.show()

----------
sample file: CSV
https://xfl.jp/NUV3ui

**Comment by highfestiva** [comment]
You can't have text indices, best is to use datetime indexes. See examples on how to create those.

**Comment by sunjar2020** [comment]
> 

you mean this?
df['Date'] = pd.DatetimeIndex(df['Date'])

I've tried add this but it still didn't work.

**Comment by sunjar2020** [comment]
Hi, highfestiva:

I re-checked my code and data again, I think the problem should not be related to the index, there must be something else wrong. I have set the date index according to the method you said, but it still doesn't work, but I can display it normally with another many set of data.

In my first example of using random numbers, I changed the __init__.py file according to Commit 2b675cc, and the other three lines can be displayed normally, but if I adjust the value range of the random data, it cannot be displayed.

new random data simulate a set of my data(replaced them with first post code)

#data_small = np.random.randint(100,120000,size=(1000,3))
#data_big = np.random.randint(100000,1000000,size=(1000,2))
data_small = np.random.randint(3635100,39655700,size=(1000,3))
data_big = np.random.randint(8967821,129607608,size=(1000,2))

After I changed the two lines of code for the random number in the first example, even with the new __init__.py file, the plot was not complete. Hope you'll check again when you're not busy.

**Comment by highfestiva** [comment]
Try `pandas.to_datetime()`. Unfortunately I only have time to support bugs in finplot, not newbies looking for programming help. As I said, check the examples, they are a valuable source of how to start.

**Comment by sunjar2020** [comment]
I'm sorry to hear you say this, I know I'm a rookie but I've tried my best. In an earlier reply I have said that I have set the date column to be indexed, but the problem remains. And when I replace other data, it can be displayed without changing any part of the program. So I don't think it's an index issue. And my example using random numbers doesn't use the x-axis, which doesn't work as the data values change.

I know you're not obligated to help me, but I guess if it's really my problem, it might be a 1-2 minute thing for a developer like you to tell me what's wrong with the code.

This is the last time I ask this question here. Anyway, thanks for providing such a nice library.

------------ added code for set datetime index
df['Date'] = pd.DatetimeIndex(df['Date'])
#df['Date'] = pd.to_datetime(df['Date']) (also tested)
df = df.set_index('Date')
>>> df.index
DatetimeIndex(['2021-01-04', '2021-01-05', '2021-01-06', '2021-01-07',
               '2021-01-08', '2021-01-11', '2021-01-12', '2021-01-13',
               '2021-01-14', '2021-01-15',
               ...
               '2021-06-17', '2021-06-18', '2021-06-21', '2021-06-22',
               '2021-06-23', '2021-06-24', '2021-06-25', '2021-06-28',
               '2021-06-29', '2021-06-30'],
              dtype='datetime64[ns]', name='Date', length=118, freq=None)

**Comment by highfestiva** [comment]
I use
```python
df['Date'] = pd.to_datetime(df['Date'])
df = df.set_index('Date')
```
and no, it doesn't take a minute. First I need your complete data (or I can't run your sample), then I need to debug it, then find the cause. If you'd followed the instruction and posted both code+data in a zip file, it would have been a lot easier. Anyway, this is good for you, if you can't piece this together, then you're going to struggle with things that may make your analysis buggy, which is much worse (as you could lose money).

**Comment by sunjar2020** [comment]
Hi,highfestiva:

The zip package can be downloaded from here. I'd appreciate it if you would test it again.

download link:
https://www.filesend.jp/l/en-US/dclckv

**Comment by highfestiva** [comment]
Works for me. Don't know what you mean by modifying init.py, but what you should do is update your local code with `git pull`. GL!

**Comment by sunjar2020** [comment]
Finally got it done, after using the git pull method you mentioned, the method I said to modify the init.py is when I see the Commit 2b675cc you mentioned, I was manually modify the init.py and add the code which the part you added. It did work when I tried first random data example worked, so I thought that would work.

Thank you very much for your time and sorry for the inconvenience.

Best regards!
