### ISSUE TITLE
Issues plotting markers on top of plot

### ISSUE THREAD

**Issue by jsun-85** [highfestiva/finplot#294]
Hi, 

First of thanks for an amazing package, it is just what I have been looking for!

I have encountered a problem though in trying to replicate the functionality in issue 31 where you made an example of how to plot multiple markers on the same candle or 'buy' markers.

I have a problem with plotting it on the x-axis, the y-axis seem to work just fine. When plotting with the standalone as per the example the 3 markers get positioned at the start of the chart no matter what x coordinates I tried and they also get printed on each subsequent candle from the start of the chart.

See the example:

![2022-01-24_11h00_27](https://user-images.githubusercontent.com/98315664/150763273-69138ebe-b5d8-4abb-81e1-a2ca2a6ada5d.png)

My full code for this example is:

`import finplot as fplt`
`import requests`
`import pandas as pd`

`symbol = 'USDT-BTC'`
`url = 'https://bittrex.com/Api/v2.0/pub/market/GetTicks?marketName=%s&tickInterval=thirtyMin' % symbol`
`data = requests.get(url).json()`

`df = pd.DataFrame(data['result'])`
`df = df.rename(columns={'T':'Time', 'O':'Open', 'C':'Close', 'H':'High', 'L':'Low', 'V':'Volume'})`
`df = df.astype({'Time':'datetime64[ns]'})`

`ax = fplt.create_plot('Tesla rocks')`
`fplt.candlestick_ochl(df[['Time','Open','Close','High','Low']])`

`x0 = len(df)-100`
`x = [x0+500, x0+0.1, x0+0.3]`

`y0 = df.Close.iloc[-100]`
`y = [y0+10000, y0+11000, y0+12000]`

`ds = fplt._create_datasrc(ax, x, y)`
`ds.standalone = True`
`fplt.plot(ds, style='>', width=2)`

`fplt.show()`

Did I make a misstake somewhere?

Thanks in advance!

**Comment by jsun-85** [comment]
Thanks a lot for the quick reply!

Basically i have two dataframes, one with the price data and the other containing the buy and sell transactions. The buy and sells can be more than one for the the same candle and basically i try to accomplish what you showcased in [this thread](https://github.com/highfestiva/finplot/issues/31#issuecomment-695952455) where you have plotted 3 markers or "buys" on a candle. I can't get my markers to be printed on the correct candle or on the same candle for that matter, they all start stacking up from the left side even though I tried to follow the example in the link. 

My expectation for the example above would be that the two markers would be printed on the 100th candle from the end of the chart. The price level (y-axis) is accurate but the x-axis seems to be my issue.

Here is my actual chart and a description on what i try to achieve:

![image](https://user-images.githubusercontent.com/98315664/150939200-f609e6cf-faf4-4464-bfb4-3ff3d2912973.png)

When I tried to plot it at first it would fit the buy markers in between the candles. And when trying to make it standalone the result was as shown that the markers doesn't get plotted where I try to plot on the X-axis and just get stacked from the beginning, one per candle from the start.

Thanks again and I hope I was a bit clearer this time!

**Comment by highfestiva** [comment]
Use `df.Time` as X-coordinate instead of an some kind of index.

**Comment by jsun-85** [comment]
I think I did figure it out now, it works fine when I just plot it using fplt.plot() instead of the ds.standalone variant plotting with the df.Time as you proposed. The misstake I did earlier with that same method was to not normalize the the datetime of the dataframe containing the buy datapoints but after normalization they get printed correctly!

Thanks alot for the guidance and quick help!
