### ISSUE TITLE
Display column name when crosshair hover over a line

### ISSUE THREAD

**Issue by sunjar2020** [highfestiva/finplot#295]
In a line chart, is there a way to display column names when the cursor hovers over a line, just like an Excel's chart? For now finplot only shows the values of the X and Y axes.

I'm asking this question because when I'm plotting a line chart by using multiple sets of data on one axis at the same time, if I want find out few outliers datas(lines),  it's hardly to identiry line's column just depend on color.

Thank you.

![sample](https://i.ibb.co/q72Ypw0/blk.png)

**Comment by highfestiva** [comment]
Yes, the S&P500 example shows how to modify the X and Y labels on the crosshair.
