### ISSUE TITLE
run finplot in a second process

### ISSUE THREAD

**Issue by incafox** [highfestiva/finplot#3]
hi, i'm writting a program using kivy and finplot, my question is how to run finplot in a second process, liberating the main process to continue its work.???

**Comment by highfestiva** [comment]
Hi Lubeck,

You should utilize the eminent subprocess module, which is included in 
python. Good luck!

Kind regards,
Jonas

------ Originalmeddelande ------
Från: "Lubeck Abraham Huaman Ponce" <notifications@github.com>
Till: "highfestiva/finplot" <finplot@noreply.github.com>
Kopia: "Subscribed" <subscribed@noreply.github.com>
Skickat: 2019-08-16 05:37:54
Ämne: [highfestiva/finplot] run finplot in a second process (#3)

**Comment by incafox** [comment]
Thanks for answering!
