### ISSUE TITLE
finplot is so powerfu !

### ISSUE THREAD

**Issue by Gary-Hertel** [highfestiva/finplot#30]
I find finplot is such a powerful tool, i used it to plot realtime candlestick_ochl and indicators based on reat api.
Now i am trying to plot realtime asset, but i don't know how to update timestamp.
Here is my code:
`data = exchange.get_coin_account(underlying="btc-usdt")
    equity = float(data['equity'])
    timestamp = get_utc_time()

    time.append(timestamp)
    asset.append(equity)

    if not plots:
        global ax
        plots.append(fplt.plot(asset, ax=ax, color='#FFFFFF', legend="asset"))
    else:
        plots[0].update_data(asset)`
How can i update timestamp ?
![image](https://user-images.githubusercontent.com/67775512/93016017-9d67c080-f5f0-11ea-891e-0bae74fd957c.png)

**Comment by highfestiva** [comment]
Looks like you should do something like:
````python
df = pd.DataFrame({'time':time, 'asset':asset})
if not plots:
    global ax
    plots.append(fplt.plot(df, ax=ax, color='#FFFFFF', legend="asset"))
else:
    plots[0].update_data(df)
````

**Comment by Gary-Hertel** [comment]
![image](https://user-images.githubusercontent.com/67775512/93060108-428fa100-f6a4-11ea-9c85-7712e29568af.png)
Great ！
