### ISSUE TITLE
[Question] rendering scatter plots with line charts

### ISSUE THREAD

**Issue by pssolanki111** [highfestiva/finplot#300]
Hey @highfestiva 

Appreciate the amazing work done on this lib :)

I was looking into alternates of `seaborn` and `plotly` for scatter plots as I have used finplot a lot in the past for ochlv data (not to mention was amazed by performance). I'm thinking of integrating it for this dataset as well. This is how the charts look
![SPY_2022-01-12_13-06-18](https://user-images.githubusercontent.com/40393715/153709111-79f904bc-4aad-483e-9013-e8a4ee08f557.png)

The underlying data is just a `pd.DataFrame` having three columns. 

the current code to spawn the above chart looks like
```py
sns.scatterplot(data=df, x='timestamp', y='price', size='size', legend=True,
                        sizes=(1, 1200)).set(title=chart_title)
sns.lineplot(data=df, x='timestamp',
                     y='price', linewidth=0.1, color='red')
```
 where sns is seaborn

The primary reason i'm looking for an alternate is that i need to be able to update the data on the chart every few secs (like 20 sec for eg) and I remember finplot's `update_data` functionality.

Any pointers for me start with? I'm able to provide all sorts of sample data/existing code or example charts if needed.

Thanks :)

**Comment by highfestiva** [comment]
Have a look at [this](https://github.com/highfestiva/finplot/blob/master/finplot/examples/bubble-table.py) example.

**Comment by pssolanki111** [comment]
appreciate the response @highfestiva 

The output chart looks like this 
![Screenshot from 2022-02-14 19-56-16](https://user-images.githubusercontent.com/40393715/153882484-962618da-5b9b-43cb-b51e-22ee39258f82.png)
which looks good but isn't quite a scatter plot. 

Any other references? or should I stick to seaborn?

**Comment by highfestiva** [comment]
The example shows several scatter plots overlaid. Change the scale, and remove all but one of them. Use your imagination.
