### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by adamsmail54321** [highfestiva/finplot#301]
### Requirements (place an `x` in each of the `[ ]`)**
* [ X] I realize finplot is not a web lib. (Hint: it's native!)
* [X ] I've read the [snippets](https://github.com/highfestiva/finplot/wiki/Snippets) and not found what I'm looking for.
* [X ] I've searched for any related issues and avoided creating a duplicate issue.
* [ X] I've updated finplot (`pip install -U finplot`).
* [X ] I've supplied the required data to run my code below.

### Code to reproduce

```python
import finplot as fplt
import pandas as pd
```

### Expected behavior
A clear and concise description of what you expected to happen instead.

#### Reproducible in:

I really like finplot and have been using it for almost a year.. however I am not great with python, but I'm about average person knowledge with it...

    My question is related to the datetime index..

    I get my data from ibkr, it's basically the same as yfinance data, ohlcv.   My chart looks great however my datetime is messed up.. my data has the correct datetime in the index, however, when displayed using finplot, the entire chart is 4 hours ahead of time.  I have had this problem for a long time, but it would be nice if you could provide me with a code snipit that would fix this problem... I understand finplot is Not a web app, however the datetime I provide is automatically forwarded 4 hours...

I am using a standard df[['open, high, low, close, volume']] 

With the correct datetime index... 

Any help would be greatly appreciated

*OS*:
*finplot version*:
*pyqtgraph version*:
*pyqt version*:

**Comment by highfestiva** [comment]
Your index is timestamps in UTC (or at least they should be). That might not be what you want to visualize. See  https://github.com/highfestiva/finplot/issues/59#issuecomment-753641706 for details.
