### ISSUE TITLE
Can I get the ochl value of a candle from a candlechart?

### ISSUE THREAD

**Issue by song-71** [highfestiva/finplot#304]
### Requirements (place an `x` in each of the `[ ]`)**
* [ ] I realize finplot is not a web lib. (Hint: it's native!)
* [ ] I've read the [snippets](https://github.com/highfestiva/finplot/wiki/Snippets) and not found what I'm looking for.
* [ ] I've searched for any related issues and avoided creating a duplicate issue.
* [ ] I've updated finplot (`pip install -U finplot`).
* [ ] I've supplied the required data to run my code below.

### Code to reproduce

```python
import finplot as fplt
import pandas as pd
```

### My question
Thank you for providing a very flexible and advanced library. I'm a Python beginner.
I am trying to display the oclh value in the crosshair_text of the candlechart as shown below.
Data is being added to my candlechart every 5 minutes, so after the update, the first x value is changed, so I had to work to find the data that matches the x values.
The only way to find out is to find the time value that matches the x value in the candlechart dataframe, find the ochl value that fits the iloc, and display it.
However, this is time-consuming as it continues to calculate every time it changed a many times of x values.
Is there any way to get the ochl value in candlechart and display it?

### Example code that find the ochl value in the candlechart dataframe, but I want find it in the candlechart directly
def update_crosshair_text(self, x, y, xtext, ytext):
        Y_= xtext[:4]; m_= xtext[5:7]; d_= xtext[8:10]; H_= xtext[11:13]; M_= xtext[14:16]
        dt=datetime(int(Y_), int(m_), int(d_), int(H_), int(M_))
        dtInt=int(datetime.timestamp(dt))*1000
    
        for i in range(len(self.candlesticks.time)):
            if self.candlesticks['time'][i]==dtInt:
                O=self.candlesticks['open'][i]
                C=self.candlesticks['close'][i]
                H=self.candlesticks['high'][i]
                L=self.candlesticks['low'][i]
                break
        txt_ohlc=f'      O {O:,.2f}\n' \
                f'      C {C:,.2f}\n' \
                f'      H {H:,.2f}\n' \
                f'      L {L:,.2f}'
        ytext = f'{y:,.2f}\n' + txt_ohlc
        return xtext, ytext

#### Screenshots

*OS*: window 10
*finplot version*:
*pyqtgraph version*:
*pyqt version*:
![candlechart_crosshairtext](https://user-images.githubusercontent.com/100416516/155712260-f2b220b5-c72e-4cbe-8ec4-25af3ab6a2a6.jpg)

**Comment by highfestiva** [comment]
Have a look at `examples/snp500.py`, it does just that.
