### ISSUE TITLE
how to draw a clean candlestick photo and save it as a png file?

### ISSUE THREAD

**Issue by Nise-2-meet-U** [highfestiva/finplot#307]
e.g.
![1586243940000_1 000689_0 989951__1M_ETH](https://user-images.githubusercontent.com/75665054/157616997-f4c75e1f-f259-4631-a5c0-01ab82ba75fa.png)

**Comment by Nise-2-meet-U** [comment]
without label or whatsoever

**Comment by highfestiva** [comment]
You'd want to hide axes and crosshair. Something like `ax.set_visible(crosshair=False, xaxis=False, yaxis=False)`. Screenshot like `line.py` example.

**Comment by Nise-2-meet-U** [comment]
Thank you, do you know how to convert it to BytesIO?
