### ISSUE TITLE
Current Price Lable 

### ISSUE THREAD

**Issue by CRY-D** [highfestiva/finplot#310]
Hi,  is there is any way to put the price label from the last candle in right of axis ?  I tried and failed

what i want is something like this

![Annotate-a-local-image](https://user-images.githubusercontent.com/16564491/159923373-39f206e5-1a7d-479c-a59a-adddb6668a47.png)

**Comment by highfestiva** [comment]
No. This library is mostly intended for backtesting, so while it might be valuable for some analysis I'm not going to spend time on it. If you succeed, and send me a small, clean pull request, I'll gladly incorporate it in the lib.

**Comment by golucoder** [comment]
> No. This library is mostly intended for backtesting, so while it might be valuable for some analysis I'm not going to spend time on it. If you succeed, and send me a small, clean pull request, I'll gladly incorporate it in the lib.

You recommanding this library for backtesting. Does it mean you are not recommanding tot use this library for firing orders based on my already backtested strategies?

**Comment by highfestiva** [comment]
Correct.

**Comment by issacnumb** [comment]
when you create line,  you can use these code :   

`ax.price_line = pg.InfiniteLine(angle=0, movable=False, pen=fplt._makepen(fplt.candle_bull_body_color, style='.'), label=str(price_data['last_close']), labelOpts={"position": 0.98})`  
  
when you update ,  you can use these code :   
`ax.price_line.label.setFormat(str(price_data['last_close']))`

**Comment by issacnumb** [comment]
total code:  
when you create:  
`
    # price line
    ax.price_line = pg.InfiniteLine(angle=0, movable=False, pen=fplt._makepen(fplt.candle_bull_body_color, style='.'), label=str(price_data['last_close']), labelOpts={"position": 0.98})
    ax.price_line.setPos(price_data['last_close'])
    ax.price_line.pen.setColor(pg.mkColor(price_data['last_col']))
    ax.addItem(ax.price_line, ignoreBounds=True)
`  
when you update:  
`
    # place and color price line
    ax.price_line.setPos(price_data['last_close'])
    ax.price_line.pen.setColor(pg.mkColor(price_data['last_col']))
    ax.price_line.label.setFormat(str(price_data['last_close']))
`
