### ISSUE TITLE
Candles Offset By One In Chart

### ISSUE THREAD

**Issue by errissa** [highfestiva/finplot#311]
### Requirements (place an `x` in each of the `[ ]`)**
* [x] I realize finplot is not a web lib. (Hint: it's native!)
* [x] I've read the [snippets](https://github.com/highfestiva/finplot/wiki/Snippets) and not found what I'm looking for.
* [x] I've searched for any related issues and avoided creating a duplicate issue.
* [x] I've updated finplot (`pip install -U finplot`).
* [ ] I've supplied the required data to run my code below.

First, thank you for this library. I experimented with various options and found `finplot` to be perfect for my needs. It's been quite easy to use!

As I was implementing a callback to display info when a candle is clicked I noticed that my plotted candles seem to be offset by 1 unit. For example, in the screenshot below the candle beneath the crosshair shows a date/time of 2022-03-21 17:00 but the candle underneath the cursor is in the Pandas dataframe at time 2022-03-21 21:00. All of the candles in this screenshot or off by 4hours (one candle) from what the crosshair shows and what's in the dataframe.

Is there a way to change the datetime 'edge' which is used for the crosshair? It's inconvenient to have to add 4 hours to get the row from the dataframe that matches the visual.

![2022-03-24-132323_1200x600_scrot](https://user-images.githubusercontent.com/3722407/159976985-ed687c61-188b-45c7-a71b-5318587980d6.png)

**Comment by highfestiva** [comment]
If you're using DST, finplot contains a bug which will be fixed in the next release (so off by one hour). So I assume your timezone is +-3, 4, or 5 hours, and that probably accounts for the difference. To use UTC, see [this](https://github.com/highfestiva/finplot/wiki/Snippets#time-zone).

**Comment by errissa** [comment]
Thanks for the reply - I thought I had tried setting `finplot` to use UTC timezone as per your link but I must not have because it worked! Very much enjoying using `finplot`.
