### ISSUE TITLE
While running complicated.py getting warning as shown in main body

### ISSUE THREAD

**Issue by golucoder** [highfestiva/finplot#312]
I think developer can correct this issue in advance. Thanks for great tools.

DeprecationWarning: Accessing pyqtgraph.QtWidgets through QtGui is deprecated and will be removed sometime after May 2022. Use QtWidgets.QGridLayout instead.

**Comment by highfestiva** [comment]
Thanks for the headsup!

**Comment by golucoder** [comment]
> Thanks for the headsup!

Thanks to you. Your code helped me a lot.
