### ISSUE TITLE
Two charts in different tabbed windows, only the second chart gets refreshed

### ISSUE THREAD

**Issue by forna** [highfestiva/finplot#317]
Hi, 
This is the second issue I am facing, the working example is available here:
https://github.com/forna/Finplot_PySide_two_chart_windows/blob/master/main.py
It requires finplot 1.8.1 and pyside6 (that is almost the same as pyqt ).

I have two finplot charts in different tabs, each is instantiated separately 
When clicking any symbol on the left side: only the chart in the second tab gets refreshed and displays the candles.
The chart in the first tab cannot get refreshed.
I have tried many different workarounds but I had no luck so far.

**Comment by highfestiva** [comment]
Interesting. If I only instantiate the first one, it works. Haven't spent much time on multiple widget plots, will investigate further.

**Comment by highfestiva** [comment]
You forgot to tell finplot which axis to plot to (it always defaults to the last one if no argument is given). Fix by:
```python
cadlesticks = fplt.candlestick_ochl(df[df_cols_list], ax=self.fplt_widget)
```
(Also fix spelling, 'n' missing in 'candle'. :)

**Comment by forna** [comment]
Thank you so much, that did the trick!
