### ISSUE TITLE
[BUG] Mouse-hover date is 1 day off (into the past)

### ISSUE THREAD

**Issue by ShivaSmith** [highfestiva/finplot#319]
### Requirements (place an `x` in each of the `[ ]`)**
* [x] I realize finplot is not a web lib. (Hint: it's native!)
* [x] I've read the [snippets](https://github.com/highfestiva/finplot/wiki/Snippets) and not found what I'm looking for.
* [x] I've searched for any related issues and avoided creating a duplicate issue.
* [x] I've updated finplot (`pip install -U finplot`).
* [x] I've supplied the required data to run my code below.

### Code to reproduce (from the repo. ReadMe front-page tutorial, but running with 'SPY')

```python
import finplot as fplt
import yfinance

df = yfinance.download('SPY')
fplt.candlestick_ochl(df[['Open', 'Close', 'High', 'Low']])
fplt.show()
```

### Describe the bug
When I run the snp500.py example (in finplot/examples), it shows the all-time-high candle date (when you mouse-hover over it) as 2022-1-3.  That is 1 day off.  It should read "2022-1-4".

*OS*:  Windows 11
*finplot version*: 1.8.1

p.s.

Thank you SO MUCH for creating Finplot!!  It's awesome and I love it!!  :)

**Comment by ShivaSmith** [comment]
Note -- when I print out the yfinance dataframe, it correctly shows the last row's day as 4/8/22 (Friday where I am).

But the mouse-hover-date (in the plot) for the last day is shown as 4/7/22 -- so it's like all the data is somehow getting shifted by 1 day to the "right" and the current day "drops off".

**Comment by highfestiva** [comment]
Default display timezone is local. See [here](https://github.com/highfestiva/finplot/wiki/Snippets#time-zone) for more info.

**Comment by ShivaSmith** [comment]
Hi... thanks for the quick reply, and the reference 😄.  I think I had come across it as I was searching through everything, but I still couldn't solve my issue.

I had found this line in `__init__.py`:
```Python
display_timezone = datetime.now(timezone.utc).astimezone().tzinfo  # default to local
```
So I guess I was confused as to why the timing was still a day off... If it really was local, then I would think the day shown in the mouse crosshair would be accurate.

But something is not working for me... the ATH candle for SPY still reads as 1/03/22, for me.  I'm in the USA, Eastern Time.

I verified that the time zone on my Windows 11 computer is set to "(UTC-05:00) Eastern Time"

I haven't modified `__init__.py` at all... I'll look into it more.  :)

**Comment by ShivaSmith** [comment]
I see at least the beginning source of my problem.  I set a breakpoint in tickValues(), here:
```python
tz = display_timezone if to_midnight else None # for shorter timeframes, timezone seems buggy
```

The time zone is correct (Eastern), but looking deeper I see that for `t1` above, at this line:
```python
t0,t1,_,_,_ = datasrc.hilo(minVal, maxVal)
```
t1's value is indeed showing as:  `2022-04-08 000:00:00` -- 1 day off (early).

So that's the issue... now to figure out why it is showing that way.

**Comment by ShivaSmith** [comment]
Ok, stepping into `hilo(self, x0, x1)`, at the end of that call, the 5-tuple returned is:
`(728265600000000000, 1649376000000000000, 479.9800109863281, 42.8125, 7353)`

So it must be that the original nanoseconds for t0 and t1 (728265600000000000, 1649376000000000000), the 1st 2 elements from the above tuple, when used in `tickValues()`, to calculate the datetime, at this line:
```python
t0,t1 = pd.to_datetime(t0), pd.to_datetime(t1)
```
must be off.

So I can check and see how those nanoseconds came to be off... was it in the original calculation, or was it when being read in from the cache, or what... will see.

**Comment by highfestiva** [comment]
I think there's a fix for your problem in the next release. Are you in DST, and the timestamps you're observing are without or vice versa? If so, fix present in `master` and upcoming in next release.

**Comment by ShivaSmith** [comment]
Aha... ok cool... yeah I was working on tracking this down and suspected that this might be related to DST, because *yes* I am in DST 😉 .

I was just starting to look into `_x2local_t()` because it is called by `update()`  in `FinCrossHair`.

I saw that DST was at least partially addressed in the 1.8.1 version of Finplot, but yeah, I can try the bleeding edge code currently in `master` and see what happens.

Thanks for the tip!  😄 

p.s.

Yes -- checking the cross-hair timestamp of the high candle for ETH in `complicated.py`, for me it is 1 hour off (it shows as 8:00), compared to what TradingView shows me (7:00), so yes, it sounds very likely due to DST -- I'll try `master` --  will report back and close this if `master` fixes it.

p.p.s.

Let me please say again how **AWESOME** Finplot is!!!  There is nothing else like it out there, and it was *exactly* what I was looking for!  I *definitely* owe you some coffee, at a minimum.  👍 

I love PyQtGraph and Qt in general... what an exremely cool package Finplot is :)...  Seriously I'm not exaggerating -- it rocks my world lol... I've been searching for something like this in Python for years -- so happy I found it!! 😸

**Comment by highfestiva** [comment]
Thanks for the praise, means a lot for a maintainer who gets a lot of flak for developing stuff. The tip of the iceberg is stuff I needed myself, the remaining stuff is for the community. Glad you like it! :)

**Comment by ShivaSmith** [comment]
re: your last comment -- Oh yeah!!  Finplot is totally awesome!  I am *very* thankful for it :).

Btw, I did pull the latest code from `master` just now (6pm Eastern time -- 4/9/22) and the likely-DST-related timestamp bug still remains -- i.e. for me, candle times (for the mouse-hover crosshair) are off by 1 -- same issue if hours, or days, or whatever the time unit -- the hover time is just "off by 1 unit".

I will try to delve into that very soon and see if I can figure it out.  :)

Btw, see this new related bug:
[[BUG] requirement in setup.py for dateutil should read 'python-dateutil](https://github.com/highfestiva/finplot/issues/320)

Just needs a minor update in setup.py...  The package name itself is 'python-dateutil', so that's what has to be in setup.py, even tho' you  import it as 'dateutil'.

**Comment by ShivaSmith** [comment]
Ok... here's what's going on.  If you call:
```python
df = yfinance.download('SPY')
```
It will return a dataframe with 7353 rows.  Ok... The *last row's* datetime index, if you print it out with:

```python
print (df.index[-1])
```
will give you a datetime of:
2022-04-08 00:00:00

That is 4/8/22 at UTC *midnight*... and then yes, if it's converted to Eastern Time, it will think it is 4/7/22 since you subtract 4 or 5 hours, depending on DST.

So yeah maybe the solution is just to use UTC... but intra-day times should still be for the correct day and correct *local time zone*.  So, for example, TradingView knows that the last day of the SPY for this week occurred is on 4/8/22, and it has all the intraday times correct also.  I need to try some Finplot intraday charts and see if the problem persists or not.

I'm not sure how to handle this exactly... have to think about it more, I guess.

**Comment by highfestiva** [comment]
The way you're describing it sounds almost like a rounding error? So you'd want something that is closer to April 8 than to April 7 to actually show 8 instead of truncating to 7. That is a different bug than the DST problems I had earlier (and which should now be fixed).

**Comment by highfestiva** [comment]
When running this:
```python
#!/usr/bin/env python3

import dateutil
import finplot as fplt
import yfinance

df = yfinance.download('SPY')
fplt.display_timezone = dateutil.tz.gettz('America/New_York')
fplt.candlestick_ochl(df[['Open', 'Close', 'High', 'Low']])
fplt.show()
```
Friday's candle gets the date `2022-04-08`. Since it doesn't have any timezone data, we interpret it as midnight UTC. We get this representation in New York time: `2022-04-07 20:00:00-04:00`. Afaict the actual closing time of SPY was `2022-04-08 16:15:00-04:00`. To me it looks like yfinance is misrepresenting the timestamp, as there is no timezone information?

It could also be that *any* date without timezone data should always be presented without timezone adjustments. Do you know if there are (common) scenarios where this might be unwanted? (I only trade in crypto which is open to trade 24/7, so haven't thought about this.)

**Comment by ShivaSmith** [comment]
Thanks for your thoughts on this.  Yeah I think we have this sorted now, so I'll close it.  I should have looked more closely at how yfinance handles (or *doesn't* handle time zones).  yfinance states "Note: yahoo finance datetimes are received as UTC."

Here's what worked for me to get Eastern time -- for daily bars, this works:
```python
df.index = df.index.tz_convert('America/New_York')
```
For intraday (only tested 1 hour bars), *no* adjustment at all is needed -- dates and times appear to be correct automagically for intraday... :)
