### ISSUE TITLE
[BUG] requirement in setup.py for dateutil should read 'python-dateutil'

### ISSUE THREAD

**Issue by ShivaSmith** [highfestiva/finplot#320]
Note -- this requirement in setup.py should be 'python-dateutil', not 'dateutil'.

If you use only 'dateutil' pip will complain and you will see:

"ERROR: Could not find a version that satisfies the requirement dateutil (from finplot) (from versions: none)
ERROR: No matching distribution found for dateutil"

When I changed to "python-dateutil' in setup.py, everything installed fine 😄 .

**Comment by highfestiva** [comment]
Ah, thanks a bunch! Fix in https://github.com/highfestiva/finplot/commit/b82f88324dadddfb727b0e6a40a9ab71bac4f5e2.

**Comment by ShivaSmith** [comment]
Thank *you* Sir for sharing Finplot... glad to help 😄.  Pulled and tested fix.  It works. 👍
