### ISSUE TITLE
Modified dockable.py won't load Volume until mouse-zooming out

### ISSUE THREAD

**Issue by ShivaSmith** [highfestiva/finplot#322]
Hi,

I modified Finplot's example, dockable.py, to just use a QSplitter widget directly (instead of via the stylesheet).  I also initially collapsed the 2 indicator rows, as desired.

The issue I have is that Volume doesn't display after initially launching the program.  After I zoom out manually with the mouse, to the level of years, then Volume "pops in" and remains visible from that time onward -- for both zooming in and out.  So it's like for some reason Volume won't load initially.  This is puzzling because I haven't changed that part of the code from dockable.py at all -- the part that loads the volume data is identical, as far as I can tell.

Here is the code -- please try running:

```python
#!/usr/bin/env python3

import finplot as fplt
from functools import lru_cache
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QGridLayout, QMainWindow, QComboBox, QLabel, QSplitter, QWidget
from threading import Thread
import yfinance as yf

app = QApplication([])
win = QMainWindow()
main_widget = QWidget()
layout = QGridLayout()
main_widget.setLayout(layout)
win.setCentralWidget(main_widget)
win.resize(1000, 800)
win.setWindowTitle("QSplitter Example -- 2 Indicators")

splitter = QSplitter(Qt.Vertical)

# Create example charts
combo = QComboBox()
combo.setEditable(True)
[combo.addItem(i) for i in "SPY AMRK FB GFN REVG TSLA TWTR WMT CT=F GC=F ^FTSE ^N225 EURUSD=X ETH-USD".split()]

layout.addWidget(combo, 0, 0, 1, 1)
info = QLabel()
layout.addWidget(info, 0, 1, 1, 1)

ax0, ax1, ax2 = fplt.create_plot_widget(master=win, rows=3, init_zoom_periods=100)

splitter.addWidget(ax0.ax_widget)
splitter.addWidget(ax1.ax_widget)
splitter.addWidget(ax2.ax_widget)

splitter.setStretchFactor(0, 10)
splitter.setStretchFactor(1, 1)
splitter.setStretchFactor(2, 1)

layout.addWidget(splitter, 1, 0, 1, 2)

# Link x-axis
ax1.setXLink(ax0)
ax2.setXLink(ax0)
win.axs = [ax0]


@lru_cache(maxsize=15)
def download(symbol):
    return yf.download(symbol, "2019-01-01")


@lru_cache(maxsize=100)
def get_name(symbol):
    return yf.Ticker(symbol).info["shortName"]


def update(txt):
    df = download(txt)
    if len(df) < 20:  # symbol does not exist
        return
    info.setText("Loading symbol name...")
    price = df["Open Close High Low".split()]
    ma20 = df.Close.rolling(20).mean()
    ma50 = df.Close.rolling(50).mean()
    volume = df["Open Close Volume".split()]
    ax0.reset()  # remove previous plots
    ax1.reset()  # remove previous plots
    ax2.reset()  # remove previous plots
    fplt.candlestick_ochl(price, ax=ax0)
    fplt.plot(ma20, legend="MA-20", ax=ax1)
    fplt.plot(ma50, legend="MA-50", ax=ax1)
    fplt.volume_ocv(volume, ax=ax2)
    fplt.refresh()  # refresh autoscaling when all plots complete
    Thread(target=lambda: info.setText(get_name(txt))).start()  # slow, so use thread


combo.currentTextChanged.connect(update)
update(combo.currentText())

fplt.show(qt_exec=False)  # prepares plots when they're all setup
win.show()
app.exec_()

```
I'm running on Windows 11, Python 3.9, with the April 10th commit from Finplot's `master`. 

I also tried to call fplt.create_plot_widget() at about the same point in the code as in `dockable.py`.  I generally tried to keep the ordering of most calls about the same as in `dockable.py`.  But that's about the only thing I can think of -- that somehow changing execution order among the Widget or Plot calls somehow is not letting Volume update properly... or it only somehow gets "reset" after zooming out far enough...  just a guess.

Thanks for any thoughts about this :).

**Comment by highfestiva** [comment]
There was a bug in the code. Replace `win.axs = [ax0]` with `win.axs = [ax0,ax1,ax2]`. GL!

**Comment by ShivaSmith** [comment]
Thanks that fixed it!  :)
