### ISSUE TITLE
Significant digits incorrect for non-power of 10 tick sizes (eg 0.25)

### ISSUE THREAD

**Issue by yamen** [highfestiva/finplot#33]
I have a data series where the 'tick' size is `0.25`. This is properly captured by `ax.significant_eps`, but the value of `ax.significant_decimals` is `1`. The simplest possible test case:

```
>>> def difftodecimals(smallest_diff):
...     s = '%.0e' % smallest_diff
...     exp = -int(s.partition('e')[2])
...     decimals = max(1, min(10, exp))
...     return decimals
... 
>>> difftodecimals(0.25)
1
>>> difftodecimals(0.025)
2
```

It seems that this function only cares about the first significant value when calculating total significant digits. I did not want to fix as I'm assuming there are other use cases outside of mine where the current function is behaving correctly.

**Comment by highfestiva** [comment]
You were right, this was worse than I thought, but at least got something going in https://github.com/highfestiva/finplot/commit/674ea4bc39c162e8eae8c8180239c529e82a861f. Note that you can always do `ax.significant_decimals = 2` and `ax.significant_eps = 0.25` if you dislike what finplots gives you.

**Comment by yamen** [comment]
I'll give it a shot - didn't want to toucn `ax.*` directly as these values seem to be updated / refreshed on new data? The detection of `significant_eps` was very clever btw, well done.

**Comment by sparkstartconsulting** [comment]
will setting ax.significant_decimals and ax.significant_eps work with something like the Yen which is quoted out to 7 significant digits? (though a lot of charting software multiplies by 100 and truncates digits for display)

**Comment by highfestiva** [comment]
USDJPY=X or which symbol?

**Comment by sparkstartconsulting** [comment]
Chicago Mercantile Exchange (CME)  Globex futures--for instance 6JZ0 (December 2020  Yen futures).  https://www.cmegroup.com/trading/fx/g10/japanese-yen.html

**Comment by highfestiva** [comment]
@sparkstartconsulting absolutely, for USDJPY=X (but defaults to three decimals).

**Comment by highfestiva** [comment]
You can always test in example-embed.py, added

````python
plots[3].update_data(volume)
ax.significant_decimals = 6
ax.significant_eps = 1e-6
...
````

and got:

![image](https://user-images.githubusercontent.com/160303/93652806-a1dc1100-fa16-11ea-9fef-c7c23490da63.png)

**Comment by sparkstartconsulting** [comment]
Awesome--thanks.  Looks like it will work very well

**Comment by highfestiva** [comment]
Is this a close?
