### ISSUE TITLE
Time in plot differs from time index in dataframe - possibly due to using .astimezone()

### ISSUE THREAD

**Issue by hollowheights** [highfestiva/finplot#335]
I am plotting from a dataframe with the time as index. The dataframe looks like this:

https://ibb.co/nbDGjS6

The time in the plot is ahead of the dataframe time by 7 hours, and I can't see why this happens.

Here is the code:

`

df = df.set_index('time') #Looks like Finplot requires this step

    #Call finplot for price data
    fplt.candlestick_ochl(df[['open', 'close', 'high', 'low']])

    #Call finplot for volume data
    #fplt.volume_ocv(df['volume'])

    #fplt.show()

    def save():
        fplt.winw = 1000
        fplt.winh = 500
        fplt.screenshot(open('%s-%s.png' %(stock,date.date()), 'wb'))
        fplt.close() #needs to be inside the save function

    fplt.timer_callback(save, 1, single_shot=True, ) # wait some until we're rendered

    fplt.show()
stockslist = [['2022-03-01', 'AAPL']]

`

**Comment by highfestiva** [comment]
Have you looked at [the snippets](https://github.com/highfestiva/finplot/wiki/Snippets#time-zone)?

**Comment by hollowheights** [comment]
Thanks for the tip! 
I had been looking for a documentation but didn't find it and read through the examples instead.
But the snippets look very useful indeed.
