### ISSUE TITLE
average line on volume bar

### ISSUE THREAD

**Issue by Diman1974** [highfestiva/finplot#338]
Hi , 
how can I draw average volume line on volume bar 
![image](https://user-images.githubusercontent.com/76178339/171327462-595a444f-ec13-4c36-b24d-e89c1fb7d8ff.png)

thanks.

**Comment by yamsu** [comment]
The [SNP500 Example](https://github.com/highfestiva/finplot/blob/master/finplot/examples/snp500.py) also does the same thing.

**Comment by dimitryn** [comment]
@yamsu thanks

**Comment by donmeganotz** [comment]
Omg I didn’t know I was subscribed, but since I am, what platform are you using or you have found popular in this community?
