### ISSUE TITLE
python3.9 fail to import [BUG]

### ISSUE THREAD

**Issue by jonatanzafar59** [highfestiva/finplot#342]
failed to import with the following error
'import finplot as fplt'

`Python 3.9.13 (main, May 24 2022, 21:28:31)
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 'NoneType' object has no attribute 'lower'
  File "<stdin>", line 1
    'NoneType' object has no attribute 'lower'
               ^
SyntaxError: invalid syntax
>>> 'NoneType' object has no attribute 'lower'
  File "<stdin>", line 1
    'NoneType' object has no attribute 'lower'
               ^
SyntaxError: invalid syntax
>>> import finplot as fplt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/finplot/__init__.py", line 2798, in <module>
    if any(sanctioned in code.lower() for sanctioned in '_ru _by ru_ be_'.split()) or \
  File "/usr/local/lib/python3.9/site-packages/finplot/__init__.py", line 2798, in <genexpr>
    if any(sanctioned in code.lower() for sanctioned in '_ru _by ru_ be_'.split()) or \
AttributeError: 'NoneType' object has no attribute 'lower'`

**Comment by highfestiva** [comment]
Fixed in https://github.com/highfestiva/finplot/commit/9d8c471c9c48a22f8f545b00baeeb85b54d64e19.
