### ISSUE TITLE
Howto plot Buy/Sell Orders

### ISSUE THREAD

**Issue by yamsu** [highfestiva/finplot#345]
I'm unable to figure out a way to plot buy/sell orders on a candlestick chart, such as shown in the image below: (arrows indicate trades, any marker would do)

![image](https://user-images.githubusercontent.com/1211897/173569822-7d6b353d-2377-485e-9dc6-bfbfee5c8a97.png)

The candlestick data is in a Pandas Dataframe and the buy/sell trade data is in a *separate* Pandas Dataframe. 

OHCLV data ("1M")
```
                                 O        H        L        C      V
T
2022-05-20 10:00:00+10:00  111.942  112.142  111.926  112.050  286.0
2022-05-20 10:01:00+10:00  112.044  112.080  111.844  112.064  150.0
```

Buy/Sell Trade (Col pl, +ve for buy, -ve sell)
```
                                        id        pl      rr    price
T
2022-05-20 15:03:37.543359762+10:00  9721   11.8954   11.90  111.540
2022-05-20 15:50:17.568209778+10:00  9722   27.2856   27.29  112.034
```
Hope someone can help!

**Comment by highfestiva** [comment]
First you want to align your `T`'s, possibly with something like [pd.merge_asof()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.merge_asof.html), possibly with a tolerance=pd.Timedelta('30s') or so. Then it's simply a matter of scatter plotting your buys and sells on top of the candles, something like [this](https://github.com/highfestiva/finplot/wiki/Examples#featured-example) example.

**Comment by yamsu** [comment]
@highfestiva Thanks, the T alignment was the issue.

Just as a side note, which may be helpful to others. The following markers are supported and can be provided through the 'style' argument. Further size of the marker can be provided with the 'width' arg.
```
fplt.plot(data, style='t1', width=2.0, color='#4a5'
```
## Marker options 
extracted from ScatterPlotItem.py
```
name_list = ['o', 's', 't', 't1', 't2', 't3', 'd', '+', 'x', 'p', 'h', 'star',
             'arrow_up', 'arrow_right', 'arrow_down', 'arrow_left', 'crosshair']
# o : circle
# s : square
# t : triangle_down
# t1: triangle_up
# t2: triangle_right
# t3: triangle_left
# d: diamond
# +: +
# x: x
# p: pentagon 
# h: hexagon
# star: star
# arrow_up/down/left/right : arrow but did not render!
# crosshair: octagon
```

**Comment by highfestiva** [comment]
Yep, and finplot adds some shortcuts for `style`, such as `'^', 'v', '>', '<'` and probably a few more I forgot.
