### ISSUE TITLE
Undocumented code behaviour

### ISSUE THREAD

**Issue by Alkalit** [highfestiva/finplot#346]
https://github.com/highfestiva/finplot/blob/9d8c471c9c48a22f8f545b00baeeb85b54d64e19/finplot/__init__.py#L2796-L2803

Since you are the owner of this project, its content is absolutely up you. But it contains very specific behavior which should be noted in the documentation - that you discriminate people on their ~~race and skin color~~ spoken language.

**Comment by highfestiva** [comment]
It's true that my sanctions cast a wide net. A bit contrarian to global politics, you might say.
