### ISSUE TITLE
renko plotting problem

### ISSUE THREAD

**Issue by sunjar2020** [highfestiva/finplot#347]
I recently made some renko plots with finplot, it's very nice and very useful for analyzing trends. Thanks for providing such a nice library. 

But I found a problem, according to the the history renko datas, I calculated the threshold is about 4% which is the price change of a brick or called the ‘box size’. But the last few rows in my data (from June 9th), the price movement has exceeded the threshold, but the renko chart does not place a new brick. I don't understand why this is. I have uploaded the package file of the program and data here:

https://tempsend.com/fkprz
or https://xfl.jp/phpioE

my code:

```
import finplot as fplt
import pandas as pd

df = pd.read_csv('sse.csv')
df.columns = ('time','open','high','low','close','Volume')
df['time'] = pd.to_datetime(df.time)
df.set_index('time', inplace = True)

w = fplt.foreground = '#000'
b = fplt.background = fplt.odd_plot_background = '#fff'
fplt.candle_bull_color = fplt.volume_bull_color = fplt.candle_bull_body_color = fplt.volume_bull_body_color = 'ff0330'
fplt.candle_bear_color = fplt.volume_bear_color = '#9AD0EC'
fplt.cross_hair_color = w+'a'

# plot renko + renko-transformed volume
ax,axv = fplt.create_plot('Renko chart', rows=2, maximize=False)
plot = fplt.renko(df[['close','Volume']], ax=ax) # let renko transform volume by passing it in as an extra column
df_renko = plot.datasrc.df # names of new renko columns are time, open, close, high, low and whatever extras you pass in
fplt.volume_ocv(df_renko[['time','open','close','Volume']], ax=axv)

fplt.show()
```

I hope you can take a look when you are not busy. thank you very much.

**Comment by highfestiva** [comment]
Afaict the Renko algorithm uses hysteresis to determine weather or not to add another brick. If the brick height is 4%, it would mean that only an 8% move up or down should used to create another brick. See implementation [here](https://github.com/highfestiva/finplot/blob/master/finplot/__init__.py#L2221) + a few lines down. It might be that I misunderstood how the "renko noise elimination" should work. If so, push a pull request and I'll have a look.

**Comment by sunjar2020** [comment]
Thanks for your reply, I'm not quite sure what the 'afaict' in 'afaict renko' means, maybe it's the name of some programmer who developed this renko algorithm? My knowledge of renko mainly comes from the following websites:

https://en.wikipedia.org/wiki/Renko_chart
https://www.investopedia.com/terms/r/renkochart.asp
https://school.stockcharts.com/doku.php?id=chart_analysis:renko
https://www.tradingview.com/support/solutions/43000502284-renko-charts/

Unlike the point figure chart, I lack an authoritative book on renko charts, all my knowledge of renko comes from the above sites. in my understanding a new brick will be drawn as soon as the price exceeds the brick size. I'll try to change the parts of the code you pointed out, but I'm new to github and I can't push a pull request yet, so I can only give you a little opinion here. I am sorry.

Thanks for your work again.

**Comment by highfestiva** [comment]
Look up "hysteresis," and "afaict" while you're at it! :) I think it's correct.

**Comment by sunjar2020** [comment]
> Look up "hysteresis," and "afaict" while you're at it! :) I think it's correct.

II still don't get it, but that's okay. thank you. :)
