### ISSUE TITLE
finplot install causing numpy conflicts

### ISSUE THREAD

**Issue by fmulv** [highfestiva/finplot#350]
"pip install finplot" is creating dependency conflicts in new install (May 2022 anaconda -> python 3.9. this is the output from the install command:

Collecting finplot
  Using cached finplot-1.8.2-py3-none-any.whl (32 kB)
Requirement already satisfied: python-dateutil in ./anaconda3/lib/python3.9/site-packages (from finplot) (2.8.2)
Collecting PyQt5
  Using cached PyQt5-5.15.7-cp37-abi3-manylinux1_x86_64.whl (8.4 MB)
Requirement already satisfied: pandas in ./anaconda3/lib/python3.9/site-packages (from finplot) (1.4.2)
Collecting pyqtgraph>=0.11.1
  Using cached pyqtgraph-0.12.4-py3-none-any.whl (995 kB)
Collecting numpy>=1.22.3
  Using cached numpy-1.23.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
Requirement already satisfied: pytz>=2020.1 in ./anaconda3/lib/python3.9/site-packages (from pandas->finplot) (2021.3)
Requirement already satisfied: six>=1.5 in ./anaconda3/lib/python3.9/site-packages (from python-dateutil->finplot) (1.16.0)
Collecting PyQt5-sip<13,>=12.11
  Using cached PyQt5_sip-12.11.0-cp39-cp39-manylinux1_x86_64.whl (357 kB)
Collecting PyQt5-Qt5>=5.15.0
  Using cached PyQt5_Qt5-5.15.2-py3-none-manylinux2014_x86_64.whl (59.9 MB)
Installing collected packages: PyQt5-sip, PyQt5-Qt5, numpy, pyqtgraph, PyQt5, finplot
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.5
    Uninstalling numpy-1.21.5:
      Successfully uninstalled numpy-1.21.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 5.1.5 requires pyqtwebengine<5.13, which is not installed.
daal4py 2021.5.0 requires daal==2021.4.0, which is not installed.
spyder 5.1.5 requires pyqt5<5.13, but you have pyqt5 5.15.7 which is incompatible.
scipy 1.7.3 requires numpy<1.23.0,>=1.16.5, but you have numpy 1.23.1 which is incompatible.
numba 0.55.1 requires numpy<1.22,>=1.18, but you have numpy 1.23.1 which is incompatible.
Successfully installed PyQt5-5.15.7 PyQt5-Qt5-5.15.2 PyQt5-sip-12.11.0 finplot-1.8.2 numpy-1.23.1 pyqtgraph-0.12.4

it seems like some older numpy dependencies are throwing errors in scripts after the finplot install uninstalled an older version of numpy. i also get this common warning in spyder.

Output from spyder call 'get_namespace_view':
/home/xxxx/anaconda3/lib/python3.9/site-packages/spyder_kernels/utils/nsview.py:427: UserWarning: legacy printing option can currently only be '1.13', '1.21', or `False`
  np.set_printoptions(**np_printoptions)

**Comment by highfestiva** [comment]
finplot has whatever dependencies it has, as do other libraries. There's not much to do about that. Instead you use [venv](https://docs.python.org/3/library/venv.html) to separate your different scripts.

**Comment by localcreator** [comment]
> finplot has whatever dependencies it has, as do other libraries. There's not much to do about that. Instead you use [venv](https://docs.python.org/3/library/venv.html) to separate your different scripts.

But version 1.8.0 works fine in jupyter. It's strange that the newer version has worse functionality..
