### ISSUE TITLE
RuntimeWarning: invalid value encountered in divide   volrs = volr / np.nansum(volr)

### ISSUE THREAD

**Issue by yuhuan1981** [highfestiva/finplot#353]
When I tried to do volume calucaltion , it appears no drawing .but RuntimeWarning: invalid value encountered in divide
  volrs = volr / np.nansum(volr)

Data flow like "[Timestamp('2022-07-01 00:00:00'), [(5.546, 77892497.0), (5.694, 55218520.0), (5.743, 103531278.0), (5.841, 108944417.0), (5.94, 174051868.0), (6.087, 67919524.0), (6.136, 243345862.0), (6.284, 89672720.0), (6.333, 144685786.0), (6.382, 96032985.0)]]]"

Seems no error

**Comment by highfestiva** [comment]
See `examples/volume-profile.py` for a working version. Your data format has to be exactly the same as in the example.

**Comment by yuhuan1981** [comment]
Hi,Thanks for your reply . 
Here is example data (part).
[Timestamp('2020-08-17 00:00:00'), [(11793.274, 12989.363000000001), (11828.034, 18602.367), (11862.795, 38322.151), (11897.555, 15950.203), (11932.315, 18930.28), (11967.076, 108466.56599999999), (12001.836, 19885.622), (12036.596, 78702.736), (12140.877, 52157.835999999996), (12210.398, 22142.943), (12245.158, 54831.562), (12279.919, 20809.567), (12314.679, 58146.87500000001), (12349.439, 63961.704999999994), (12384.2, 38885.224)]]]
looks like same format

**Comment by yuhuan1981** [comment]
#!/usr/bin/env python3

from collections import defaultdict
import dateutil.parser
import finplot as fplt
import pandas as pd
import pytz
import requests
import numpy as np



def download_price_history(ticker):
    # ===import data
    df = pd.read_csv('X:/sdb1/PY/01 Data/CN/Day2/'+ticker+'.csv', encoding='gbk', parse_dates=['date'])
    df = df.sort_values(by='date', ascending=True).reset_index(drop=True)  
    df.reset_index(drop=True, inplace=True)
    df = df[['date', 'close','open','high','low','volume']]  
    return df.astype({'date':'datetime64[ms]', 'open':float, 'high':float, 'low':float, 'close':float, 'volume':float})
    






def calc_volume_profile(df, period, bins):
    '''Calculate a poor man's volume distribution/profile by "pinpointing" each kline volume to a certain
       price and placing them, into N buckets. (IRL volume would be something like "trade-bins" per candle.)
       The output format is a matrix, where each [period] time is a row index, and even columns contain
       start (low) price and odd columns contain volume (for that price and time interval). See
       finplot.horiz_time_volume() for more info.'''
    data = []
    df['hlc3'] = (df.high + df.low + df.close) / 3 # assume this is volume center per each 1m candle
    _,all_bins = pd.cut(df.hlc3, bins, right=False, retbins=True)
    for _,g in df.groupby(pd.Grouper(key='date', freq=period)):
        print (g)
        t = g.date.iloc[0]
        volbins = pd.cut(g.hlc3, all_bins, right=False)
        price2vol = defaultdict(float)
        for iv,vol in zip(volbins, g.volume):
            price2vol[iv.left] += vol
        data.append([t, sorted(price2vol.items())])
        np.seterr(invalid='ignore')
    return data




# download and calculate indicators
df = download_price_history('sh.600740')
print (df)
time_volume_profile = calc_volume_profile(df, period='2W',bins=100) # try fewer/more horizontal bars (graphical resolution only)
print (time_volume_profile)
# vwap = calc_vwap() # try period='D'


# plot
fplt.create_plot('Demo')
fplt.plot(df.date,df.close, legend='Price')
fplt.horiz_time_volume(time_volume_profile, draw_va=0.7, draw_poc=1.0)
fplt.show()

**Comment by highfestiva** [comment]
Please zip code+data and I'll try to figure out what bug you've written.
