### ISSUE TITLE
[BUG] Kernel Crash in Jupyter (into VSCode)

### ISSUE THREAD

**Issue by localcreator** [highfestiva/finplot#356]
When trying to import finplot, a kernel Jupyter error occurs
![finplot_crash](https://user-images.githubusercontent.com/76257407/184335694-0ecdf611-439a-4eeb-bcb7-60e31725f47b.png)

### Code to reproduce
```python
import finplot as fplt
```

### Describe the bug
При выполнении кода в текущей ячейке или предыдущей ячейке ядро аварийно завершило работу. Проверьте код в ячейках, чтобы определить возможную причину сбоя. Щелкните <a href="https://aka.ms/vscodeJupyterKernelCrash">здесь</a> для получения дополнительных сведений. Подробнее см. в [журнале Jupyter](command:jupyter.viewOutput).
Canceled future for execute_request message before replies were done

### Expected behavior
Sucsess or clear field whith green bird

#### Reproducible in:

*OS*: Kubuntu 22.04.1
*finplot version==1.8.1, 1.8.2
*pyqtgraph version==0.12.4
*pyqt version==5.15.7 (automated installation whith finplot)

**Comment by highfestiva** [comment]
https://github.com/highfestiva/finplot#what-it-is-not

**Comment by localcreator** [comment]
> https://github.com/highfestiva/finplot#what-it-is-not

But version 1.8.0 works fine in jupyter. It's strange that the newer version has worse functionality..

**Comment by highfestiva** [comment]
Sorry to hear that, and you're more than welcome to send in a pull request, but the variation of environments that people are using is simply to great for me to maintain. If you use it vanilla, it works.
