### ISSUE TITLE
[BUG] Label in examples/pandas-df-plot.py is showing a wrong value

### ISSUE THREAD

**Issue by Invidia19** [highfestiva/finplot#362]
### Requirements (place an `x` in each of the `[ ]`)**
* [x] I realize finplot is not a web lib. (Hint: it's native!)
* [x] I've read the [snippets](https://github.com/highfestiva/finplot/wiki/Snippets) and not found what I'm looking for.
* [x] I've searched for any related issues and avoided creating a duplicate issue.
* [x] I've updated finplot (`pip install -U finplot`).
* [x] I've supplied the required data to run my code below.

### Code to reproduce

```python
#!/usr/bin/env python3

import finplot as fplt
import pandas as pd

df = pd.DataFrame({'A':[1,2,3,5], 'B':[2,4,5,3], 'C':[3,6,11,8], 'D':[1,1,2,2], 'labels':list('ABCD')}, index=[1606086000, 1606086001, 1606086002, 1606086003])

df.plot('A')
df.plot('A', 'labels', kind='labels', color='#FF0000')
# print(df)
df.plot('C', kind='scatter')
(1-df.B).plot(kind='scatter')
df.plot(kind='candle').setZValue(-100)
(df.B-4).plot.bar()

fplt.show()

```

### Describe the bug
line 9 is suppose to be producing labels of "A" "B" "C" "D", but in the screenshot it's showing "2" "4" "5" "3"

### Expected behavior
labels of "A" "B" "C" "D"

#### Screenshots
![image](https://user-images.githubusercontent.com/54266187/187701060-59a020d1-526f-4926-b387-5da123c3c94f.png)

#### Reproducible in:

*OS*: Windows 10
*finplot version*: 1.8.1
*pyqtgraph version*: 0.11.1
*pyqt version*:
*python version*: 3.6.5

**Comment by highfestiva** [comment]
Good call, something I missed. You can either patch https://github.com/highfestiva/finplot/commit/a45f9c33d23b57a42c29b503806c96ea1435d007 or simply do this until the next release:
```python
df[['A','labels']].plot(kind='labels', color='#FF0000')
```
