### ISSUE TITLE
[BUG] Backend error in pyinstaller.

### ISSUE THREAD

**Issue by big100** [highfestiva/finplot#363]
### Describe the bug

```
When I create an exe file with pyinstaller and run it, an error occurs.

ValueError: Could not find plotting backend 'finplot.pdplot'. Ensure that you've installed the package providing the 'finplot.pdplot' entrypoint, or that the package has a top-level `.plot` method.
[163972] Failed to execute script 'test5' due to unhandled exception!

but this part
pd.set_option('plotting.backend', 'finplot.pdplot')

If I disable it like below, there is no problem.
# pd.set_option('plotting.backend', 'finplot.pdplot')

Is there any way to use it without disabling it?

If disabled, moving averages cannot be used in pyinstaller.

```

### Expected behavior
A clear and concise description of what you expected to happen instead.

#### Screenshots
🔽 error code 🔽
![image](https://user-images.githubusercontent.com/37491415/190068210-3a422278-a85c-4772-b4fa-62135f274fe9.png)
```
Traceback (most recent call last):
  File "test5.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "finplot\__init__.py", line 2807, in <module>
  File "pandas\_config\config.py", line 256, in __call__
  File "pandas\_config\config.py", line 153, in _set_option
  File "pandas\core\config_init.py", line 719, in register_plotting_backend_cb
  File "pandas\plotting\_core.py", line 1849, in _get_plot_backend
  File "pandas\plotting\_core.py", line 1818, in _load_backend
ValueError: Could not find plotting backend 'finplot.pdplot'. Ensure that you've installed the package providing the 'finplot.pdplot' entrypoint, or that the package has a top-level `.plot` method.
[163972] Failed to execute script 'test5' due to unhandled exception!

```

#### Reproducible in:

🔽 sorce code🔽
```

import finplot as fplt
import numpy as np
import pandas as pd

from pyqtgraph.graphicsItems.ViewBox.axisCtrlTemplate_pyqt5 import * 
from pyqtgraph.graphicsItems.ViewBox.axisCtrlTemplate_pyside2 import *
from pyqtgraph.graphicsItems.PlotItem.plotConfigTemplate_pyqt5 import * 
from pyqtgraph.graphicsItems.PlotItem.plotConfigTemplate_pyside2 import *
from pyqtgraph.imageview.ImageViewTemplate_pyqt5 import * 
from pyqtgraph.imageview.ImageViewTemplate_pyside2 import * 
from pyqtgraph.console.template_pyqt5 import *
from pyqtgraph.console.template_pyside2 import *

dates = pd.date_range('01:00', '01:00:01.200', freq='1ms')
prices = pd.Series(np.random.random(len(dates))).rolling(30).mean() + 4
fplt.plot(dates, prices, width=3)
line = fplt.add_line((dates[-1], 4.5), (dates[-100], 4.5), color='#9900ff', interactive=False)

text = fplt.add_text((dates[-50], 4.5), "ask4625482654", color='#bb7700')
fplt.show()
```

🔽 error line 🔽
```
__init__.py
# use finplot instead of matplotlib
pd.set_option('plotting.backend', 'finplot.pdplot')


```
🔽 command 🔽

pyinstaller -F --paths=C:\Miniconda3\envs\pyinstall_32_test\Lib\site-packages --clean -n test test5.py ↲

*OS*: windows10

altgraph                  0.17.2
certifi                   2021.10.8
chardet                   5.0.0
finplot                   1.8.2
future                    0.18.2
natsort                   8.1.0
numpy                     1.23.2
pandas                    1.4.4
pefile                    2022.5.30
pip                       21.2.4
pyinstaller               5.3
pyinstaller-hooks-contrib 2022.3
PyQt5                     5.15.7
PyQt5-Qt5                 5.15.2
PyQt5-sip                 12.11.0
pyqtgraph                 0.12.4
PySide2                   5.15.2.1
python-dateutil           2.8.2
pytz                      2022.2.1
pywin32-ctypes            0.2.0
Send2Trash                1.8.0
setuptools                58.0.4
shiboken2                 5.15.2.1
six                       1.16.0
tinyaes                   1.0.3
wheel                     0.37.1
wincertstore              0.2

**Comment by highfestiva** [comment]
You should add `finplot/pdplot.py` to the bundle you're trying to package. I don't know how that's done in pyinstaller, but probably not very complicated.

**Comment by big100** [comment]
Thank you I solved it.

I solved it with the options below.
--collect-submodules finplot.pdplot
