### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Yazzito** [highfestiva/finplot#364]
### Requirements (place an `x` in each of the `[ ]`)**
* [x] I realize finplot is not a web lib. (Hint: it's native!)
* [x] I've read the [snippets](https://github.com/highfestiva/finplot/wiki/Snippets) and not found what I'm looking for.
* [x] I've searched for any related issues and avoided creating a duplicate issue.
* [x] I've updated finplot (`pip install -U finplot`).
* [x] I've supplied the required data to run my code below.

### Code to reproduce

```python
import sys
import finplot as fplt
from PyQt6.QtWidgets import *
import yfinance


# Creating the main window
class App(QMainWindow):
    def __init__(self):
        super().__init__()
        self.title = 'PyQt6 - QTabWidget'
        self.left = 0
        self.top = 0
        self.width = 600
        self.height = 400
        self.setWindowTitle(self.title)
        self.setGeometry(self.left, self.top, self.width, self.height)

        self.tab_widget = MyTabWidget(self)
        self.setCentralWidget(self.tab_widget)
        fplt.show(qt_exec=False)
        self.show()

    # Creating tab widgets


class MyTabWidget(QWidget):
    def __init__(self, parent):
        super(QWidget, self).__init__(parent)
        self.layout = QVBoxLayout(self)

        # Initialize tab screen
        self.tabs = QTabWidget()
        self.tabs.setMovable(True)

        self.tab1 = QWidget()

        self.tabs.resize(600, 400)

        # Add tabs
        self.tabs.addTab(self.tab1, "tab1")

        self.tab1.layout = QVBoxLayout(self)
        self.tab1.label = QLabel("AAPL")
        self.tab1.df = yfinance.download('AAPL')
        self.tab1.fplt_widget = fplt.create_plot_widget(self.window())
        fplt.candlestick_ochl(self.tab1.df[['Open', 'Close', 'High', 'Low']])
        self.tab1.layout.addWidget(self.tab1.label)
        self.tab1.layout.addWidget(self.tab1.fplt_widget.ax_widget)
        self.window().axs = [self.tab1.fplt_widget] # required property of window
        self.tab1.setLayout(self.tab1.layout)

        # Add tabs to widget
        self.layout.addWidget(self.tabs)
        self.setLayout(self.layout)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = App()
    sys.exit(app.exec_())

```

### Describe the bug
Hello!  The provided code is an example you helped another user create and I'm just re-using it to illustrate this issue.
The issue is related to Finplot and PyQt6. 

The code works in PyQt5 and displays the GUI, tabwidget and data. When I change the import to PyQt6 (I'll show the change below), the program crashes with no message and no GUI is displayed.

The only change is the import call:
from PyQt5.QtWidgets import *
to:
from PyQt6.QtWidgets import *

PS. The line it crashes on is:
self.tab1.fplt_widget = fplt.create_plot_widget(self.window())

### Expected behavior
I'm trying to figure out if Finplot is compatible with PyQt6? I did search the forums for Finplot and PyQt6 status, but couldn't find any info.

#### Screenshots
None

#### Reproducible in:

*OS*: Windows
*finplot version*: 1.8.2
*pyqtgraph version*: 0.12.4
*pyqt version*:
PyQt5 5.15.6
or
PyQt6 6.3.1

**Comment by highfestiva** [comment]
Hi Yazzito! I don't think so, but haven't checked. Do you know if pyqtgraph is compatible? I don't do particularly much Qt trickery, so it might be something very easy to fix. If you find the bug, please post a pull request, thanks!

**Comment by Yazzito** [comment]
Thank you for your response. I am looking into the root cause but I do have one additional related question/issue.

Regarding the imports, the order in which I import PyQt5 and finplot do not matter. (GUI works as expected either way.)
With PyQt6, swapping the order yields different errors. (code used is the same as the provided in the original ticket btw)
--- If PyQt6 is imported before finplot, I get the following errors from finplot:

in module
    import finplot as fplt
  File "site-packages\finplot\__init__.py", line 604, in <module>
    class FinPolyLine(pg.PolyLineROI):
  File "site-packages\finplot\__init__.py", line 644, in FinPolyLine
    def movePoint(self, handle, pos, modifiers=QtCore.Qt.KeyboardModifier(), finish=True, coords='parent'):
TypeError: EnumMeta.__call__() missing 1 required positional argument: 'value'

--- If finplot (and by extension pyqtgraph) is imported before PyQt6, then the program crashes when trying to create the fplt_widget as described in the top of this bug.

--------------------
The reason why I mention this is because I read [here](https://stackoverflow.com/questions/70887458/adding-pyqtgraph-to-pyqt6)  that PyQt6 must be imported before pyqtgraph.

But if I import PyQt6 then finplot appears to crash with the error described above (TypeError: EnumMeta.__call__() missing 1 required positional argument: 'value')

Any ideas on what the TypeError is referring to internal to finplot or things I could try?

If I do find the root cause, I will post back here.

**Comment by highfestiva** [comment]
Thanks for the investigation. It seems `QtCore.Qt.KeyboardModifier` is no longer a function, but an enum. You could try removing the `()` to see if that helps. Don't know the best approach to making this Qt5-compatible though. Feel free to take a look at what they do in pyqtgraph if you have the time.

**Comment by Yazzito** [comment]
Yes, you're correct. Details below but I am now able to view and interact with the charts & data in PyQt6.

There are 3 issues identified so far in the finplot code with regards to PyQt6.

1) All the enumerations have changed as you mentioned above.  There are a dozen or two of these I've updated so far. Updating all of these allowed me to display and view the widget/plot. Interaction with the plot only partially worked as I also needed to update the QWheelEvent as show in update #2 below.

Example:
old: (in finplot __init__.py)
if ev.button() != QtCore.Qt.LeftButton or ev.modifiers() != QtCore.Qt.ControlModifier or not self.draw_line:
new:
if ev.button() != QtCore.Qt.MouseButton.LeftButton or ev.modifiers() != QtCore.Qt.KeyboardModifier.ControlModifier or not self.draw_line:

2) The QWheelEvent arguments have changed. The QPoint items are now QPointF. Any .pos definition is now .position.

Original code: (in finplot __init__.py)
d = QtCore.QPoint(-2,0)
ev = QtGui.QWheelEvent(ev.pos()+d, ev.globalPos()+d, ev.pixelDelta(), ev.angleDelta(), ev.angleDelta().y(), QtCore.Qt.Vertical, ev.buttons(), ev.modifiers())

PyQt6 Working code:
d = QtCore.QPointF(-2,0)
ev = QtGui.QWheelEvent(ev.position()+d, ev.globalPosition()+d, ev.pixelDelta(), ev.angleDelta(), ev.buttons(), ev.modifiers(), ev.phase(), ev.inverted())

PS. You can view the PyQt6 QWheelEvent def [Qt6](https://doc.qt.io/qt-6/qwheelevent.html) - in case I missed anything!

3) PyQt6 MUST be imported before pyqtgraph. Since finplot loads pyqtgraph, PyQt6 MUST be imported before finplot.

---------- Summary:
The plot (actually widget for me) is now working fine in PyQt6 after these 3 fixes. Yay!

I did not exhaustively test all features in finplot in PyQt6. Everything I did test (mouse events, keys, etc..) worked but you may have more exhaustive testcases to try.

That's it. If you'd like me to upload the modified finplot code to this ticket, please let me know. Otherwise, you can close this ticket I think? Thank you again for your responses and help! Much appreciated!

**Comment by highfestiva** [comment]
Thank you so much for the help! I'll try to investigate how hard it is to be compatible between the two versions and try add some compatibility indirections. Please keep the ticket open.

**Comment by highfestiva** [comment]
Transitioned to PyQt6 in efb869668b2d0eb35e332eed5fce75f523b8ad0a.
