### ISSUE TITLE
If you zoom in, the top and bottom are cut off. Is there a function to move the graph up and down?

### ISSUE THREAD

**Issue by big100** [highfestiva/finplot#366]
The zoom function is used well with Ctrl+Mheel.

However, if you zoom in, the top and bottom are cut off.

Is there any way to move the graph up and down at this point?

![image](https://user-images.githubusercontent.com/37491415/191150973-d4eaf6b3-dd83-4924-9a69-66454b7b7ecb.png)

![image](https://user-images.githubusercontent.com/37491415/191150988-f6724449-0038-4ac9-971d-58cc48513ec3.png)

![image](https://user-images.githubusercontent.com/37491415/191151356-2d2880cf-2691-4390-a98f-2f3ec51dfa4d.png)

![image](https://user-images.githubusercontent.com/37491415/191151375-4ff23ca4-5b50-496d-9d2a-8dabb6f3b6c3.png)

**Comment by highfestiva** [comment]
No, there is currently no way to do that. Temporarily you can zoom in using right mouse drag, but that will reset as soon as you pan/zoom.

**Comment by big100** [comment]
Thank you for your answers.
