### ISSUE TITLE
[BUG] There is a bug in the 1.8.3 update. add_line is not removed with remove_line

### ISSUE THREAD

**Issue by big100** [highfestiva/finplot#367]
There is a bug in the 1.8.3 update.

add_line is not deleted with remove_line
add_text is deleted fine with remove_text

In 1.8.2 there is no problem.

![image](https://user-images.githubusercontent.com/37491415/191875197-ef3ea82c-0850-45cc-b137-fc11ab662655.png)

![image](https://user-images.githubusercontent.com/37491415/191875222-dfbad9a3-7ffa-46e7-89be-4af855a2180c.png)

**Comment by highfestiva** [comment]
Oops, fix in 6b40a65b.

**Comment by big100** [comment]
Will it be fixed after 1.8.3 update?

**Comment by highfestiva** [comment]
Release 1.8.4 should contain the fix.
