### ISSUE TITLE
Use OHLCV instead of OCHLV. It's more commom to see open, high, low, close, volume

### ISSUE THREAD

**Issue by arturdaraujo** [highfestiva/finplot#374]
### Describe the bug
Great package! This is silly and not really a bug but a design suggestion. The most common column order for financial assets is ohlcv (open, high, low, close, volume). This order is more common if you check other packages (pandas-ta, ta, ta-lib, alpha-vantage, yfinance, etc).  Other than that, very cool graphic wrapper for stocks.

**Comment by highfestiva** [comment]
I've contemplated this [before](https://github.com/highfestiva/finplot/issues/257#issuecomment-926956493) (a few times in fact) and come to the conclusion that for consistency with a) the volume plot (which is open-close-volume), and b) the internal data structure (which auto-scales the Y-axis based on the last columns).

It's a possibility to add a helper function which just transforms the data, but it would cost a bit of performance and more importantly maintenance. But then confusion would/might increase, as there would be two almost-identically named functions which do the same thing. For compatibility it's not a good thing to replace what we have with a new function either.

**Comment by arturdaraujo** [comment]
Thanks for the answer! Performance and maintenance should definitely come first.

**Comment by highfestiva** [comment]
Started this, which doesn't seem to interest anyone: https://github.com/highfestiva/finplot/discussions/375 ;)

**Comment by highfestiva** [comment]
5/6 votes on keeping as is. Not much to go on, but probably not going to swing in favor of changing names though. Closing this.
