### ISSUE TITLE
Where can I find out about the new features of new release?

### ISSUE THREAD

**Issue by sunjar2020** [highfestiva/finplot#376]
After a few months, I visited your github homepage again, and I was glad to found that finplot has been updated with two new versions, 1.83 and 1.8.4. Thanks for your work! However, I checked the web pages about finplot on github and pypi, but I couldn't find what features have been added in the new version.  So where should I see this? 

Thank you!

**Comment by highfestiva** [comment]
Unfortunately you'd have to read what's new in commit comments. Lately it's been mostly bug fixes. Whenever I add something more substantial, I either update the examples or add a new one.

**Comment by sunjar2020** [comment]
Understood, thank you!
