### ISSUE TITLE
Draw line with list of [x,y] points

### ISSUE THREAD

**Issue by Sebastian7700** [highfestiva/finplot#377]
I'm not really sure if I should put this in an issue, so if this is not one just remove it.
My issue is, I can't find a feature to draw a line with a list of [x,y] points.

So basically I have calculated the ZigZag indicator and I want to plot the line.
In my dataframe, I have two columns indicating if the line connects to the high of the candle, the low of the candle, or not connecting:
high points = [0,0,1,0,1,0]
low points = [0,1,0,1,1,0]
With high and low data, you can obviously calculate x, y positions on the chart.
Note that a line can connect from the high of a candle to the low of the same candle (this is why I don't just plot a line).

Thanks for the awesome library.

**Comment by highfestiva** [comment]
The only way finplot supports this in the current version is to draw a bunch of individual lines. Drawing a "poly line" could be done accessing some finplot internals, but is also possible using the underlying pyqtgraph api (both come with some drawbacks. Example of the latter:

```python
#!/usr/bin/env python3

import finplot as fplt
import numpy as np


ax = fplt.create_plot('zigzag')

# plot some candlesticks
candles = np.random.random([4, 50]) + 5
candles = np.sort(candles, axis=0)
candles = [np.arange(50), candles[1], candles[2], candles[3], candles[0]]
fplt.candlestick_ochl(candles)

# add your own plot on top
x = candles[0].copy()
np.random.shuffle(x)
y = np.random.random(50) + 5
item = ax.plot(x, y, pen=fplt._makepen(color='#f00'))
item.setZValue(5)

fplt.show()
```

**Comment by highfestiva** [comment]
Support for this feature could be added in at least a couple of different ways. Would be interesting to know more about your visualization, could you post a mock that I could look at to give me a sense of how you'd want to use this feature?

**Comment by Sebastian7700** [comment]
Hey mate, thank you for the example code.
This is exactly what I wanted to do. Here is how it looks:
![zigzag](https://user-images.githubusercontent.com/61465142/197499006-96d55bb7-eff7-4b30-bd40-c70ec9e04222.png)

Works like a charm!
So basically that's enough for me. I don't need further implementation.

Btw if you or someone else is interested in the zigzag code, I can share it. The Tradingview indicator has two parameters (percent change and depth). The image shows values for 8% and depth=1. The only problem is I couldn't implement it for some other depth than 1. So basically if somebody else wants to try...
