### ISSUE TITLE
Is there a way to add a horizontal bar to one subplot?

### ISSUE THREAD

**Issue by sunjar2020** [highfestiva/finplot#379]
Is there a way to add a horizontal bar to one subplot? The bar's width is the length of the canvas, its height can be customized, and the color in its inside can varies with the magnitude of the value, like a heatmap, that's is the color to be white when the value is 0, then positive numbers are represented as red, and negative numbers are represented as blue. The larger the value, the darker the color.

The data can be a numpy array or dataframe's column values. like as:
`np.random.seed(9)`
`simu_data = np.random.randint(-100000, 100000, size = 200).cumsum()`

![sample](https://user-images.githubusercontent.com/64413895/200554422-2a3d7237-ea19-43d5-85b9-8bc4d930c84b.png)

**Comment by highfestiva** [comment]
Yes there is, but you have to manage parts of it yourself, depending on what you want. See `examples/bubble-table.py` for how to plot a low resolution heat map on the second plot (with labels on top). `pyqtgraph` (the underlying plotting lib) has support for various color components, you could possibly use one of those. Let me know how it goes.

**Comment by sunjar2020** [comment]
I'll look into it, thank you.

**Comment by highfestiva** [comment]
Did you get something working?

**Comment by sunjar2020** [comment]
> Did you get something working?

Not yet. I'm sorry I read the code of bubble-table, it's a little bit complicated to me,  I'll look at it when I have time, I have another higher priority work about finplot now, and I'm going to post another issue, so let me just turn this issue off.
