### ISSUE TITLE
[BUG] No separate "candle_bear_body_color"

### ISSUE THREAD

**Issue by gabrsafwat** [highfestiva/finplot#381]
"candle_bear_body_color" is missing

**Comment by highfestiva** [comment]
It defaults to `candle_bear_color`, but is also reachable from the plot:
```python
plot = asset[['Open','Close','High','Low']].plot(kind='candle')

plot.colors.update(dict(
  bull_shadow = '#388d53',
  bull_frame  = '#205536',
  bull_body   = '#52b370',
  bear_shadow = '#d56161',
  bear_frame  = '#5c1a10',
  bear_body   = '#e8704f'))
```

**Comment by gabrsafwat** [comment]
This is better to resolve in the source code library by adding (after line 43):
`candle_bear_body_color = background`
then adding (after line 1120):
`bear_body        = candle_bear_body_color,`

<img width="801" alt="2022-11-11_13-56-17" src="https://user-images.githubusercontent.com/42674507/201335623-51e6c519-8db1-4fa4-8d45-3e7833037980.png">

this is much easier!

**Comment by highfestiva** [comment]
Thanks, good idea, fixed in 29b43ed.

**Comment by gabrsafwat** [comment]
Thank you for making this library the best for financial plotting. This library could exceed expectations considering the minor comments like those posted in the issues section. I truly love it.
Please keep up the good work.

**Comment by gabrsafwat** [comment]
Also in the AK-Indicator, is there a way to color the line "green" (when > 0) and "red" (when < 0)?
It will also be great if I can add a horizontal "0" line!

Thank you

**Comment by highfestiva** [comment]
The MACD colors are calculated based on your preferred candle colors. You can override, se examples for that and the horizontal line. See https://github.com/highfestiva/finplot/issues/26  for info on plotting different colors (same applies for both scatter plot and line plot).

**Comment by highfestiva** [comment]
The MACD colors are called `weak_...` These are the defaults:

```python
                           weak_bull_shadow = brighten(candle_bull_color, 1.2),
                           weak_bull_frame  = brighten(candle_bull_color, 1.2),
                           weak_bull_body   = brighten(candle_bull_color, 1.2),
                           weak_bear_shadow = brighten(candle_bear_color, 1.5),
                           weak_bear_frame  = brighten(candle_bear_color, 1.5),
                           weak_bear_body   = brighten(candle_bear_color, 1.5))
```

**Comment by gabrsafwat** [comment]
Modifying the code presented above produced more issues. I can clearly see in your code that you are following a specific coloring schema, which is hard to change without modifying the source code. I hope in the future you can provide some flexibility for end-users to customize the coloring schema without having to dig deep into the source code.... I still like your library though!

**Comment by highfestiva** [comment]
You can, the same way some example does it with the returned plot. Think perhaps in the bitmex and snp examples, I don't remember exactly but have a look.

**Comment by highfestiva** [comment]
Also see my second comment on this issue.
