### ISSUE TITLE
[BUG]: __call__() missing 1 required positional argument: 'value'

### ISSUE THREAD

**Issue by Rahib4** [highfestiva/finplot#383]
### Requirements (place an `x` in each of the `[ ]`)**
* [ ] I realize finplot is not a web lib. (Hint: it's native!)
* [ ] I've read the [snippets](https://github.com/highfestiva/finplot/wiki/Snippets) and not found what I'm looking for.
* [ ] I've searched for any related issues and avoided creating a duplicate issue.
* [ ] I've updated finplot (`pip install -U finplot`).
* [ ] I've supplied the required data to run my code below.

### Code to reproduce

```python
import pandas as pd
import numpy as np
import requests 
import time
import yfinance as yf
# from PyQt6.QtWidgets import *
import finplot
from io import StringIO
```

### Describe the bug
When I am trying to import finplot library it throws an error. I am running Python 3.8 on window. I have also tried PyQt5 & 6.
Tried installing and uninstalling libaries. Restarted my laptop, hoping that might fix the bug.

### Expected behavior
It should simply load the library.

#### Screenshots
![image](https://user-images.githubusercontent.com/13463450/200998154-6ec3c367-981d-4d87-a4fc-fe1e49c2562e.png)

#### Reproducible in:

*OS*: Windows 10
*finplot version*: 1.8.4
*pyqtgraph version*: 0.13.1
*pyqt version*:5.15.7

**Comment by highfestiva** [comment]
It seems newer versions of PyQt is not backwards compatible. I'll look into it in a few days.

**Comment by Kwameamerica** [comment]
By

**Comment by pony010** [comment]
Got the same erro

**Comment by highfestiva** [comment]
Transitioned to PyQt6 in efb869668b2d0eb35e332eed5fce75f523b8ad0a.

**Comment by cong-1** [comment]
Is this error due to the use of PyQt inside Jupyter?
