### ISSUE TITLE
I get this error: Process finished with exit code 1

### ISSUE THREAD

**Issue by xor85** [highfestiva/finplot#389]
When I run the examples on PyCharm I get this error message:
Process finished with exit code 1

Even an empty file with one command (import finplot as fplt) causes this exit code.

Using the search, I found that using version 1.8.0 helps, but this is not an option

**Comment by xor85** [comment]
> Most probably sanctions.
Sanctions?
I have only one line of code:

import finplot as fplt

causes this error, I don't even connect to anything.
Or is it your sanctions as a developer? The description of the package does not say anything about sanctions.

**Comment by Konstantin-Leontyev** [comment]
What does it mean?

**Comment by xor85** [comment]
> 
Найди в коде строчку с определением локации и закоменть ее. Все будет работать

**Comment by Konstantin-Leontyev** [comment]
Спасибо, как раз разобрался.

**Comment by Evgeniy-Zh** [comment]
Sanctions against who? Sanctions against the ones who speak russian? Hmm, which countries could it be...? What the genius has come up with this? What do you think this locale means 'ru_UA'? (locale of my system) Or maybe you want to sanction both sides of the conflict, ok then, no questions.
