### ISSUE TITLE
Unvisualized moving average 

### ISSUE THREAD

**Issue by MateoeslaLey** [highfestiva/finplot#39]
Hi! 

First of all, great job with this module! it really saves me lot of time.

Now, when I plot a moving average, it doesnt plot. After a while trying, I literally took your example number two where a ma of 25 candles is plotted, and still doesnt plot anything.

Maybe its a configuration or something.

Thaks in advance!

Great things!

**Comment by Trembles** [comment]
Bit hard to help when you don't provide any code of what you have done.

**Comment by highfestiva** [comment]
Guessing you're using the wrong version of Qt. You should have `PyQt5==5.13.0`. There's a bug in newer versions of Qt, see [here](https://github.com/pyqtgraph/pyqtgraph/issues/1057). You could try to do a `.dropna()` like so: `.rolling(20).mean().dropna()` in your plot, and if that works, talk to Qt.

**Comment by highfestiva** [comment]
I assume you do not see the blue line in [example-line.py](https://github.com/highfestiva/finplot/blob/master/finplot/example-line.py)? Replace the third line (the `plot()` call) with this:
````python
df = pd.DataFrame({'dates': dates, 'prices':prices}).dropna().reset_index(drop=True)
dates,prices = df['dates'],df['prices']
fplt.plot(df, width=3)
````
If that shows the line, downgrade pyqt5 to 5.13.0.

**Comment by arul67800** [comment]
Hi sir, so far the best plotting tool for financial marker..any way possible to change candle stick time duration eg(1,3,5,15,1hr,) and chart type(eg,candle stick,heikinashi, renko ) from chart itself without going to code?? would be great if it happens..thanks in advance..also..can you plot supertrend and linear regression scripts??

**Comment by highfestiva** [comment]
@arul67800 can't see how this is part of the original issue?

The flipping between intervals and types is easy to do yourself using finplot, but it is an application responsibility and is not part of a plotting library, nor will it be in the future. The same goes for supertrend and linear regression. To see an example of linear regression for price correlation, have a look at example-overlay-correlate.py.

Closing this due to lack of feedback.

**Comment by highfestiva** [comment]
Most recent finplot supports all Qt versions.
