### ISSUE TITLE
the program crashes without an error[BUG]

### ISSUE THREAD

**Issue by 118260** [highfestiva/finplot#392]
Code:

print("start")
import finplot as fplt
print("BLA BLA BLA")

output: 

start
Press any key to continue . . .

**Comment by 118260** [comment]
2 weeks ago the code worked) 
And then abruptly stopped

**Comment by highfestiva** [comment]
Probably a result of sanctions against Russia(b) or Belarus(sian) since the start of the war against Ukraine.

**Comment by 118260** [comment]
I'm just curious
Have you personally blocked for russians and belarusians?

**Comment by highfestiva** [comment]
No doubt individuals and small groups can be moronic and malicious. When a state does it, it's a different matter. Sanctions are _intended_ to pressure citizens toward change, not the heads of state (which are mostly impossible to reach directly). We individuals must stand against all types of misconduct, not point the finger at other ppl behaving badly.

**Comment by 118260** [comment]
Europeans and Russians have different mentality)
In Europe, states are afraid of protests. Since they remember what happened in France in the 1800s
It doesn't work in Russia. The reason is in the history of Russia. In the 1930s there were repressions in the USSR. The Communist bastards shot a lot of people. Including my great-grandfather. After Stalin's death, repressions became much less, but they did not disappear, and even in the 1980s they could be sent to a camp for disagreement with politics. People remember this and therefore the protests are not as active as in Europe.
Russia has a well-built vertical of power. If a new leader of the opposition appears, he is quickly imprisoned. You can sit down for a while even for showing an empty poster in your hands on Red Square. No one will protest without the opposition leader. At the moment, no one is thinking about protests, because an external threat has appeared. In Russia, people take sanctions personally, that is, simply because you are Russian. Therefore, the sanctions only united the peoples in Russia. 
People don't see the point of protests, they'll put you in jail anyway)
People in Russia on February 24th were shocked by the entry of troops. No one wanted a war, because many people have relatives in Ukraine. Then there were protests, but everyone was dispersed, and some were imprisoned.
Belarusians protested the most in the 20th year. But even there, the protests were severely suppressed, people were simply knocked down by police trucks and shot with traumatic weapons. Tortured by the police. There is no such cruelty in Europe. That's the answer to why sanctions don't work. 
Finally, I will only say that by hurting an opponent, you will not build peace. I 'm sorry for my bad English. And have a good day to you)

**Comment by highfestiva** [comment]
We will be judged by what we do. None is remembered for doing nothing, as nothing could be done in a complex world. I'm not looking to hurt anyone, and I don't consider your my opponent. Apology accepted. ;) Have a great day!
