### ISSUE TITLE
Updating the last bar

### ISSUE THREAD

**Issue by RafaelLima7** [highfestiva/finplot#397]
Hello, looking forward to thank you for the library, it's wonderful.
I'm trying to make the chart update only the last bar, and not the entire history (in order to decrease the latency). How could I do this? I used the most complicated example. But I couldn't do it in the "for k in data:" part or in the plots.
Would you help me? Thanks

**Comment by highfestiva** [comment]
There are three examples which do real-time updates of the last candle. Please have a look at those.
