### ISSUE TITLE
how the align the x between axs?

### ISSUE THREAD

**Issue by Fantasticer** [highfestiva/finplot#4]

**Comment by highfestiva** [comment]
The axis should already be aligned. One case I can think of when they’re not is if one plot has y-axis labels that are much wider than the others. I’ll add something for it in the comming days.

Skickat från min iPhone

**Comment by Fantasticer** [comment]
yes, the wide different range of different axs cause this problem.

**Comment by highfestiva** [comment]
Wasn't able to reproduce, assume you're under a different OS than Windows? Anyhoo, I supplied a fix for it. Just after you've imported, simply go `fplt.y_label_width = 200` or whatever is fitting. A full example:

	#!/usr/bin/env python3

	import finplot as fplt
	import numpy as np
	import pandas as pd

	dates = pd.date_range('01:00', '21:30', freq='1min')
	prices = pd.Series(np.random.random(len(dates))).rolling(30).mean() + 4
	fplt.y_label_width = 230
	ax,ax2 = fplt.create_plot('Crap stuff', rows=2, maximize=False)
	fplt.plot(dates, prices, ax=ax)
	fplt.plot(dates, np.random.random(len(dates))*3e5, ax=ax2)
	fplt.show()

This minor changed is pipped as 0.3.6, good luck!
