### ISSUE TITLE
IndexError: index 4 is out of bounds for axis 0 with size 4

### ISSUE THREAD

**Issue by stroack** [highfestiva/finplot#404]
Hi,
I'm trying to create a candle charts using this simple code below but it give me the error in object.

```
import pandas as pd
import finplot as fplt

df = pd.read_excel(.../Data/KO.xlsx')
ax= fplt.create_plot('CocaCola', rows=1)
candles = df[['Date','Open','Close','High','Low']]
fplt.candlestick_ochl(candles, ax=ax)
fplt.show()
```

Both library are updated, Python versione 3.9.13

Could someone tell me how to solve the problem or tell me where to look for information to learn more and find a solution?

Thanks a lot

**Comment by highfestiva** [comment]
Looks like your data is lacking datetime. I should add some type of error log message, but at least still show something. I'll have a look.

**Comment by highfestiva** [comment]
If you instead use my fix in 5857588, you'll get a warning message and it should still display the candlesticks. Albeit with no datetime (as you've not supplied any).

**Comment by stroack** [comment]
Hi highfestiva, thank you so much for your attention.
I confirm that after the fix I can view the chart. I also tried running the code by removing the 'Date' and the issue persists.

`import pandas as pd
import finplot as fplt

```
import pandas as pd
import finplot as fplt

df = pd.read_excel(.../Data/KO.xlsx')
ax= fplt.create_plot('CocaCola', rows=1)
candles = df[['Open','Close','High','Low']]
fplt.candlestick_ochl(candles, ax=ax)
fplt.show()
```

For completeness, I am attaching the excel (data downloaded from yahoo in csv and converted to excel)
[KO.xlsx](https://github.com/highfestiva/finplot/files/10555715/KO.xlsx)

**Comment by highfestiva** [comment]
Is this the same data and code you're running? Works for me with your KO.xlsx and

```python
import pandas as pd
import finplot as fplt

df = pd.read_excel('KO.xlsx')
ax= fplt.create_plot('CocaCola', rows=1)
candles = df[['Date','Open','Close','High','Low']]
fplt.candlestick_ochl(candles, ax=ax)
fplt.show()
```
![image](https://user-images.githubusercontent.com/160303/216072352-7befc950-c412-49c2-9b46-b9134e7b4ba8.png)

**Comment by stroack** [comment]
Sorry, in my second post I explained myself very badly.
With the first code,
`candles = df[['Date','Open','Close','High','Low']]`

It's all ok!

In the second post,
`candles = df[['Open','Close','High','Low']]`

**without** 'Date' before 'Open' keep giving me "IndexError: index 4 is out of bounds for axis 0 with size 4"

**Comment by highfestiva** [comment]
Aha, please tell me then how you patched my latest change?

**Comment by stroack** [comment]
Hi, I apologize for the delay with which I reply.
For your last change I simply upgrade the package.
Now, I make a simply chart with two EMA on it but this time I used data direclty taken from yahoo (without first saving locally and then importing into the code) and everything worked perfectly! So I think it's a problem with the imported excel file and not with the package.
At this point for my operation the problem is overcome.
Thank you so much for your precious support

**Comment by highfestiva** [comment]
My latest changes were not included in any release, but only patched here on github. As soon as the next version comes out, this will be solved (I hope). GL!
