### ISSUE TITLE
blank plot on extremely simple and common data

### ISSUE THREAD

**Issue by spectra-analytics** [highfestiva/finplot#408]
I have extremely simple data in dataframe format -> TOCHLV where T ("time") is in datetime format. This is the example the wiki/readme provides:

```
fplt.candlestick_ochl(df[['Open', 'Close', 'High', 'Low']])
fplt.show()
```

This does not seem to work, errors out no matter how much data-checking I do and data pre-processing.
```IndexError: positional indexers are out-of-bounds```

Alright, so I figured where's the time column? So I fed that in, which is not requested or seemingly required by the examples and that solved the error but I get a completely blank plot. The times seem to be correct (crosshair text shows minute-by-minute which is the format of my data). Nothing else draws. The Y axis is in scientific notation the values are so low.

**Comment by spectra-analytics** [comment]
```raw['time'] = pandas.to_datetime(raw['time'])

        ax = finplot.create_plot('S&P 500')
        finplot.candlestick_ochl(raw[['time', 'open', 'close', 'high', 'low']], ax=ax)
        finplot.show()
```
this is the updated code that needs rectification, still blank.

df snippet:
```
                      time        open        high         low       close  volume
107196 2022-08-23 04:01:00  410.563914  410.663041  410.563914  410.563914    2256
107195 2022-08-23 04:02:00  410.534176  410.881120  410.534176  410.861295    4311
107194 2022-08-23 04:03:00  410.781993  410.781993  410.643215  410.643215    3316
107193 2022-08-23 04:04:00  410.653128  410.781993  410.653128  410.653128    2049
107192 2022-08-23 04:05:00  410.732430  410.781993  410.732430  410.781993     397
...                    ...         ...         ...         ...         ...     ...
4      2023-02-17 19:48:00  407.260000  407.260000  407.240000  407.250000    1046
3      2023-02-17 19:54:00  407.210000  407.210000  407.210000  407.210000     299
2      2023-02-17 19:57:00  407.220000  407.230000  407.220000  407.230000     815
1      2023-02-17 19:59:00  407.250000  407.600000  407.250000  407.560000   14006
0      2023-02-17 20:00:00  407.400000  407.400000  407.380000  407.380000    2440
```

**Comment by Trembles** [comment]
I think your problem is the index is not monotonically increasing and if you want datatime as the x values that should be the index not a column so set time as your index
df.set_index('time', inplace=True)

**Comment by spectra-analytics** [comment]
Nah, i tried that. Changed the indexing. I'm not worried about x/y axis, more or less just getting the library to function at all. I also tried with yfinance, the example straight from the wiki & no dice.

**Comment by Trembles** [comment]
Paste your complete code here and a copy of minimum data so people don't have to guess as to where its going wrong for you but rather replicate exactly on their end.

**Comment by highfestiva** [comment]
Concur, with code+data we'll figure it out. There is no printout warning about your data, particular about your timestamps?

**Comment by spectra-analytics** [comment]
I did post my complete code. I mentioned I tried with yfinance example and same issue. I tried reinstalling the library, but I also have a massively bloated python installation so I might run it in a venv -- could be conflicting with some other lib? If your code works as described in the readme, it must be something else unrelated to the implementation?

**Comment by spectra-analytics** [comment]
> ```
> 
>         ax = finplot.create_plot('S&P 500')
>         finplot.candlestick_ochl(raw[['time', 'open', 'close', 'high', 'low']], ax=ax)
>         finplot.show()
> ```
> 
> this is the updated code that needs rectification, still blank.
> 
> df snippet:
> 
> ```
>                       time        open        high         low       close  volume
> 107196 2022-08-23 04:01:00  410.563914  410.663041  410.563914  410.563914    2256
> 107195 2022-08-23 04:02:00  410.534176  410.881120  410.534176  410.861295    4311
> 107194 2022-08-23 04:03:00  410.781993  410.781993  410.643215  410.643215    3316
> 107193 2022-08-23 04:04:00  410.653128  410.781993  410.653128  410.653128    2049
> 107192 2022-08-23 04:05:00  410.732430  410.781993  410.732430  410.781993     397
> ...                    ...         ...         ...         ...         ...     ...
> 4      2023-02-17 19:48:00  407.260000  407.260000  407.240000  407.250000    1046
> 3      2023-02-17 19:54:00  407.210000  407.210000  407.210000  407.210000     299
> 2      2023-02-17 19:57:00  407.220000  407.230000  407.220000  407.230000     815
> 1      2023-02-17 19:59:00  407.250000  407.600000  407.250000  407.560000   14006
> 0      2023-02-17 20:00:00  407.400000  407.400000  407.380000  407.380000    2440
> ```

This reply is the complete code. Data + my 3 line implementation. "raw" is just the dataframe directly pulled from a CSV. The data output is a print(raw)

**Comment by spectra-analytics** [comment]
```
import finplot as fplt
import yfinance

df = yfinance.download('AAPL')
fplt.candlestick_ochl(df[['Open', 'Close', 'High', 'Low']])
fplt.show()
```

This example from the readme is the one I mentioned, which also does not work. It errors out of the box with the same index error in the OP. If I add the date column, the plot is blank but it executes.

**Comment by highfestiva** [comment]
That is very interesting. What version of finplot are you running? Have you patched it after installation? What version of pandas/numpy are you using? What version of Python?

**Comment by spectra-analytics** [comment]
venv works. looks like this is my problem to figure out. thanks for the help though guys i appreciate it.
