### ISSUE TITLE
set xlabel/ylabel?

### ISSUE THREAD

**Issue by mfiro** [highfestiva/finplot#41]
Hi,

is there any way to set xlabel and ylabel for the plot?

I haven't found this feature.

Thanks

**Comment by highfestiva** [comment]
@mfiro It's possible to use internal (pyqtgraph's) api, like so:

````python
ax,ax2 = fplt.create_plot('Alphabet Inc.', rows=2, maximize=False)
ax.getAxis('right').style['showValues'] = False
ax.setLabel('right', 'Price (USD)')
ax2.getAxis('right').style['showValues'] = False
ax2.setLabel('right', 'Correlation')
````

which gets you this:

![image](https://user-images.githubusercontent.com/160303/94406419-4a564780-0172-11eb-9f8c-732ba7d74919.png)

(The lines `...style['showValues'] = False` simply ensures the text values are not displayed on the right axis too.)
