### ISSUE TITLE
Axies for finplot embed

### ISSUE THREAD

**Issue by Grethold** [highfestiva/finplot#42]
Hi. 
Is it possible to add an additional axis to an embedded project? Like here:
![obraz](https://user-images.githubusercontent.com/24272429/94427688-c448f980-018f-11eb-93b7-d1d6abebd7db.png)

This is that piece of code:
`ax = fplt.create_plot_widget(win, init_zoom_periods=0)`
`win.axs = [ax] # finplot requres this property`
`layout.addWidget(ax.ax_widget, 2, 0, 1, 4)`

Normal we can add axies like that:
`ax,axv,ax2,ax3,ax4 = fplt.create_plot('blabla', rows=5)`

**Comment by highfestiva** [comment]
You sure can.
````python
ax,ax2 = fplt.create_plot_widget(win, rows=2)
win.axs = [ax,ax2] # finplot requres this property
layout.addWidget(ax.ax_widget, 1, 0, 1, 2)
layout.addWidget(ax2.ax_widget, 2, 0, 1, 2)
````
![image](https://user-images.githubusercontent.com/160303/94575414-82de4a00-0274-11eb-8265-767009ad4992.png)
