### ISSUE TITLE
Dissapperance of Y Axis

### ISSUE THREAD

**Issue by deepspkd** [highfestiva/finplot#425]
First of all thankyou for such a great tool. 

I am trying to make a standalone windows app. The issue i encountered was, X Axis is disappearing when i reach the left end of the chart, i.e. when its showing the first two lines from the csv file. 
![With Y Axis](https://github.com/highfestiva/finplot/assets/66288861/e47fc75f-d05c-4e63-b776-ee45aad95697)
With X Axis
![Without Y Axis](https://github.com/highfestiva/finplot/assets/66288861/989c5a78-3446-4fac-8a07-05733b0f0ea2)
When trying to view First one or two candles X Axis is gone.

`   
[db.zip](https://github.com/highfestiva/finplot/files/11571168/db.zip)

    import sys
    from PyQt5.QtWidgets import (QApplication,QMainWindow, QDockWidget, QDesktopWidget, QTabWidget, QListWidget)
    from PyQt5.QtCore import Qt    
    import finplot as fplt
    import pandas as pd
    import os
    import pyqtgraph as pg # main graph drawing module
    from pyqtgraph.dockarea import DockArea, Dock
    
    class MTAA(QMainWindow):
    
        def __init__(self):
            super().__init__()
            self.initializeUI()
    
        def initializeUI(self):
            self.setWindowTitle("MTAA 1.00")  # Set Title of Application
    
            # Adjust Screen size to available size
    
            desktop = QDesktopWidget().screenGeometry()
            self.height = desktop.height()
            self.width = desktop.width()
            self.setGeometry(0, 0, self.width, self.height)
            self.setWindowState(Qt.WindowMaximized)  # Set initial state as "Maximised"
    
            self.area = DockArea()
            self.setCentralWidget(self.area)
    
            self.createDockViews()  # create indicator, watchlist, studies Tabbed windows and dock it to mainwindow
            self.show()
    
        def createDockViews(self):
    
            '''
            Dock Window (left) is created and a tab window with needed items viz watchlist, indicators, studies
            are added as its widget.
            '''
    
            # Left Dock Window
            self.DockWindow_Left = QDockWidget()
            self.DockWindow_Left.setAllowedAreas(Qt.LeftDockWidgetArea)
    
            #Creation of tab Items
            self.Tab_Dock_Window = QTabWidget()
            self.Indicator_Tab = QListWidget()
            self.Watchlist_Tab = QListWidget()
            self.Studies_Tab = QListWidget()
    
            self.Tab_Dock_Window.addTab(self.Watchlist_Tab, "Watchlist")
            self.Tab_Dock_Window.addTab(self.Indicator_Tab, "Indicator")
            self.Tab_Dock_Window.addTab(self.Studies_Tab, "Studies")
    
            #setting the widget of dock window and adding it to Main Window
    
            tabwidth = round(self.width/6) #using round function to covert real to int
            self.Tab_Dock_Window.setMaximumWidth(tabwidth)
    
            self.DockWindow_Left.setWidget(self.Tab_Dock_Window)
            self.addDockWidget(Qt.LeftDockWidgetArea, self.DockWindow_Left)
    
            self.Watchlist_Tab.addItems(self.GetDataFileList("BhavData"))
            self.Watchlist_Tab.itemDoubleClicked.connect(self.BhavDoubleClicked)
    
        def BhavDoubleClicked(self, item):
    
            x = self.GetBhavData(item.text())
    
            DockSub = Dock(item.text(),size=(1000,100),closable = True)
            self.area.addDock(DockSub)
    
            chart = fplt.create_plot_widget(master=self.area,rows=1,init_zoom_periods=100)
    
            self.area.axs = [chart]
            DockSub.addWidget(chart.ax_widget)
            self.axs = [chart]
    
            fplt.candlestick_ochl(x[['OPEN','CLOSE','HIGH','LOW']], ax = chart)
    
            fplt.show(qt_exec=False)
    
        def GetDataFileList(self,datatype):
            '''Take Bhav files from db folder'''
            ParentFolder = os.getcwd()
            BhavDataSavePath = os.path.join(ParentFolder, "db")
    
            if datatype == "BhavData":
                FileList = os.listdir(BhavDataSavePath)
    
            return FileList
    
        def GetBhavData(self,SelectedBhavFile):
            '''Read bhav file selected from watchlist Tab'''
            ParentFolder = os.getcwd()
            BhavDataSavePath = os.path.join(ParentFolder, "db", SelectedBhavFile)
    
            return pd.read_csv(BhavDataSavePath, index_col='TIMESTAMP', parse_dates=['TIMESTAMP'])
    
            pass
    
    
    if __name__ == "__main__":
        app = QApplication([])
        window = MTAA()
        sys.exit(app.exec_())`

This is the warning I am getting in my pyCharm terminal window.

C:\Users\Deepu\AppData\Local\Programs\Python\Python39\lib\site-packages\finplot\__init__.py:2708: RuntimeWarning: divide by zero encountered in scalar divide
  dt = (t-t0) / (t1-t0)
C:\Users\Deepu\AppData\Local\Programs\Python\Python39\lib\site-packages\finplot\__init__.py:92: RuntimeWarning: invalid value encountered in scalar multiply
  lerp = lambda t,a,b: t*b+(1-t)*a
Traceback (most recent call last):
  File "C:\Users\Deepu\AppData\Local\Programs\Python\Python39\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 654, in paint
    specs = self.generateDrawSpecs(painter)
  File "C:\Users\Deepu\AppData\Local\Programs\Python\Python39\lib\site-packages\finplot\__init__.py", line 144, in generateDrawSpecs
    specs = super().generateDrawSpecs(p)
  File "C:\Users\Deepu\AppData\Local\Programs\Python\Python39\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 977, in generateDrawSpecs
    tickLevels = self.tickValues(self.range[0], self.range[1], lengthInPixels)
  File "C:\Users\Deepu\AppData\Local\Programs\Python\Python39\lib\site-packages\finplot\__init__.py", line 139, in tickValues
    indices = [ceil(i) for i in rng]
  File "C:\Users\Deepu\AppData\Local\Programs\Python\Python39\lib\site-packages\finplot\__init__.py", line 139, in <listcomp>
    indices = [ceil(i) for i in rng]
ValueError: cannot convert float NaN to integer

and the traceback part gets repeated when ever i try to view the first two candles.

**Comment by highfestiva** [comment]
PyQt version 5 is no longer supported. Please update to v6 and try again.

**Comment by deepspkd** [comment]
I Changed to PyQt 6. But problem still exists.
  
    import sys
    from PyQt6.QtWidgets import (QApplication,QMainWindow, QDockWidget,
    QTabWidget, QListWidget, QWidget)
    from PyQt6.QtCore import Qt    
    import finplot as fplt
    import pandas as pd
    import os
    import pyqtgraph as pg # main graph drawing module
    from pyqtgraph.dockarea import DockArea, Dock
    
    class MTAA(QMainWindow):
    
        def __init__(self):
            super().__init__()
            self.initializeUI()
    
        def initializeUI(self):
            self.setWindowTitle("MTAA 1.00")  # Set Title of Application
    
            # Adjust Screen size to available size
    
            desktop = QWidget().screen().availableGeometry()
            self.height = desktop.height()
            self.width = desktop.width()
            self.setGeometry(0, 0, self.width, self.height)
            self.showMaximized()  # Set initial state as "Maximised"
    
            self.area = DockArea()
            self.setCentralWidget(self.area)
    
            self.createDockViews()  # create indicator, watchlist, studies Tabbed windows and dock it to mainwindow
            self.show()
    
        def createDockViews(self):
    
            '''
            Dock Window (left) is created and a tab window with needed items viz watchlist, indicators, studies
            are added as its widget.
            '''
    
            # Left Dock Window
            self.DockWindow_Left = QDockWidget()
            self.DockWindow_Left.setAllowedAreas(Qt.DockWidgetArea.LeftDockWidgetArea)
    
            #Creation of tab Items
            self.Tab_Dock_Window = QTabWidget()
            self.Indicator_Tab = QListWidget()
            self.Watchlist_Tab = QListWidget()
            self.Studies_Tab = QListWidget()
    
            self.Tab_Dock_Window.addTab(self.Watchlist_Tab, "Watchlist")
            self.Tab_Dock_Window.addTab(self.Indicator_Tab, "Indicator")
            self.Tab_Dock_Window.addTab(self.Studies_Tab, "Studies")
    
            #setting the widget of dock window and adding it to Main Window
    
            tabwidth = round(self.width/6) #using round function to covert real to int
            self.Tab_Dock_Window.setMaximumWidth(tabwidth)
    
            self.DockWindow_Left.setWidget(self.Tab_Dock_Window)
            self.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.DockWindow_Left)
    
            self.Watchlist_Tab.addItems(self.GetDataFileList("BhavData"))
            self.Watchlist_Tab.itemDoubleClicked.connect(self.BhavDoubleClicked)
    
        def BhavDoubleClicked(self, item):
    
            x = self.GetBhavData(item.text())
    
            DockSub = Dock(item.text(),size=(1000,100),closable = True)
            self.area.addDock(DockSub)
    
            chart = fplt.create_plot_widget(master=self.area,rows=1,init_zoom_periods=100)
    
            self.area.axs = [chart]
            DockSub.addWidget(chart.ax_widget)
            self.axs = [chart]
    
            fplt.candlestick_ochl(x[['OPEN','CLOSE','HIGH','LOW']], ax = chart)
    
            fplt.show(qt_exec=False)
    
        def GetDataFileList(self,datatype):
            '''Take Bhav files from db folder'''
            ParentFolder = os.getcwd()
            BhavDataSavePath = os.path.join(ParentFolder, "db")
    
            if datatype == "BhavData":
                FileList = os.listdir(BhavDataSavePath)
    
            return FileList
    
        def GetBhavData(self,SelectedBhavFile):
            '''Read bhav file selected from watchlist Tab'''
            ParentFolder = os.getcwd()
            BhavDataSavePath = os.path.join(ParentFolder, "db", SelectedBhavFile)
    
            return pd.read_csv(BhavDataSavePath, index_col='TIMESTAMP', parse_dates=['TIMESTAMP'])
    
            pass
    
    
    if __name__ == "__main__":
        app = QApplication([])
        window = MTAA()
        sys.exit(app.exec())

![With Y Axis - PyQt6](https://github.com/highfestiva/finplot/assets/66288861/1c191919-dcf2-4513-9610-4068b36aeb4c)
With Y Axis.

![Without Y Axis - PyQt6](https://github.com/highfestiva/finplot/assets/66288861/21a38bab-380f-4b54-94c2-dc498c739b69)
Without Y Axis

[db.zip](https://github.com/highfestiva/finplot/files/11580741/db.zip)

**Comment by highfestiva** [comment]
The error printout `ValueError: cannot convert float NaN to integer` gives a hint. The cause of the problem is that your two first lines in the data file contains the same date, so there is no way to determine the duration between candles.
