### ISSUE TITLE
__version__ field to see installed version of finplot?

### ISSUE THREAD

**Issue by haimivan** [highfestiva/finplot#426]
Hi,

I am very happy to see that finplot is still so good maintained! (y)

I am wondering whether the introduction of a field  `finplot.__version__ = '1.x.y'` would make sense.

Presently I am working with various versions of finplot and that field would make it easier to see which version I have in use (and perhaps it makes sense for others too when looking into bug reports etc.).

Thanks for considering this.

**Comment by highfestiva** [comment]
Good idea, added it in 2a626180a81fd13d20712b67044afbc17f104f21.
