### ISSUE TITLE
timestamp

### ISSUE THREAD

**Issue by Gary-Hertel** [highfestiva/finplot#43]
![image](https://user-images.githubusercontent.com/67775512/94579415-614c8500-02ab-11eb-8257-47479108ec3b.png)
i want timestamp contains hour and minute, instead of date only, my timestamp is like "2020-09-29 15:22:10.784148", why picture didn't show hour and minute ?

**Comment by highfestiva** [comment]
Intresting, could you post a minimal piece of code to illustrate the 
problem?

------ Originalmeddelande ------
Från: "Gary-Hertel" <notifications@github.com>
Till: "highfestiva/finplot" <finplot@noreply.github.com>
Kopia: "Subscribed" <subscribed@noreply.github.com>
Skickat: 2020-09-29 17:29:43
Ämne: [highfestiva/finplot] timestamp (#43)

**Comment by Gary-Hertel** [comment]
`time = []
btc = []
def update():
    equity1 = exchange.get_single_equity(symbol="btc-usdt")
    timestamp = get_utc_time()
    time.append(timestamp)
    btc.append(equity1)
    df2 = pd.DataFrame({"time": time, "btc": btc})
    df2.astype({'time': 'datetime64[ns]'})
    if not plots:
        global ax
    plots.append(fplt.plot(df2, ax=ax, color='#ff66cc', legend="total", zoomscale=True))
    else:
        plots[0].update_data(df2)
plots = []
fplt.foreground = '#FFFFFF'  # 前景色
fplt.background = '#333333'  # 背景色
fplt.odd_plot_background = '#333333'  # 第二层图纸的背景色
fplt.cross_hair_color = "#333333"  # 准星的颜色
ax = fplt.create_plot("asset", init_zoom_periods=100, maximize=True, rows=1)
update()
fplt.timer_callback(update, 60.0)   # 设置自动刷新时间
fplt.show()`

**Comment by Gary-Hertel** [comment]
`import pandas as pd
import finplot as fplt
from purequant.time import *
from purequant.config import config
from purequant.logger import logger
from purequant.trade import OKEXFUTURES

config.loads('config.json')
exchange = OKEXFUTURES(config.access_key, config.secret_key, config.passphrase, "BTC-USDT-201225")

time = []
btc = []
eth = []
trx = []
total = []

def update():
    equity1 = exchange.get_single_equity(symbol="btc-usdt")
    equity2 = exchange.get_single_equity(symbol="eth-usdt")
    equity3 = exchange.get_single_equity(symbol="trx-usdt")
    timestamp = get_utc_time()

    time.append(timestamp)
    btc.append(equity1)
    eth.append(equity2)
    trx.append(equity3)
    total.append(equity1 + equity2 + equity3)

    df1 = pd.DataFrame({"time": time, "total": total})
    df1.astype({'time': 'datetime64[ns]'})
    df2 = pd.DataFrame({"time": time, "btc": btc})
    df2.astype({'time': 'datetime64[ns]'})
    df3 = pd.DataFrame({"time": time, "eth": eth})
    df3.astype({'time': 'datetime64[ns]'})
    df4 = pd.DataFrame({"time": time, "trx": trx})
    df4.astype({'time': 'datetime64[ns]'})

    if not plots:
        global ax, ax2, ax3, ax4
        plots.append(fplt.plot(df1, ax=ax, color='#ff66cc', legend="total", zoomscale=True))
        plots.append(fplt.plot(df2, ax=ax2, color='#ffff33', legend="btc", zoomscale=True))
        plots.append(fplt.plot(df3, ax=ax3, color='#66ffff', legend="eth", zoomscale=True))
        plots.append(fplt.plot(df4, ax=ax4, color='#ff1f8a', legend="trx", zoomscale=True))
    else:
        plots[0].update_data(df1)
        plots[1].update_data(df2)
        plots[2].update_data(df3)
        plots[3].update_data(df4)

try:
    plots = []
    fplt.foreground = '#FFFFFF'  # 前景色
    fplt.background = '#333333'  # 背景色
    fplt.odd_plot_background = '#333333'  # 第二层图纸的背景色
    fplt.cross_hair_color = "#333333"  # 准星的颜色
    ax, ax2, ax3, ax4 = fplt.create_plot("asset", init_zoom_periods=100, maximize=True, rows=4)
    update()
    fplt.timer_callback(update, 60.0)   # 设置自动刷新时间
    fplt.show()
except:
    logger.error()

`

**Comment by highfestiva** [comment]
Exchange package, where do I get that?

**Comment by highfestiva** [comment]
Is there some default passphrase, etc. I can use?

**Comment by highfestiva** [comment]
`$ curl 'https://www.okex.com/v2/spot/instruments/BTC-USDT/candles?granularity=900&size=1000&t=1601394566951'`

yields ms timestamps like so: "2020-09-19T06:00:00.000Z", "2020-09-19T06:15:00.000Z"...

**Comment by Gary-Hertel** [comment]
import pandas as pd
import finplot as fplt
from purequant.time import *
from purequant.config import config
from purequant.logger import logger
from purequant.trade import BITMEX

config.loads('config.json')
exchange = BITMEX("WQ0jZeCNvJiFjr5De-DuDSj8",
                  "gWwwpP26LS071CBstjAQmrnXe0VbjCJhSWAqdCQA1ngax3NH",
                  "XBTUSD",
                  testing=True)

time = []
xbt = []

def update():
    equity = exchange.get_single_equity()
    timestamp = get_utc_time()

    time.append(timestamp)
    xbt.append(equity)

    df = pd.DataFrame({"time": time, "total": xbt})
    df.astype({'time': 'datetime64[ns]'})

    if not plots:
        global ax
        plots.append(fplt.plot(df, ax=ax, color='#ff66cc', legend="xbt"))
    else:
        plots[0].update_data(df)

try:
    plots = []
    fplt.foreground = '#FFFFFF'  # 前景色
    fplt.background = '#333333'  # 背景色
    fplt.odd_plot_background = '#333333'  # 第二层图纸的背景色
    fplt.cross_hair_color = "#333333"  # 准星的颜色
    ax = fplt.create_plot("asset", init_zoom_periods=100, maximize=True, rows=1)
    update()
    fplt.timer_callback(update, 5.0)   # 设置自动刷新时间
    fplt.show()
except:
    logger.error()

**Comment by Gary-Hertel** [comment]
import pandas as pd
import finplot as fplt
from purequant.time import *
from purequant.logger import logger
from purequant.trade import BITMEX

exchange = BITMEX("WQ0jZeCNvJiFjr5De-DuDSj8",
                  "gWwwpP26LS071CBstjAQmrnXe0VbjCJhSWAqdCQA1ngax3NH",
                  "XBTUSD",
                  testing=True)

time = []
xbt = []

def update():
    equity = exchange.get_single_equity()
    timestamp = get_utc_time()

    time.append(timestamp)
    xbt.append(equity)

    df = pd.DataFrame({"time": time, "total": xbt})
    df.astype({'time': 'datetime64[ns]'})

    if not plots:
        global ax
        plots.append(fplt.plot(df, ax=ax, color='#ff66cc', legend="xbt"))
    else:
        plots[0].update_data(df)

try:
    plots = []
    fplt.foreground = '#FFFFFF'  # 前景色
    fplt.background = '#333333'  # 背景色
    fplt.odd_plot_background = '#333333'  # 第二层图纸的背景色
    fplt.cross_hair_color = "#333333"  # 准星的颜色
    ax = fplt.create_plot("asset", init_zoom_periods=100, maximize=True, rows=1)
    update()
    fplt.timer_callback(update, 5.0)   # 设置自动刷新时间
    fplt.show()
except:
    logger.error()

**Comment by Gary-Hertel** [comment]
You can try this code . Thanks a lot !

**Comment by highfestiva** [comment]
You're probably running an old version. Try `pip install -U finplot`.

![image](https://user-images.githubusercontent.com/160303/94584398-da81b300-027e-11eb-96ba-8c208aeeb25d.png)

**Comment by Gary-Hertel** [comment]
Great ! I upgraded finplot, now it's ok ! Thanks ！
