### ISSUE TITLE
Legend text for embed finplot

### ISSUE THREAD

**Issue by Grethold** [highfestiva/finplot#44]
Hi again.
Is it possible add legend with actual index values for "example-embed?
Like here:
`fplt.set_time_inspector(update_legend_text, ax=ax, when='hover')`

![obraz](https://user-images.githubusercontent.com/24272429/94682023-9fd25600-0324-11eb-8146-ca847d531015.png)

but when I try this in embeded project i got this:

> fplt.set_time_inspector(update_legend_text, ax=ax, when='hover')
> File "C:\Users\Marcin\AppData\Roaming\Python\Python37\site-packages\finplot\__init__.py", line 1485, in set_time_inspector
> win.proxy_hover = pg.SignalProxy(win.scene().sigMouseMoved, rateLimit=15, slot=partial(_inspect_pos, ax, inspector))
>
> AttributeError: 'NoneType' object has no attribute 'sigMouseMoved'

Thanks!

**Comment by highfestiva** [comment]
No, that is not supported.

If you go embedded, you need a scene for that. Best is of course to use `finplot.FinWindow`, but if you want to roll your own, you can. You just have to code some yourself.

**Comment by yamen** [comment]
If you roll your own, extend from `pg.GraphicsLayoutWidget` and initialise it is a similar manner to how `FinWindow` is created. Be sure to give it the `axs` property and you should be good to go. The library will recognise a `pg.GraphicsLayoutWidget` as being like a `FinWindow` but with a user managed lifecycle.

**Comment by highfestiva** [comment]
@yamen Can you add a QWidget to a QGraphicsGridLayout which is used in FinWindow somehow?

**Comment by yamen** [comment]
Not that I’m aware of, but FinWindow is itself a widget and can be embedded into a broader application, which I think was the intent of question. For example, this works within example-embed (here it's using FinWindow directly) and you can build a whole application around it.

```pg.mkQApp()
pg.setConfigOptions(foreground=fplt.foreground, background=fplt.background)
finplot = fplt.FinWindow(title="chart")
ax = fplt.create_plot_widget(finplot, init_zoom_periods=100)
finplot.ci.addItem(ax, row=0, col=0)
layout.addWidget(finplot, 1, 0, 1, 2)```

**Comment by highfestiva** [comment]
Wow, that's awesome! Adjusted the embedding example accordingly. Thanks yamen!

@Grethold So the answer is that using yamen's method you can! Pull the latest code and add this to example-embedded.py:

````python
hover_label = fplt.add_legend('', ax=ax)
def update_legend_text(x, y):
    row = df.loc[pd.to_datetime(x, unit='ms')]
    fmt = '<span style="color:#%s">%%.2f</span>' % ('0b0' if (row.Open<row.Close).all() else 'a00')
    rawtxt = '<span style="font-size:13px">%%s</span> &nbsp; O%s C%s H%s L%s' % (fmt, fmt, fmt, fmt)
    hover_label.setText(rawtxt % (symbol, row.Open, row.Close, row.High, row.Low))
fplt.set_time_inspector(update_legend_text, ax=ax, when='hover')
````
![image](https://user-images.githubusercontent.com/160303/94975169-192e9c00-0511-11eb-91d4-8249b9f46f67.png)
