### ISSUE TITLE
[BUG] Process finished with exit code 1 when Import Finplot

### ISSUE THREAD

**Issue by Fr3sto** [highfestiva/finplot#442]
I tried to import finplot but always i get this message
Process finished with exit code 1
Installed finplot by this line
pip install finplot
What should i do to fix this?
I tried to install previous versions but still get this error.

Use Python 3.11.4 on Windows 10

Also installed the library on another computer and got this same error

**Comment by highfestiva** [comment]
See https://github.com/highfestiva/finplot/issues/389
