### ISSUE TITLE
[BUG] Version 1.9.2 set_mouse_callback() AttributeError

### ISSUE THREAD

**Issue by fs-elvis-chuang** [highfestiva/finplot#455]
*OS*: Windows 10
*finplot version*: 1.9.2
*pyqtgraph version*:
*pyqt version*: PyQt6 6.5.3 Qt 6.5.3

In examples
https://github.com/highfestiva/finplot/blob/master/finplot/examples/snp500.py

 fplt.set_mouse_callback(update_legend_text, ax=ax, when='hover')
AttributeError: module 'finplot' has no attribute 'set_mouse_callback'

**Comment by highfestiva** [comment]
It hadn't been released yet. Now version 1.9.3 is out, try `pip install -U finplot`.

**Comment by fs-elvis-chuang** [comment]
Hi highfestiva,

Thank you very much for your assistance. 
The problem has been solved.

Best regards,
