### ISSUE TITLE
[BUG] x-labels has +1 hour than the real data

### ISSUE THREAD

**Issue by alexgiul** [highfestiva/finplot#458]
### Requirements (place an `x` in each of the `[ ]`)**
* [x] I realize finplot is not a web lib. (Hint: it's native!)
* [x] I've read the [snippets](https://github.com/highfestiva/finplot/wiki/Snippets) and not found what I'm looking for.
* [x] I've searched for any related issues and avoided creating a duplicate issue.
* [x] I've updated finplot (`pip install -U finplot`).
* [x] I've supplied the required data to run my code below.

### Code to reproduce

```python
import finplot as fplt
import pandas as pd

fplt.autoviewrestore()
ax = fplt.create_plot('beyond_horizon',init_zoom_periods=100, yscale='log')
ax.showGrid(True, True)

df = pd.read_csv(f'./eurusd.csv', parse_dates=['date'], delimiter=',')
df.index = pd.DatetimeIndex(df['date'])  # convert to datetimeindex

price = df['open close high low'.split()]
ax.reset()  # remove previous plots
fplt.candlestick_ochl(price)

```

### Describe the bug
My last point of data is 2023-11-01 13:17:00,1.0532,1.05324,1.05313,1.05318,130 but when I plot, the data is moved ahead of 1-hour.

[EURUSD.csv](https://github.com/highfestiva/finplot/files/13231614/EURUSD.csv)

### Expected behavior
I should see my last bar at 13:17:00 and not at 14:17:00

#### Screenshots
![finplot_error](https://github.com/highfestiva/finplot/assets/34978052/65392d76-bb4a-4b38-8cea-8a175446e76a)

#### Reproducible in:

*OS*: Windows
*finplot version*: 1.9.2
*pyqtgraph version*: 0.13.3
*pyqt version*:6.4.2

**Comment by highfestiva** [comment]
See https://github.com/highfestiva/finplot/wiki/Snippets#time-zone.
