### ISSUE TITLE
How can I save the plot as png?

### ISSUE THREAD

**Issue by zemus-lab** [highfestiva/finplot#46]
Hi, is it possible to export the plots as png or any other format?

**Comment by highfestiva** [comment]
Yes.

**Comment by zemus-lab** [comment]
Could you please tell me what is the line of code I have to use to save it? Thanks!

**Comment by highfestiva** [comment]
Look at the examples, in this case [https://github.com/highfestiva/finplot/blob/master/finplot/example-line.py](example-line.py) might be suitable.
