### ISSUE TITLE
performance issue, any optimization idea? like threading?

### ISSUE THREAD

**Issue by raptoravis** [highfestiva/finplot#465]
Hi,
I have an app with couple of  tabs, each tab is created with `fplt.create_plot(rows=5)`, each tab has 18 plots. 

it is working and can update lively. but the performance is really not good (UI response is slow, it takes about 2 seconds  to respond when press righ key for example.). the data is about 5 days 1m data, that is about 1650 candles.

when live update, it also has a freeze. the following is the live update snippets:

```
            for plt, df_columns in self.plts:
                plt_df = self.df[df_columns]
                plt.update_data(plt_df, gfx=False)
            for plt, df_columns in self.plts:
                plt.update_gfx()
```

my question is: 
if there are any good practice to speed it up?
I've checked the other issue about the threading, but it seems not good.

btw, it is still quite slow even with just one tab.

thanks

![image](https://github.com/highfestiva/finplot/assets/4395022/f482d622-2e79-420d-9169-5ca2dbd7cf5e)

**Comment by highfestiva** [comment]
Interesting, I would love to get my hands on a small sample that illustrates the low performance. Could you supply one? Just cut out the relevant code and zip with a pinch of data. 1650 candles is nothing, I've used millions. (The thing that uses the most performance is probably line plots anyway.) My guess is there is something else taking a long time, perhaps rendering multiple times due to recursion or something to that effect.

**Comment by raptoravis** [comment]
thanks a lot, I will prepare one for you. 
but it takes some time.

**Comment by highfestiva** [comment]
Hm, hard to tell. .388 seconds to render the update after you press the key is of course a possibility if you have a lot of lines. But if you look at for instance `examples/btc-long-term.py` which shows approximately 5k candles and more than 150 vertical lines, it's pretty obvious that the number of candles should not be a problem during panning.

`examples/analyze.py` shows ~7k candles, as many volume bars, seven plot lines across five axes, fill between, band, legends without stuttering and probably renders in less than .1s.

Do you have different time resolutions on your plots, or do you use some explicit setting? Is any warning printed when you plot?

**Comment by raptoravis** [comment]
```
df = yf.download(symbol, start, interval=interval)
```
it is so weird that the yf.download runs with totally different speed.

in the embed, it is normal but in my code(the 2nd slow case), it runs 10 times slower!

**Comment by raptoravis** [comment]
finally, I found the cause which is a thread which is 100% busy! that is beyond my imagination that one thread slow down all the processing so severely!

anyway thanks a lot. the finplot is really so brilliant!
