### ISSUE TITLE
calc_period_ns returns a wrong value for data there are gaps

### ISSUE THREAD

**Issue by raptoravis** [highfestiva/finplot#466]
in `HorizontalTimeVolumeItem.generate_picture`,
```
f = self.datasrc.calc_period_ns(n=1000, delta=lambda dt:int(dt.mean())) / _get_datasrc(self.ax).calc_period_ns(n=1000, delta=lambda dt:int(dt.mean()))

```
`_get_datasrc(self.ax).calc_period_ns(n=1000, delta=lambda dt:int(dt.mean()))` returns a wrong value.

my test data is the 1m data, for ex. data is from 11.1 to 11.5, it closes at the 16:00 and opens at 9:30 on the next day, so there is a gap of couple of hours, so `_get_datasrc(self.ax).calc_period_ns(n=1000, delta=lambda dt:int(dt.mean()))` returns a wrong value.

of course there are some dirty fixes, but is there some perfect fix to this?

**Comment by highfestiva** [comment]
Yes, I haven't given closing markets much love when it comes to horizontal time volumes. Could you please create some miniature test for me, or simply try removing the `delta=` arguments for both calls, to see if that might help?

**Comment by raptoravis** [comment]
I made a fix https://github.com/highfestiva/finplot/pull/467
it seems perfect for volume_profile.py and my tests.
and, I also added some configuration to it.

**Comment by highfestiva** [comment]
See here for more info: https://github.com/highfestiva/finplot/pull/467#issuecomment-1839067321

**Comment by raptoravis** [comment]
I have seen the update, perfect!
