### ISSUE TITLE
Datetime format at the X-Axes

### ISSUE THREAD

**Issue by Protomolekule** [highfestiva/finplot#468]
I would like to change the x-axes from my df to another format. Unfortunally I run into several problems and could not find any working solution. I've tried it by
    df['Date'] = df.index.strftime ('%d.%m.%Y %H:%M')
    df = df.set_index ('Date')

Another trial is:
    df.index = df.index.strftime ('%d.%m.%Y %H:%M')

Both end up in errors like:
  File "C:\DATEN\workshop\development\python\Trading_6\venv\lib\site-packages\finplot\__init__.py", line 254, in __init__
    if type(df.index) == pd.DatetimeIndex or df.index[-1]>1e8 or '.RangeIndex' not in str(type(df.index)):
TypeError: '>' not supported between instances of 'str' and 'float'

The dataframe format is:
                       Open    High     Low   Close  Volume
Date                                                       
2023-09-06 14:00:00  563.50  563.50  561.00  561.00      23
2023-09-06 15:00:00  562.00  564.06  558.60  562.46    1577
2023-09-06 16:00:00  562.16  562.48  558.13  558.13    2034
2023-09-06 17:00:00  558.12  560.36  555.85  559.58    2169
2023-09-06 18:00:00  559.40  560.37  556.24  558.36     991
...                     ...     ...     ...     ...     ...

df.info()
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 866 entries, 2023-09-06 14:00:00 to 2023-12-04 15:00:00
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Open    866 non-null    float64
 1   High    866 non-null    float64
 2   Low     866 non-null    float64
 3   Close   866 non-null    float64
 4   Volume  866 non-null    int64  
dtypes: float64(4), int64(1)

How to change the format and keep the index upright?
Thanks in advance

**Comment by Protomolekule** [comment]
Dear  highfestiva,

Thanks for the fast response. It's working :-), thanks. Just give me a
yes or no. I just replaced that finplot/__init__.py you sent  in
4bff640 [1] with the existing one. I'm ásking because I'm not familar
with github and the procedures to include patches.

Regards

--- Original Nachricht ---
Betreff: Re: [highfestiva/finplot] Datetime format at the X-Axes
(Issue #468)
Von: "highfestiva" 
An: "highfestiva/finplot" 
CC: "Protomolekule" , "Author" 
Datum: 04.12.2023 16:22












Good question, hadn't thought of that. Added easy support for it in
4bff640 [1].



Generally the output X-axis format is a _function_ of the input data,
as it has to do with presentation (think of it like syntax vs.
semantics). What you instead would have wanted to do is to change the
_X-axis presentation_ (not the input data).



—
Reply to this email directly, view it on GitHub [2], or unsubscribe
[3].
You are receiving this because you authored the thread.Message ID: 





Links:
------
[1]
https://github.com/highfestiva/finplot/commit/4bff640e2dd24e92f9245d17c5c8ea99ed10ca55
[2]
https://github.com/highfestiva/finplot/issues/468#issuecomment-1838871805
[3]

**Comment by highfestiva** [comment]
Sure, that will work. Whenever I release a new version, "your" change will be included and then you'll just do `pip install -U finplot` to install the other changes that I'll add later.
