### ISSUE TITLE
a dummy item needs to be added at the end for volume profile plotting

### ISSUE THREAD

**Issue by raptoravis** [highfestiva/finplot#469]
```
       tvp, all_bins = calc_volume_profile(
            df, period=period, col_volume=col_volume, bins=self.all_bins
        )

        te = df.index[-1]
        tvp.append([te, [tvp[-1][1][0]]])
```

like the code above, a dummy item needs to be added at the end for volume profile plotting to mark the ending time so that the last part can have a correct range.

the weekly volume profile:
![image](https://github.com/highfestiva/finplot/assets/4395022/4c0b4821-40a5-4ec9-bf67-c8ece169181b)

```
       vp_p = cal_vp_period(last_df, col_volume=col_volume, all_bins=self.all_bins)
        vwap_p = calc_vwap_period(last_df, col_volume=col_volume)

        te = last_df.index[-1]
        vp_p_t = [vp_p, [te, [vp_p[1][0]]]]

```

the flexible volume profile which can start flexiablely till the end:
![image](https://github.com/highfestiva/finplot/assets/4395022/82059ec6-d4c2-4dc9-a75a-56bb8bce3ee5)

**Comment by highfestiva** [comment]
I think that's fixed in the last commit, 97b35fd91584b4707bfc49dedf3f9e3e5d19df2e. Please check if you're still getting this problem using that.

**Comment by raptoravis** [comment]
I had already integrated this commit #97b35fd

my local fix is to makre sure the last "period" has an ending date so that the plotting knows where to stop plotting. otherwise it would crash or a wrong ending.
```
te = last_df.index[-1]
vp_p_t = [vp_p, [te, [vp_p[1][0]]]]

```

**Comment by raptoravis** [comment]
look the difference: the last part with the red outline, if there were no the dummy end marker, the last one DOES NOT konw where to end. I just added that dummy one to make it look correct but I am not sure if there is a better solution to it.

![image](https://github.com/highfestiva/finplot/assets/4395022/774fcad2-952d-443f-83ec-a692b172371b)

![image](https://github.com/highfestiva/finplot/assets/4395022/2f46f039-389e-41aa-bcc4-98db6046e896)

**Comment by highfestiva** [comment]
It's currently doing N periods after the given start date. I don't know if this is correct (i.e. you should move the start date) or incorrect (i.e. I should make the last part less wide). Can you enlighten me?

**Comment by raptoravis** [comment]
and, yes, "it works perfectly," only with my personal case. so I will just close this issue. 

thanks, i will try to use add_text sometime later.
