### ISSUE TITLE
Wrong variable format in update_y_zoom

### ISSUE THREAD

**Issue by Protomolekule** [highfestiva/finplot#476]
### Requirements (place an `x` in each of the `[ ]`)**
* [x ] I realize finplot is not a web lib. (Hint: it's native!)
* [x ] I've read the [snippets](https://github.com/highfestiva/finplot/wiki/Snippets) and not found what I'm looking for.
* [x ] I've searched for any related issues and avoided creating a duplicate issue.
* [x ] I've updated finplot (`pip install -U finplot`).
* [ x] I've supplied the required data to run my code below.

### Code to reproduce
```
def finplot_update( wid, df,title="Its me"):
    if len (df) < 20:  # symbol does not exist
        return
    axes = wid.axs
    if len (axes) == 0:
        print("No Valid finplot")
        return
    # finplot_info.setText("Loading symbol name...")
    price = df["Open Close High Low".split ()]
    ma20 = df.Close.rolling (20).mean ()
    ma50 = df.Close.rolling (50).mean ()
    ma200 = df.Close.rolling (200).mean ()
    volume = df["Open Close Volume".split ()]
    for ax in axes:
        ax.reset ()  # remove previous plots
    fplt.candlestick_ochl (price, ax=axes[0])
    fplt.plot (ma200, legend="MA-200", ax=axes[0])
    fplt.volume_ocv (volume, ax=axes[1])
    fplt.refresh ()  # refresh autoscaling when all plots complete
    fplt.add_legend(title, ax=axes[0] )

```

### Describe the bug
I did several adaption of the snippets to get a combined volume/candle graph as a widget to add in my programm. It's working but when I zoom in with the mouse it crashes. I'm not totally sure if this is a real bug or missprogramming, but every trial leeds to the same result... I've found that there are different variable types. 

The dataframe is:
                            Open   High    Low  Close  Volume
Date                                                         
2023-08-21 09:00:00-04:00  13.01  13.01  12.74  12.82   41827
2023-08-21 10:00:00-04:00  12.82  12.99  12.72  12.91  118616
2023-08-21 11:00:00-04:00  12.89  12.96  12.79  12.85   43334
2023-08-21 12:00:00-04:00  12.86  13.11  12.85  13.04   32121
2023-08-21 13:00:00-04:00  13.04  13.11  13.01  13.03   21144
...                          ...    ...    ...    ...     ...
2023-12-18 15:00:00-05:00  10.68  10.76  10.64  10.65   93218
2023-12-18 16:00:00-05:00  10.66  10.70  10.65  10.70   68988
2023-12-18 17:00:00-05:00  10.70  10.70  10.70  10.70       0
2023-12-18 18:00:00-05:00  10.75  10.75  10.75  10.75    1350
2023-12-18 19:00:00-05:00  10.77  10.86  10.77  10.86    2900
[949 rows x 5 columns]

df.info()
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 949 entries, 2023-08-21 09:00:00-04:00 to 2023-12-18 19:00:00-05:00
Data columns (total 5 columns):
 _    Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Open    949 non-null    float64
 1   High    949 non-null    float64
 2   Low     949 non-null    float64
 3   Close   949 non-null    float64
 4   Volume  949 non-null    object 
dtypes: float64(4), object(1)
memory usage: 44.5+ KB

While zooming in I got error message, related to data type
hi,lo: <class 'numpy.float64'> <class 'numpy.float64'> 20.83 4.91
self.v_zoom_scale: <class 'float'> 0.97
hi,lo: <class 'numpy.float64'> <class 'numpy.float64'> 7.16 6.83
self.v_zoom_scale: <class 'float'> 0.97
hi,lo: <class 'numpy.float64'> <class 'numpy.float64'> 8.15 8.15
self.v_zoom_scale: <class 'float'> 0.97
hi,lo: <class 'numpy.float64'> <class 'numpy.float64'> 8.15 8.15
self.v_zoom_scale: <class 'float'> 0.97
hi,lo: <class 'decimal.Decimal'> <class 'numpy.int64'> 120 0                                   <-  here is the format wrong
self.v_zoom_scale: <class 'float'> 0.97
Traceback (most recent call last):
  File "C:\venv\lib\site-packages\pyqtgraph\graphicsItems\ViewBox\ViewBox.py", line 1055, in linkedXChanged
    self.linkedViewChanged(view, ViewBox.XAxis)
  File "C:\venv\lib\site-packages\finplot\__init__.py", line 1016, in linkedViewChanged
    self.update_y_zoom(vr.left(), vr.right())
  File "C:\venv\lib\site-packages\finplot\__init__.py", line 1108, in update_y_zoom
    rng = (hi-lo) / self.v_zoom_scale
TypeError: unsupported operand type(s) for /: 'decimal.Decimal' and 'float'

I've tried to set the hi, lo as float(hi)... , but then it hangs on other positions

### Expected behavior
Zooming the scale to see more candles

#### Reproducible in:

*OS*: Windows
*finplot version*: 1.93
*pyqtgraph version*: 0.13.3
*pyqt version*: 6.61 (6.6.0 same issue)

**Comment by highfestiva** [comment]
Ah, this is caused by the data in your matrix is of type `decimal.Decimal` instead of `float`. I guess it depends on how you load your data. How do you load your data, and from what format?

**Comment by Protomolekule** [comment]
This can be closed. It seems that yFinance has other format detailst than tws. Still have a problem with candles, which are shown in without color.

**Comment by highfestiva** [comment]
There are plenty of finplot examples displaying colored candles.
