### ISSUE TITLE
Remove_line in embed finplot

### ISSUE THREAD

**Issue by Grethold** [highfestiva/finplot#49]
Hi again and thanks for the last help.
Now i have problem with remove_line in embed finplot.

First I tried add and delete line as following:
`up = fplt.add_line((df["START"].iloc[i],df['up'].iloc[i] ), (df["STOPpos"].iloc[i], df3['up'].iloc[i]), color='#ffffff', interactive=False, ax = ax)`
`fplt.remove_line(up)`
but it doesn't work.

Next I tried this:
`plots.append(fplt.add_line((df["START"].iloc[i],df['up'].iloc[i] ), (df["STOPpos"].iloc[i], df3['up'].iloc[i]), color='#ffffff', interactive=False, ax = ax))`
and delete:
`fplt.remove_line(plots[2])`

but the lines don't remove.
My code is similar (more advanced) like this:
```
...
plots = []
def update(txt):
    df = download(txt)
    df2 = test(df)
    if len(df) < 20: # symbol does not exist
        return
    price = df['Open Close High Low'.split()]
    volume = df['Open Close Volume'.split()]
    if not plots:
        plots.append(fplt.candlestick_ochl(price))
        plots.append(fplt.volume_ocv(volume, ax=ax.overlay()))
        for i in range(0,df2.shape[0]):
          if df2['STOP'].iloc[i] != 0:
            plots.append(fplt.add_line((df2["START"].iloc[i],df2['up'].iloc[i] ), (df2["STOP"].iloc[i], df2['up'].iloc[i]), color='#000000', interactive=False, ax = ax))
    else:
        plots[0].update_data(price)
        plots[1].update_data(volume)
        length = len(plots)
        for i in range(2,length-1):
          fplt.remove_line(plots[i])
          #del plots[i]
        if line.isChecked():
          for i in range(0,df2.shape[0]):
            if df2['STOP'].iloc[i] != 0:
              plots.append(fplt.add_line((df2["START"].iloc[i],df2['up'].iloc[i] ), (df2["STOP"].iloc[i], df2['up'].iloc[i]), color='#000000', interactive=False, ax = ax))
...
```

What am I doing wrong?
Thanks for help!

**Comment by highfestiva** [comment]
If you look at example-line.py, that seems to work when uncommenting the remove_line() call. I can't see anything obvious in your code. Could you reduce the code preproducing the bug to a minimal example and post here?

**Comment by Grethold** [comment]
Ok. After few tests, it's work. Sorry for the problem.
