### ISSUE TITLE
[BUG] hours in crosshair missing

### ISSUE THREAD

**Issue by Protomolekule** [highfestiva/finplot#493]
### Requirements (place an `x` in each of the `[ ]`)**
* [x ] I realize finplot is not a web lib. (Hint: it's native!)
* [ x] I've read the [snippets](https://github.com/highfestiva/finplot/wiki/Snippets) and not found what I'm looking for.
* [ x] I've searched for any related issues and avoided creating a duplicate issue.
* [ x] I've updated finplot (`pip install -U finplot`).
* [ ] I've supplied the required data to run my code below.

### Describe the bug
The setting of `fplt.timestamp_format = '%d.%m.%y\n%H:%M'` does not work. The minutes are not displayed in the crosshair as expected. 

### Expected behavior
I've changed the fplt.timestamp_format in different ways, but the minutes are always suppressed, but exist. The hours will be displayed.

#### Screenshots
![grafik](https://github.com/highfestiva/finplot/assets/23557320/ad836010-ab17-4787-bd5f-bc5746b89dfa)

#### Reproducible in:

*OS win 11:
*finplot version 1.93:
*pyqtgraph version 0.13.3*:
*pyqt version 6.6*:

**Comment by highfestiva** [comment]
I'm presuming this is due to you you using 1h-resolution data? I added a setting you can use to skip timestamp truncation in 80666b8, check it out.

**Comment by Protomolekule** [comment]
Thanks a lot. Is working now
