### ISSUE TITLE
Question about fplt.plot()

### ISSUE THREAD

**Issue by lzlgboy** [highfestiva/finplot#50]
Thanks for creating this great work. It is very powerful compare to other plot libs. 
When I plot using fplt.plot(df['timestamp', df['MyIndicator']], the x axis display timestamp value instead of display datetime format. Ideally I also want to print H:M:S format instead of YY/MM/DD/ format. How can I do that? 

Best regards,
Ken

![image](https://user-images.githubusercontent.com/8021712/95676877-08bc9800-0b87-11eb-9323-fe59f67692a8.png)

**Comment by highfestiva** [comment]
Could you post a minimal example of code+data so I can reproduce this?

**Comment by lzlgboy** [comment]
Thanks for help. It is strange that when I run the code the other day, it is working, so I am not sure whether theres is problem in the input file. But still, is there a way to set format through fplot.plot() function to customize time display format? Such as H:M:S format instead of YY/MM/DD/ format, if I just display realtime data.

The code is borrowed from the example-bfx.py with modifications, the 'timestamp' is a format like : 1602172653135
====CODE=====
def PlotMass(symbol,Mass_Listed:dict,idx_Listed:int):

    def update():
    # load data
        index = idx_Listed
        df = pd.DataFrame(Mass_Listed[symbol][0:index]['timestamp'],copy=False)
        df.columns = ['timestamp']
        df['timestamp'] = df['timestamp'] / 1000.0
        df['M_dn'] = pd.DataFrame(Mass_Listed[symbol][0:index]['MassDown'],copy=False)
        df['M_up'] = pd.DataFrame(Mass_Listed[symbol][0:index]['MassUp'],copy=False)

        df['mw_M_up'] = df['M_up'].rolling(window=period,min_periods=0).mean()
        df['mw_M_dn'] = df['M_dn'].rolling(window=period,min_periods=0).mean()

        # pick columns for our three data sources: candlesticks and TD sequencial labels for up/down
        if not plots:
            # first time we create the plots
            global ax
            plots.append(fplt.plot(df.timestamp,df.mw_M_dn, legend='MassDown',color='#00FF00'))
            plots.append(fplt.plot(df['timestamp'],df['mw_M_up'], legend='MassUp',color='#FF0000'))
        else:
            # every time after we just update the data sources on each plot
            plots[0].update_data(df)
            plots[1].update_data(df)

    plots = []
    ax = fplt.create_plot('Mass', init_zoom_periods=10000, maximize=False)
    update()
    fplt.timer_callback(update, 1.0) # update (using synchronous rest call) every N seconds
    fplt.show()

**Comment by highfestiva** [comment]
Need to see your data to know what's wrong. Is it unordered?

This example replaces the default bottom axis and shows only time in the crosshair:

````python
#!/usr/bin/env python3


import finplot as fplt
import numpy as np
import pandas as pd


# 1. replace default axis with your own
def my_timestamp_str(df, row):
    row = max(0, min(len(df)-1, int(row))) # clamp
    col = 0 # or 'timestamp' or whatever is your datetime column name
    s = str(pd.to_datetime(df.loc[row, col], unit='ms'))
    return s.partition(' ')[2].partition('.')[0] # only time without milliseconds

class MyAxis(fplt.EpochAxisItem):
    def tickStrings(self, values, scale, spacing):
        return [my_timestamp_str(self.vb.datasrc.df, value) for value in values]

ax = fplt.create_plot()
ax.setAxisItems({'bottom': MyAxis(vb=ax.vb, orientation='bottom')})

# 2. plot something
timestamp = np.linspace(1_602_172_653_135, 1_602_173_653_135, 500)
y = np.random.random(len(timestamp))
fplt.plot(timestamp, y, ax=ax)

# 3. fix the crosshair X text too
def update_crosshair_text(x, y, xtext, ytext):
    return xtext.partition(' ')[2], ytext
fplt.add_crosshair_info(update_crosshair_text)

fplt.show()
````

Normally that should not be necessary to get a proper date though. And you don't have to divide your timestamp by 1,000, as you can see in this example.

**Comment by highfestiva** [comment]
@lzlgboy I just did an update which may or may not fix your timestamp problems. Try out https://github.com/highfestiva/finplot/commit/5bb833277e70357349db3a61366a9ff306d1e55c to see if it works. If not I need a snippet of your data to resolve the issue.

**Comment by highfestiva** [comment]
@lzlgboy I think your timestamp data is unordered. Sort it first, and timestamps should work just fine.

**Comment by lzlgboy** [comment]
That is great! You are definitely right. Some part of the real time data mixed, after sorting, no prolem. Thanks very much for the hard work~
