### ISSUE TITLE
log scale blows up on large numbers?

### ISSUE THREAD

**Issue by jabowery** [highfestiva/finplot#51]
Find the attached .py and .csv files zipped together which produced this graph:

![finplotbug](https://user-images.githubusercontent.com/57646/95817865-2a816080-0ce8-11eb-915d-5d2f1c90d535.png)

I expected the vertical scale to be appropriate to the maximum value in the .csv.  If you divide that dataframe by 10 the bug goes away.

[finplotylogscalebug.zip](https://github.com/highfestiva/finplot/files/5369036/finplotylogscalebug.zip)

**Comment by highfestiva** [comment]
Thanks for the reproducible example, problem solved in commit 069aea5.

**Comment by jabowery** [comment]
Thanks for the timely workaround.
