### ISSUE TITLE
X Axes not updates after resize

### ISSUE THREAD

**Issue by Protomolekule** [highfestiva/finplot#517]
I'm using the following function to set the X-axes. But the plot won't be updated. Taken from the example [examples/animate.py](https://github.com/highfestiva/finplot/blob/master/finplot/examples/animate.py). 

```
 def setDateRange(self, start=None, end=None):
        '''start / end is string = index '''
        iend = self.dfcandles.index.get_loc (self.dfcandles.index[-1])
        if start == 'MAX':
            istart = self.dfcandles.index[0]
        else:
            istart = self.dfcandles.index.get_loc (start)

        fplt.set_x_pos (istart, iend, ax=self.ax_a)
        fplt.set_x_pos (istart, iend, ax=self.ax_b)


```
If I change the size of `self.dfcandles`  and use 
```
        self.fp1.update_data (self.dfcandles)
        self.fp2.update_data (self.dfcandles[['Open', 'Close', 'Volume']])

```
 it will be updated. But I don't think thats the correct way. The plots are created inside a `QWidget` Class using 
```
        # create the plot widget
        self.ax_a, self.ax_b = fplt.create_plot_widget (self, rows=2)


```

What am I missing? Can't find a solution...

**Comment by highfestiva** [comment]
You are using the _zero-based index_ of your index instead of the _value_ of your index. Instead do:

```python3
iend = self.dfcandles.index[-1]
if start == 'MAX':
    istart = self.dfcandles.index[0]
else:
    istart = self.dfcandles.index[start]
```

**Comment by Protomolekule** [comment]
Hm, thanks for your quick answer.

In the example there you use  `type(df.index[int(x-w)])
<class 'numpy.float64'>`

If I change the format with `istart = np.float64(istart.timestamp())` I get a float which looks like in the example. But the range stays in old values. I've tried different methods to end up with a float64, but still no adjustment. 

Nethertheless you took me to the right direction. I've used  `fplt.refresh ()` in another function which runs after the range settings. Deleted it and now I get the correct range. 👍 

So, please can you tell me when to use  `fplt.refresh ()` and  `fplt.update()`? It seems I'm mixing up something.

**Comment by highfestiva** [comment]
`refresh()` restores any saved range positions, resets the Y-zoom, moves the crosshair to the mouse position and so forth — for all axes in all windows.

There are a half-dozen update functions in the module, so hard to tell what you're asking there. If you're referring to `plot.update_data()`, it modifies the data on a plot, optionally also updating the graphics (which is default).

**Comment by Protomolekule** [comment]
Thanks, makes the finplot world a little bit clearer to me :-)
