### ISSUE TITLE
setRowStretchFactor doesnt work

### ISSUE THREAD

**Issue by baabeetaa** [highfestiva/finplot#529]
i tried https://github.com/highfestiva/finplot/issues/56 and it doesnt work
is there a way to set height for each each row? I'd like to set the primary one to much larger.

**Comment by highfestiva** [comment]
Yeah, I had to rework that to make it work properly, and changed the layout in the process. This is how you set the height now:

```python
fplt.axis_height_factor[0] = 5 # the first plot will take five height units (one is default)
fplt.axis_height_factor[1] = 2 # the second plot will take two height units

fplt.plot(...)
fplt.show()
```

**Comment by baabeetaa** [comment]
great! it works. thank you.
