### ISSUE TITLE
finplot install issue

### ISSUE THREAD

**Issue by mindougas** [highfestiva/finplot#53]
Hello, could you please change the installation requirement for PyQt5, to be rather as below, because in my case it complains about it if its like this 'PyQt5==5.13.0', for some reason its not able to install this specific version. Thanks!
install_requires=['pandas>=0.23.4', 'PyQt5>=5.13.0', 'pyqtgraph>=0.10.0']

**Comment by highfestiva** [comment]
Hi! Can’t do that unfortunately as there’s a bug in newer Qt. I’ll investigate at some point as it’s not sustainable to cling on to legacy versions.

Skickat från min iPhone

**Comment by highfestiva** [comment]
This is caused by a bug in pyqtgraph, https://github.com/pyqtgraph/pyqtgraph/issues/1057, which is really a bug in pyqt5, which is really a bug in Qt.

**Comment by aladdin-hub** [comment]
I have the same version mismatch: I use Spyder 4.1.5, that require pyqt5 5.12, but finplot requires pyqt5.13

So, there is no solution for spyder?

**Comment by highfestiva** [comment]
Unfortunately I think the only thing you can do is try to force-install non-matching versions and hope for the best until the new version of pyqtgraph is released. finplot wants pyqt 5.9 or 5.13, so you could try those. There is only [one holdup](https://github.com/pyqtgraph/pyqtgraph/pull/1406) for pyqtgraph's release afaik, you could always try to help there.

**Comment by aladdin-hub** [comment]
> 
> 
> Unfortunately I think the only thing you can do is try to force-install non-matching versions and hope for the best until the new version of pyqtgraph is released. finplot wants pyqt 5.9 or 5.13, so you could try those. There is only [one holdup](https://github.com/pyqtgraph/pyqtgraph/pull/1406) for pyqtgraph's release afaik, you could always try to help there.
> 
> _Edit:_ One hackish, but working, possibility is to clone the most recent pyqtgraph and copy that into your site-packages. Then force-install latest finplot. Works for me in py39.

well, as I'm a newbie, it's hard for me to do what you proposed. If you give me some links on how to do this, I'll be much appreciated! 

For now, I just did the non-recommended thing - I installed conflicting versions to different environments: conda and pip. It's work for now, but I think some issues might be.

**Comment by highfestiva** [comment]
@mindougas @aladdin-hub The new release, finplot v1.5, uses the most recent pyqtgraph 0.11.1, which supports the latest PyQt. Update like so:

````bash
pip install --upgrade finplot
````
