### ISSUE TITLE
The official tutorial provided by QLineEdit to block the input method suggests using `setAttribute`, but it is ineffective. Please provide a solution.

### ISSUE THREAD

**Issue by jszhrm** [highfestiva/finplot#535]
The official tutorial provided by QLineEdit to block the input method suggests using `setAttribute`, but it is ineffective. Please provide a solution.

**Comment by highfestiva** [comment]
No tutorial is provided by QLineEdit. Nor is there any code referencing QLineEdit within pyqt. No, I will certainly not.

**Comment by jszhrm** [comment]
Here is the translation of the text you provided:

**Bug Title:** Input Method Disablement Setting Ineffective  
**System Environment:** Windows 10  
**Python Version:** 3.12.4  
**Qt Version:** PySide6 v6.8.01  
**Bug Description:** The function to disable Asian input methods for `QLineEdit` (`QLineEdit.setAttribute(Qt.WidgetAttribute.WA_InputMethodEnabled, False)`) does not work. The only method that achieves a similar effect within this control is `QLineEdit.setEchoMode(QLineEdit.EchoMode.Password)`, but this sets the control to password mode. The same setting (disabling input methods) works in PyQt5 v5.15.11.  
**Sample Code:**

```python
from PySide6.QtWidgets import QLineEdit, QVBoxLayout, QWidget, QApplication
from PySide6.QtCore import Qt

class TestWindow(QWidget):
    def __init__(self):
        super().__init__()
        self.initUI()

    def initUI(self):
        layout = QVBoxLayout(self)

        self.line_edit = QLineEdit(self)
        self.line_edit.setAttribute(Qt.WidgetAttribute.WA_InputMethodEnabled, False)
        layout.addWidget(self.line_edit)
        
        self.line_pswd = QLineEdit(self)
        self.line_pswd.setEchoMode(QLineEdit.EchoMode.Password)
        layout.addWidget(self.line_pswd)
        
        self.setWindowTitle('Test Window')
        self.setGeometry(300, 300, 300, 50)

if __name__ == '__main__':
    app = QApplication()
    window = TestWindow()
    window.show()
    app.exec()
```

Let me know if you need further adjustments!
