### ISSUE TITLE
Hover to select overlay

### ISSUE THREAD

**Issue by jabowery** [highfestiva/finplot#54]
Enhancement request related to [secondary Y-axis](https://github.com/highfestiva/finplot/issues/52):

Multiple overlayed graphs with varying Y-axes might be handled if a mouse-over hover of a given graph's line brought up the corresponding scale on the left side and its label up in the upper left hand corner.

**Comment by highfestiva** [comment]
While it might sound like a nice feature for some to have, feature creep comes to mind: thickening/highlighting the line and rendering it in front of the other ones. Some might want clicks, others hover, some want to select in the legend, others on the line itself, and perhaps a majority on both. Some might find it confusing if scale suddenly changes when hovering.

It's also fairly easy to implement oneself, as pyqtgraph support hover, click, etc.

But foremost this is not a feature that most people that do backtesting need. Therefore I will have to decline.
