### ISSUE TITLE
can each viewbox's size be scaled?

### ISSUE THREAD

**Issue by oxful** [highfestiva/finplot#56]

**Comment by highfestiva** [comment]
Yes, but you have to dig into the intestines of finplot.

````python
#!/usr/bin/env python3

import finplot as fplt
import numpy as np

fplt.odd_plot_background = '#555'
ax1,ax2,ax3 = fplt.create_plot(rows=3)

# set scale
fplt.windows[0].ci.layout.setRowStretchFactor(0, 1)
fplt.windows[0].ci.layout.setRowStretchFactor(1, 2)
fplt.windows[0].ci.layout.setRowStretchFactor(2, 3)

fplt.plot(np.linspace(1600000000, 1600000100, 500), np.random.random(500), ax=ax1)
fplt.plot(np.linspace(1600000000, 1600000100, 500), np.random.random(500), ax=ax2)
fplt.plot(np.linspace(1600000000, 1600000100, 500), np.random.random(500), ax=ax3)
fplt.show()
````

![image](https://user-images.githubusercontent.com/160303/96873104-c93e5780-1474-11eb-846b-69647aece0db.png)

**Comment by Grethold** [comment]
The same is possible with example-embed?

```ax, ax2 = fplt.create_plot_widget(win, rows=2)
win.axs = [ax,ax2] # finplot requres this property
layout.addWidget(ax.ax_widget, 1, 0, 1, 2)
layout.addWidget(ax2.ax_widget, 2, 0, 1, 2)
```



![Zrzut ekranu 2020-10-23 134750](https://user-images.githubusercontent.com/24272429/96999966-5bf2fb00-1536-11eb-9649-f867ca4a8316.png)

**Comment by highfestiva** [comment]
Yes, but that's not part of finplot, you have to use pyqt5 to do that. 
(Try switching the next-to-last 1 into a 3, and possibly there'll be 
something going on.)

KR Jonte

------ Originalmeddelande ------
Från: "Hans Christian Andersen" <notifications@github.com>
Till: "highfestiva/finplot" <finplot@noreply.github.com>
Kopia: "Jonas Byström" <highfestiva@gmail.com>; "Comment" 
<comment@noreply.github.com>
Skickat: 2020-10-23 13:48:30
Ämne: Re: [highfestiva/finplot] can each viewbox's size be scaled? (#56)

**Comment by oxful** [comment]
thankyou so much , i'll try it later

**Comment by oxful** [comment]
by the way , finplot is very very great
