### ISSUE TITLE
Non filled circle

### ISSUE THREAD

**Issue by Grethold** [highfestiva/finplot#57]
Hi!
Is it possible to make an unfilled circle like this?
![obraz](https://user-images.githubusercontent.com/24272429/96891655-2a702600-1489-11eb-9bef-3f6f68b8d844.png)
Thanks!

**Comment by highfestiva** [comment]
Manually: Ctrl+MMButton-drag. To do it programatically you have to jump through hoops:
````python
	pos = fplt.pg.Point(100, 80)
	size = fplt.pg.Point(10,10)
	pen = fplt.pg.mkPen('#c95')
	ellipse = fplt.pg.EllipseROI(pos, size, pen=pen, movable=False)
	ax.vb.addItem(ellipse)
````

**Comment by Grethold** [comment]
It works perfectly, thank you!
![obraz](https://user-images.githubusercontent.com/24272429/96928108-62429200-14b8-11eb-9fe6-9feb6ee3b1c1.png)

**Comment by Grethold** [comment]
Is it possible to delete this item?

**Comment by highfestiva** [comment]
Did you try `ax.vb.removeItem(ellipse)`?
