### ISSUE TITLE
Incorrect timezone used

### ISSUE THREAD

**Issue by jabowery** [highfestiva/finplot#59]
Find the attached code.

`finplot` shows:
![finplotwrongtimezone](https://user-images.githubusercontent.com/57646/97098690-0c9fee00-164e-11eb-8a44-bbf34ee3d7d0.png)
`matplotlib` shows:
![matplotlibrighttimezone](https://user-images.githubusercontent.com/57646/97098699-1de8fa80-164e-11eb-82a3-7b41e1111dfb.png)

My local timezone is US Central.  Although the times are drawn from stock market quotes in US Eastern time, the resulting .csv's datetimes contain no timezone so I would have expected it to (in order of expectation):

* use the times as they stand as does matplotlib
* use US Central time and interpret the times in the .csv as UTC

But it seems to do neither.

[finplottimezonebug.zip](https://github.com/highfestiva/finplot/files/5434161/finplottimezonebug.zip)

**Comment by highfestiva** [comment]
It does what you expect in your second assumption: 2020-09-30T15:24:00Z is 2020-09-30T10:24:00 CDT.

**Comment by jabowery** [comment]
Ah, ok.  I made a mistake in calculating the time difference.  Issue closed.  But I do have a question:  Can I specify that I want to use US Eastern timezone for both reading the csv and the X axis?

**Comment by highfestiva** [comment]
You could use `finplot.display_timezone = datetime.timezone.utc`.

**Comment by guanm326** [comment]
Whenever I am plotting I am getting UTC time zone. According to the docs, finplot uses local compute time zone. Additionally I've set `display_timezone`:

```
    import finplot as fplt
    from dateutil.tz import gettz
    fplt.display_timezone = gettz('America/Chicago')
    ax, ax2 = fplt.create_plot("Custom", rows=2)
    fplt.candlestick_ochl(data[['Open', 'Close', 'High', 'Low']])
    fplt.show()
```

Image below shows the time of my last bar of the dataframe. Its the closing price of a US stock in chicago time which is around 14:59PM. I am getting 9:59. Any ideas?



![Untitled](https://user-images.githubusercontent.com/2151940/103483595-efa23c80-4dad-11eb-8c1b-7c42dde556a9.png)


![Un1titled](https://user-images.githubusercontent.com/2151940/103483637-3bed7c80-4dae-11eb-9921-14db82e9d8ec.png)

**Comment by highfestiva** [comment]
@guanm326 unable to reproduce, post a full example including data.

**Comment by guanm326** [comment]
I've attached csv data. code below:

    data = pd.read_csv("...........stk.csv")
    data['datetime'] = pd.to_datetime(data['datetime'])
    data = data.set_index('datetime')

    import finplot as fplt
    from dateutil.tz import gettz
    fplt.display_timezone = gettz('America/Chicago')
    ax, ax2 = fplt.create_plot("Custom", rows=2)
    fplt.candlestick_ochl(data[['Open', 'Close', 'High', 'Low']])
    fplt.show()

Now its showing 8:59 for the last bar when its suppose to be 14:59...

[stk.zip](https://github.com/highfestiva/finplot/files/5762696/stk.zip)
![Untitled](https://user-images.githubusercontent.com/2151940/103495232-b09cd700-4dff-11eb-8f7b-70ba4e2a7bff.png)
![image](https://user-images.githubusercontent.com/2151940/103495279-df1ab200-4dff-11eb-86c5-287e555b59ec.png)

**Comment by highfestiva** [comment]
You are loading data in UTC format, and want to display it as such?

````python
fplt.display_timezone = gettz('UTC')
````
