### ISSUE TITLE
Possible to make it display as webpage component?

### ISSUE THREAD

**Issue by kccheung** [highfestiva/finplot#6]
I would like to add finplot realtime chart on webpage which is developed using Django / Flask. Would like to know if this is possible now or in the future?

**Comment by highfestiva** [comment]
Possibly, but probably not. Feel free to contribute a web implementation if you have the time!

Skickat från min iPhone

**Comment by highfestiva** [comment]
Sorry, decided against web backend. Better to do one thing really well, sorry about that. Unfortunately I don't know what might be a good recommendation for you, except for perhaps tradingview. Good luck!
