### ISSUE TITLE
Cannot drag plots with mouse button after add grid

### ISSUE THREAD

**Issue by sunphoenix** [highfestiva/finplot#62]
Hi, firstly I must say finplot is really a fancy and powerful tool.  I decide to use finplot as my strategy backtesting result visualization platform.
Now I encounter with a problem when I want to make the chart show grid:
I add statement `ax.showGrid(False, True)` in  following functions: candlestick_ochl, volume_ocv and plot.
Then I found that I cannot use mouse left button to drag plots horizontally any more.
Could you please help? What should I do to make the chart show grid without interfere current feature?
Thank you very much.

**Comment by highfestiva** [comment]
That seems to have been a result of some internal constraints in pyqtgraph's axis implementation. I circumvented it in commit e405263.

**Comment by sunphoenix** [comment]
Wonderful! It works! 
But it's a little hard to know why. Do I need to read the source code of pyqtgraph to understand your solution?
Thank you.

**Comment by highfestiva** [comment]
Yes, but it seems to be by design. For some reason horizontal grid=only Y-drag. See pyqtgraph's AxisItem.py:1158.
