### ISSUE TITLE
(df.index)): TypeError: '>' not supported between instances of 'str' and 'float'

### ISSUE THREAD

**Issue by pssolanki111** [highfestiva/finplot#63]
Hi Jonas,
Thanks for this wonderful gem of a library :)
[HERE](https://github.com/highfestiva/finplot/issues/58#issuecomment-716935886) is a comment from you a while back. 
Now I'm trying to plot data from a json object. 

[THIS](https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=IBM&interval=5min&apikey=demo) Is the API endpoint. 

When I try below code based on your advice (I'm nearly certain I'm doing it wrong),

```
import requests as rq
import pandas as pd
import finplot as fplt


url = 'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=IBM&interval=5min&apikey=demo'

r = rq.get(url).json()

ax = fplt.create_plot('test', rows=1)

# plot candle sticks
fplt.candlestick_ochl(r['Time Series (5min)'], ax=ax)

```

I'm met with this traceback,

```
Traceback (most recent call last):
  File "C:\BeingProfessional\projects\Py\SoFlow.py", line 22, in <module>
    fplt.candlestick_ochl(r['Time Series (5min)'], ax=ax)
  File "C:\Program Files\Python37-32\lib\site-packages\finplot\__init__.py", line 1254, in candlestick_ochl
    datasrc = _create_datasrc(ax, datasrc)
  File "C:\Program Files\Python37-32\lib\site-packages\finplot\__init__.py", line 1819, in _create_datasrc
    datasrc = do_create(*args)
  File "C:\Program Files\Python37-32\lib\site-packages\finplot\__init__.py", line 1818, in do_create
    return PandasDataSource(pd.concat(args, axis=1))
  File "C:\Program Files\Python37-32\lib\site-packages\finplot\__init__.py", line 160, in __init__
    if type(df.index) == pd.DatetimeIndex or df.index[-1]>1e7 or '.RangeIndex' not in str(type(df.index)):
TypeError: '>' not supported between instances of 'str' and 'float'

```
My queries are, 
1. How do I plot this json response data in finplot? If it makes it easier, I am okay with a solution with pandas.
2. Why does finplot throw this error?
3. If there is something wrong with this json formatting, how about the TD Ameritrade API's price history json? I know how to use TDA API, but how do I plot that data in finplot? The json schema looks like [THIS](https://developer.tdameritrade.com/price-history/apis/get/marketdata/%7Bsymbol%7D/pricehistory)

I'll appreciate any help or suggestion..

**Comment by pssolanki111** [comment]
I was able to produce a similar error code for TDA API json response. 
tried the endpoint - [HERE](https://api.tdameritrade.com/v1/marketdata/AAPL/pricehistory?apikey=G2CFAVSZYXPFGYJIMLQLWPWD5Y2FOQNG&periodType=day&period=1&frequencyType=minute&frequency=30)

short code,

```
import requests as rq
import pandas as pd
import finplot as fplt


url = 'https://api.tdameritrade.com/v1/marketdata/AAPL/pricehistory?apikey=G2CFAVSZYXPFGYJIMLQLWPWD5Y2FOQNG&periodType=day&period=1&frequencyType=minute&frequency=30'

r = rq.get(url).json()

print(r['candles'])

ax,ax2 = fplt.create_plot('test', rows=2)

# plot candle sticks
fplt.candlestick_ochl(r['candles'], ax=ax)

fplt.show()

```

Traceback was
```
Traceback (most recent call last):
  File "C:\BeingProfessional\projects\Py\SoFlow.py", line 15, in <module>
    fplt.candlestick_ochl(r['candles'], ax=ax)
  File "C:\Program Files\Python37-32\lib\site-packages\finplot\__init__.py", line 1256, in candlestick_ochl
    _set_datasrc(ax, datasrc)
  File "C:\Program Files\Python37-32\lib\site-packages\finplot\__init__.py", line 1862, in _set_datasrc
    if datasrc.timebased() and (epoch_period > 1e7 or not datasrc.standalone):
  File "C:\Program Files\Python37-32\lib\site-packages\finplot\__init__.py", line 252, in timebased
    return self.df.iloc[-1,0] > 1e7
TypeError: '>' not supported between instances of 'dict' and 'float'

```

**Comment by highfestiva** [comment]
You're not far off the mark:

````python
df = pd.DataFrame(r['candles']).set_index('datetime')
fplt.candlestick_ochl(df[['open','close','high','low']])
fplt.show()
````

Have fun!

**Comment by highfestiva** [comment]
... regarding your first example/bug you need some more data processing, but out of the scope for a plotting library:

1. Put each timestamp per row.
2. Make it into a matrix.
3. Convert all values from strings to their respective types (datetime and floats).

Then you can plot.

**Comment by highfestiva** [comment]
Btw. this is what you need to do to get your first example plotting:

````python
url = 'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=IBM&interval=5min&apikey=demo'
r = rq.get(url).json()
ts = r['Time Series (5min)']
rows = [[t]+list(kv.values()) for t,kv in ts.items()]
df = pd.DataFrame(data=rows, columns=['timestamp']+list(next(iter(ts.values()))))
df = df.rename(columns={'1. open':'open', '2. high':'high', '3. low':'low', '4. close':'close', '5. volume':'volume'})
df['timestamp'] = pd.to_datetime(df['timestamp'])
df = df.set_index('timestamp')
df = df.astype(float)
````

Note though, that the open and close columns are actually *inversed* in the downloaded data! We fix by simply flipping open and close when plotting like so:

````python
fplt.candlestick_ochl(df[['close','open','high','low']]) # close before open
fplt.show()
````

**Comment by pssolanki111** [comment]
> You're not far off the mark:
> 
> ```python
> df = pd.DataFrame(r['candles']).set_index('datetime')
> fplt.candlestick_ochl(df[['open','close','high','low']])
> fplt.show()
> ```
> 
> Have fun!

Thank You. I had similar ideas but that schema got the better of me.



> Btw. this is what you need to do to get your first example plotting:
> 
> ```python
> url = 'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=IBM&interval=5min&apikey=demo'
> r = rq.get(url).json()
> ts = r['Time Series (5min)']
> rows = [[t]+list(kv.values()) for t,kv in ts.items()]
> df = pd.DataFrame(data=rows, columns=['timestamp']+list(next(iter(ts.values()))))
> df = df.rename(columns={'1. open':'open', '2. high':'high', '3. low':'low', '4. close':'close', '5. volume':'volume'})
> df['timestamp'] = pd.to_datetime(df['timestamp'])
> df = df.set_index('timestamp')
> df = df.astype(float)
> ```
> 
> Note though, that the open and close columns are actually _inversed_ in the downloaded data! We fix by simply flipping open and close when plotting like so:
> 
> ```python
> fplt.candlestick_ochl(df[['close','open','high','low']]) # close before open
> fplt.show()
> ```

I can't thank you enough, jonas! I'ma close the issue now. Thus is just too good.
