### ISSUE TITLE
[Possible workaround for] ERROR: Could not find a version that satisfies the requirement PyQt5==5.13.0 (from finplot) (from versions: 5.12.3, 5.14.0, 5.14.1, 5.14.2, 5.15.0, 5.15.1)

### ISSUE THREAD

**Issue by pssolanki111** [highfestiva/finplot#64]
Hey there, Jonas
Sorry for troubling you again. One of my clients had this problem when they were trying to install finplot. I could use finplot perfectly well with Py3.7 on my machine.  

C:\Users\some user\scripts\projects\pythontraining\Scripts>pip install finplot
Collecting finplot
Downloading finplot-1.3.0-py3-none-any.whl (48 kB)
|████████████████████████████████| 48 kB 318 kB/s
Collecting pyqtgraph>=0.10.0
Downloading pyqtgraph-0.11.0-py3-none-any.whl (800 kB)
|████████████████████████████████| 800 kB 133 kB/s
Collecting pandas>=0.23.4
Downloading pandas-1.1.4-cp39-cp39-win_amd64.whl (8.9 MB)
|████████████████████████████████| 8.9 MB 386 kB/s
ERROR: Could not find a version that satisfies the requirement PyQt5==5.13.0 (from finplot) (from versions: 5.12.3, 5.14.0, 5.14.1, 5.14.2, 5.15.0, 5.15.1)
ERROR: No matching distribution found for PyQt5==5.13.0 (from finplot)

C:\Users\some name\scripts\projects\pythontraining\Scripts>pip install finplot
Collecting finplot
Using cached finplot-1.3.0-py3-none-any.whl (48 kB)
Collecting pandas>=0.23.4
Using cached pandas-1.1.4-cp39-cp39-win_amd64.whl (8.9 MB)
ERROR: Could not find a version that satisfies the requirement PyQt5==5.13.0 (from finplot) (from versions: 5.12.3, 5.14.0, 5.14.1, 5.14.2, 5.15.0, 5.15.1)
ERROR: No matching distribution found for PyQt5==5.13.0 (from finplot)

Isn't there a workaround for the same? Maybe getting `precompiled binary wheels` for the required version of `pyqtgraph` and installing them manually?
Till the time the pyqtgraph maintainers review those PRs addressing the bug related to NaN, maybe something like that could do the job for us ATM. 

What do you think? I wanted to discuss this with ya 'cause it feels promising to me..

**Comment by highfestiva** [comment]
You could `pip --no-dependencies` and pull in whatever. In the mean while, your NaN lines will be gone.

**Comment by pssolanki111** [comment]
@highfestiva I see. Unfortunately could not find any precompiled binary wheels for Py3.9. Is there a way to somehow pull out my finplot install (on Py3.7) and install that on Py3.9 system.
And sorry 'cause I didn't understand what you meant by "Your NaN lines will be gone".

**Comment by pssolanki111** [comment]
@highfestiva I'm closing this issue 'cause as we already have a similar issue opened. And I just made my client install a previous version of python (py3.7).

**Comment by highfestiva** [comment]
In the latest incarnation `finplot` supports all Qt versions.
