### ISSUE TITLE
Friday bars appear as Sunday (or the day before the next market open)

### ISSUE THREAD

**Issue by daiwei89** [highfestiva/finplot#65]
Thank you for the super useful plotting tool. I think it's opinionated in the right ways. Here's a pretty important bug I find.

Basic example 

```
import finplot as fplt
import yfinance

df = yfinance.download('AAPL')
df = df[['Open', 'Close', 'High', 'Low']]
df.columns = ['open', 'close', 'high', 'low']
fplt.candlestick_ochl(df)
fplt.show()
```
For example 2013-5-27 (Monday) is memorial holiday (market close). 2013-5-24 (Friday) is plotted as 2013-5-27. This is quite inaccurate and misleading especially for financial data.

See screenshot:

![image](https://user-images.githubusercontent.com/1715658/100140028-39117a80-2e45-11eb-87b2-2146056a0f9d.png)

**Comment by pssolanki111** [comment]
Well I'm no expert here, but I'm almost entirely certain that it definitely depends on the timezone of the `datetime` values. Moreover the library will always plot what it finds in the data, it won't create those data points manually. 

I'm pretty sure `finplot` allows to change the TimeZone info to parse the dates.

However you would probably want to wait for a response from Jonas.

**Comment by highfestiva** [comment]
This is actually to a bug in Yahoo Finance's api, where downloaded days down to 1h intervals are reported in local (Nasdaq) time instead of UTC. If you use [60m resolution](ranaroussi/yfinance#125), everything's fine. Someone else bumped into this bug [before](https://github.com/highfestiva/finplot/issues/31#issuecomment-695952455).

To circumvent the problem:

````python
from datetime import timezone
fplt.display_timezone = timezone.utc
# download 1d resolution and plot...
````

**Comment by daiwei89** [comment]
Nice! That indeed solved the problem. Thank you so much for the fast answer!

**Comment by highfestiva** [comment]
Left him a [pull request](https://github.com/ranaroussi/yfinance/pull/516) to ensure date is correct for 1d and 1w intervals, but is seems the code is not on par with his codefactor settings.
