### ISSUE TITLE
dump markers are so small, how to make it bigger ?

### ISSUE THREAD

**Issue by Gary-Hertel** [highfestiva/finplot#66]
dump markers are so small,  not easy to see signals.
how to make it bigger so can see signals more obvious ？
![image](https://user-images.githubusercontent.com/67775512/100779126-e2a6cc00-3442-11eb-8068-c07dfb6e0cf3.png)

**Comment by highfestiva** [comment]
`fplt.plot(x, y, style='v', width=10)`

**Comment by Gary-Hertel** [comment]
Excellent！Thanks a lot ! Finplot is so powerful !
![image](https://user-images.githubusercontent.com/67775512/100781171-a759cc80-3445-11eb-9ed2-36e1398ee4e5.png)

**Comment by Gary-Hertel** [comment]
I have a new problem, i am using i mintue kline, in the pictures, i just can see 2020-01-01, how can i see 2020-01-01 12-00-00
```
df = pd.DataFrame(kline, columns='time open high low close volume'.split())
    df = df.astype(
        {
            'time': 'datetime64[ns]',
            'open': 'float64',
            'high': 'float64',
            'low': 'float64',
            'close': 'float64',
            'volume': 'float64'
        }
    )
    candlesticks = df['time open close high low'.split()]
    volumes = df['time open close volume'.split()]
```

**Comment by Gary-Hertel** [comment]
i solved this problem, i used wrong timeframe.
