### ISSUE TITLE
PandasDataSource incorrectly identifies series as standalone (heuristic in _is_standalone)

### ISSUE THREAD

**Issue by seletskiy** [highfestiva/finplot#67]
Example data that I pass as `x` argument to the `finplot.plot(x=…)` function:

```
0       2020-12-04 14:31:02.709666
1       2020-12-04 14:31:02.710209
2       2020-12-04 14:31:02.710811
3       2020-12-04 14:31:02.711258
4       2020-12-04 14:31:02.711691
                   ...
28885   2020-12-04 15:00:53.234997
28886   2020-12-04 15:00:53.484589
28887   2020-12-04 15:00:53.485027
28888   2020-12-04 15:00:53.485514
28889   2020-12-04 15:00:53.486025
```

I don't get plot that I want with this kind of data because [`_is_standalone()` function](https://github.com/highfestiva/finplot/blob/master/finplot/__init__.py#L1794) returns `True`, in particular, `timeser.diff()<=0` condition returns many items that are `0` because it seems that `diff` function fails to account for microsecond part, e.g. diff between `2020-12-04 14:31:02.711258` and `2020-12-04 14:31:02.711691` returns `0`.

I use the following workaround which works but requires additional code on the client-side.

```
ds = plt.PandasDataSource(pd.concat((times, prices), axis=1))
ds.standalone = False
plt.plot(ds)
```

**Comment by highfestiva** [comment]
You're right, this causes millisecond truncation instead of rounding:

````python
pd.to_datetime(['2020-12-04 14:31:02.711691']).astype(int) // 1_000_000
````

Would rounding to the trick for you, or do you require even higher resolution? One possibility is to change internal representation to ns, which might be a good idea for high frequency trading anyway...

**Comment by seletskiy** [comment]
@highfestiva Thanks for the prompt reply. Yep, I need to keep that nasty microsecond part due to the high-frequency nature of the data I'm dealing with.

**Comment by highfestiva** [comment]
With five minutes+ worth of data, your charts are going to be sluggish bordering useless?

**Comment by seletskiy** [comment]
@highfestiva Well, I do not have a point every microsecond. Sometimes, several data points fit into a single millisecond (as in the example), sometimes they do not. Right now `finplot` renders ~160k points just fine.

**Comment by highfestiva** [comment]
I changed the internal representation to ns instead of ms in https://github.com/highfestiva/finplot/commit/448bd43c6c2c7828d8b5a1a8cddf223c5984eb68; check it.

**Comment by seletskiy** [comment]
@highfestiva It works! Thanks for the very quick fix and overall great lib for plotting.
