### ISSUE TITLE
Analogue of block = false in matplotlib

### ISSUE THREAD

**Issue by VCasecnikovs** [highfestiva/finplot#68]
Good evening.
I am trying to do some visualisation for my RL project.
In my project, I sometimes need to call which calls render function, which should show me the next frame. In matplotlib I used

`plt.show(block=False)`
and after updating axis:
`plt.pause(0.001)`

Could You tell me, what should I do to accomplish the same using finplot?
Is there some documentation?

I tried 
`fplt.show(qt_exec=False)`
and
`time.sleep(0.001)`

But it was in no respondmode...

Best regards,
Vadims.

**Comment by VCasecnikovs** [comment]
Related problem:

https://stackoverflow.com/questions/44527603/run-pyqt-gui-main-app-as-a-separate-non-blocking-process

**Comment by VCasecnikovs** [comment]
As I understand, I should wrap something with QThread. Figuring out what.

**Comment by VCasecnikovs** [comment]
class NonBlockingFinplot():
    def __init__(self, title):
        self.title = title
        self.volume_plot = None
        self.candles_plot = None

    def start(self):
        self.q = Queue()
        self.p = Process(target=self.run)
        self.p.start()
        return self.q

    def run(self):
        self.price_ax, self.net_worth_ax = fplt.create_plot(title=self.title, rows=2)
        fplt.autoviewrestore()
        fplt.timer_callback(self._update, 0.01)
        fplt.show()

    def _update(self):
        while not self.q.empty():
            episode, start_index, current_index = self.q.get()
            
            candles = episode[["otime", "open", "close", "high", "low"]]
            if self.candles_plot is None:
                self.candles_plot = fplt.candlestick_ochl(candles, ax=self.price_ax)
            self.candles_plot.update_data(candles)


            volumes = episode[['otime', 'open', 'close', 'volume']]
            if self.volume_plot is None:
                self.volume_plot = fplt.volume_ocv(volumes, ax=self.price_ax.overlay())
            self.volume_plot.update_data(volumes)

**Comment by VCasecnikovs** [comment]
I finally, solved my problem using the code above. But the issue shouldn't be closed, because it is must-have to do unblocked non-blocking rendering.

**Comment by VCasecnikovs** [comment]
Maybe, this example could help You.
https://gist.github.com/Overdrivr/1c505f9a4ec5be35b2a1
Thank you for the repo.

**Comment by highfestiva** [comment]
I presume you did not read the issue on [threading](https://github.com/highfestiva/finplot#threading). This lib is mainly for backtesting. Therefore it doesn't seem obvious to me that this feature request is a must-have.

**Comment by VCasecnikovs** [comment]
Hello, I've read the issue. Sorry, if I was too aggressive. My point Is that backtesting could be realtime also. For example in a reinforcement learning problem. For me, it looked like it isn't hard to implement it in a universal way. To do this, the threading should be inserted deeper into the library code. Also, the documentation would make this repository more popular. I know that it is really hard to maintain an open-source project. But I would add this 2 features to the TODO list.

**Comment by highfestiva** [comment]
I'll leave it open and ponder the future of this issue.

**Comment by highfestiva** [comment]
Sorry, but this idea introduces too much complexity without adding enough value.
