### ISSUE TITLE
RIght margin candles with volume overlay / Add grid to plot

### ISSUE THREAD

**Issue by EliaOnceAgain** [highfestiva/finplot#69]
First of all, thanks a lot for the library it is great, much appreciated!

I've got two questions
1) `fplt.right_margin_candles = 50` does not move overlay (volume in my case), is there a way to get it to work?
2) Any way to plot grid lines every X price Y time, and/or dynamically set depending on zoom?

**Comment by highfestiva** [comment]
1. You need to set it before creating your plot.
2. `ax.showGrid(True, True)` uses underlying pyqtgraph to show grid. See pyqtgraph for more info on that topic.

**Comment by EliaOnceAgain** [comment]
1. That's what I've been doing but the volume overlay still does not pan with the plotted chart.
2. Unfortunately that disables your keybinding and can't pan the chart with grids on

**Comment by highfestiva** [comment]
Are you using a recent version? `pip install -U finplot`

**Comment by EliaOnceAgain** [comment]
Updated from 1.3 to 1.4, keybindings are working fine with `ax.showGrid(True,True)`. Thanks!

Any clue about number volume overlay does not pan left with chart? It's not critical but would be great if there's a way to get it working from my side

**Comment by highfestiva** [comment]
Compare your code with `example-snp500.py`. Don't know what you're doing wrong without a minimal example.

**Comment by EliaOnceAgain** [comment]
I'll check it out, thanks again
