### ISSUE TITLE
how to plot inline with jupyterlab?

### ISSUE THREAD

**Issue by smartinsightsfromdata** [highfestiva/finplot#7]
Congrats.  Great package!

Is it possible to save inline a plot in jupyterlab?

How?

**Comment by highfestiva** [comment]
Thanks! Unfortunately no support to work in jupyterlab. Haven't used it 
myself unfortunately.

But by all means, please add the code for it and I'll be happy 
incorporate your pull request! :)

Kind regards,
Jonas

------ Originalmeddelande ------
Från: "Enzo" <notifications@github.com>
Till: "highfestiva/finplot" <finplot@noreply.github.com>
Kopia: "Subscribed" <subscribed@noreply.github.com>
Skickat: 2019-10-24 19:06:47
Ämne: [highfestiva/finplot] how to plot inline with jupyterlab? (#7)

**Comment by highfestiva** [comment]
Sorry, decided against web backend, which is required for JupyterLabs. Better to do one thing really well, sorry about that. If you're still going to use it, it's the old-school way with PyCharm or some other editor. Good luck though!
