### ISSUE TITLE
How to update plot?

### ISSUE THREAD

**Issue by VCasecnikovs** [highfestiva/finplot#70]
Good evening,
I have problem with updating markers.
Haven't found explanation how to do this in examples.
Best regards,
Vadims.

**Comment by VCasecnikovs** [comment]
For now, I have ended with something stupid as this
`
if cover_markers.sum() != 0:
                if self.cover_marker_plot is None:
                    self.cover_marker_plot = fplt.plot(pd.DataFrame({"otime" : time[cover_markers], "price" : price[cover_markers]}), color="#000", style='^', ax=self.price_ax, width=5)
                else:
                    self.cover_marker_plot.update_data(pd.DataFrame({"otime" : time[cover_markers], "price" : price[cover_markers]}))

`

**Comment by highfestiva** [comment]
Leave this issue open, and I'll create some example with animated labels and scatter plot.

**Comment by VCasecnikovs** [comment]
Thank you,
The problem is when I update candles and markers on one axis, it just starts to be broken.
All axis shows some random markers and no candles...

**Comment by highfestiva** [comment]
All I read are random words, no explanation. You need to be more specific. What are you doing, reproducible in a minimal piece of code.

**Comment by highfestiva** [comment]
I added a [function](https://github.com/highfestiva/finplot/commit/e57e04aad7508a53628a5440f44ccae08cd10d20#diff-0bd282be9c1ff9f2b099f7ab6bdcc3dc292c933956dc61dce58ed7577ef9fc83R1460-R1466) in the API to move the viewport. And an [example](https://github.com/highfestiva/finplot/blob/master/finplot/example-animate.py) of how to animate both data and viewport.
