### ISSUE TITLE
Save Multiple Images

### ISSUE THREAD

**Issue by avn3r** [highfestiva/finplot#71]
Hello 

First of all thanks for the library. It has everything I could ask for and more and the closest thing to creating tradingview style graphs in python with little code.

However, I have one major hurdle. I want to use this library for Data Collection. Be able to save and store lots of images of this graph. I look at the example provided of using screenshots and the callback to save an image but that only works for a specific plot being shown. I want to be able to loop and over ranges. For example, if I select Apple stock and provide at day frequency. I want to save a plot of day 1 to 10 10-20, etc. But I want to do this while looping over the df so I don't have to run the script hit escape change value manually. I need to automate this since I'm collecting lots of images.

Can you point me in the right direction?
I tried something like this without success:
```
def save():
    global filename
    fplt.screenshot(open(f'{filename}.png', 'wb'))

for i in range(5):
    filename = str(i)
    fplt.timer_callback(save, .5, single_shot=True)  # wait some until we're rendered
    fplt.show()
```

**Comment by highfestiva** [comment]
You could use `ax.vb.pan_x(percent=+90)` to access the "view box" (a pyqtgraph construct) to move 90% of the display width to right. Out of curiosity, what are you going to use these images for?

**Comment by avn3r** [comment]
Basically, I need to save without the .show(), that will be too slow. I'm using it to train a AI model. So transforming the data to image with indicators and let the AI figure it out.

I got it working with mplfinance but I prefer this library for speed and flexibility but stock on this step.

**Comment by highfestiva** [comment]
You're a ton better off using the raw data instead of the images. However I don't think it's possible without `.show()`, but that shouldn't be a major problem? You can load 500k candles per round, then pan through them in zoomed-in level, then load the next 500k and update the plot, `pan_x()`, etc, etc.

**Comment by highfestiva** [comment]
To clarify:

1. Load and `show()`.
2. `pan_x(steps=-1e10)` to far left.
3. Take `screenshot()`.
4. `pan_x(percent=+90)`
5. If not at same position: goto 2.
6. Load if necessary.
7. Update plots with new data or break.
8. Goto 2.

**Comment by avn3r-dn** [comment]
Feel Free to close this, thanks!
