### ISSUE TITLE
please help me!!!

### ISSUE THREAD

**Issue by LongNumber5** [highfestiva/finplot#73]
Can I ask you something? I just want each graph display, the default graph will zoom in and show exactly 100 candles and move to the end just like pressing the "End" button? Thank you very much.

**Comment by highfestiva** [comment]
`create_plot(init_zoom_periods=100)`

**Comment by LongNumber5** [comment]
Wow, Thank you very much.

**Comment by LongNumber5** [comment]
Your library is really awesome
![image](https://user-images.githubusercontent.com/60207029/101600316-b9330500-3a2d-11eb-8677-a89d21739674.png)

**Comment by highfestiva** [comment]
please close me!!!
