### ISSUE TITLE
Is there any way to JumpToDate

### ISSUE THREAD

**Issue by karunkrishna** [highfestiva/finplot#78]
Is there an api to jump current viewport to a particular date and have it zoomed in?

Say I want to visually spot check a few cases, by entering a DateTime for when the signal was triggered, is that all possible? 
Any insight on how I might be able to implement this, if it doesn't exist? 

Overall Render (init_zoom_period=1e5)
![image](https://user-images.githubusercontent.com/2157606/102390188-16850400-3fa2-11eb-94a8-18b9646345c4.png)

JumpToDate: 2020-12-08 13:00  (init_zoom_periods=1e2)
![image](https://user-images.githubusercontent.com/2157606/102390164-0d943280-3fa2-11eb-8603-18a98d871721.png)

**Comment by highfestiva** [comment]
Unfortunately there is no such api nicely available straight out of the box. But say you have 500 candles. Then this probably works:

````python
ax.vb.update_y_zoom(x0=200, x1=300)
````

This will move the left side to the 200th candle, and the right-hand side will show the 300th candle. One more unfortunate thing is that you might have to do this for all plots, i.e. `ax`, `ax2`, `ax3`...

Please don't close this issue, and I'll add an api function for it when I have time.

**Comment by highfestiva** [comment]
I added a [function](https://github.com/highfestiva/finplot/commit/e57e04aad7508a53628a5440f44ccae08cd10d20#diff-0bd282be9c1ff9f2b099f7ab6bdcc3dc292c933956dc61dce58ed7577ef9fc83R1460-R1466) in the API to move the viewport. And an [example](https://github.com/highfestiva/finplot/blob/master/finplot/example-animate.py) too.
