### ISSUE TITLE
Let me ask how to not draw the X marked area as in the picture?

### ISSUE THREAD

**Issue by LongNumber5** [highfestiva/finplot#79]
![image](https://user-images.githubusercontent.com/60207029/102448738-5eb92a80-4065-11eb-985e-03243d060cb5.png)
Let me ask how to not draw the X marked area as in the picture.

**Comment by highfestiva** [comment]
Can I see a minimal example to reproduce the X?

Looks like you've done a lot! If I may ask, what's your overall impression? How's the API? Performance? How hard is it to get things done? Any feature in particular you've built that took a lot of effort? Thanks!

**Comment by LongNumber5** [comment]
Thanks

**Comment by highfestiva** [comment]
You troll you!?
