### ISSUE TITLE
Function for "Fill Between" and "Alpha"?

### ISSUE THREAD

**Issue by yiluzhou** [highfestiva/finplot#8]
How to generate a shaded region (eg: Bollinger Band)? In matplotlib, there is "fill_between" and "alpha" function.

Thank you!

**Comment by highfestiva** [comment]
Unfortunately not yet. I haven't found fill particularly useful myself, partly because I often add many plots per axis. If you'd like to add it and create a pull request, perhaps some class close to pyqtgraph's LinearRegionItem could be of help. I'd be happy to include it if you do!

**Comment by highfestiva** [comment]
I just added the feature you requested in 36fe6879c3bce3f434d075ef3cf4964527683de0. The input parameters are the two line plots you want to shade between. See example-bitmex-ws.py for more info.

**Comment by yiluzhou** [comment]
Awesome!!! Thank you so much!!!
