### ISSUE TITLE
Saving image enhacement

### ISSUE THREAD

**Issue by karunkrishna** [highfestiva/finplot#80]
1. Is it possible to define the width and height of the plot when initialized so that it can be respected in the save function (currently the only option is fplt.create_plot(maximize=True)

2. Is it possible to save the image without having to run flpt.show()

- The image only get's created once the show function is run
- I wanted to loop through several dates and create a print screens;  Having to call show, results in me having to close each pop-up manually 

![image](https://user-images.githubusercontent.com/2157606/102551849-2ed24d00-408e-11eb-9ebd-40d24d0d9cf1.png)

**Comment by highfestiva** [comment]
1. Set `fplt.winw` and `winh` before creating window.
2. See https://github.com/highfestiva/finplot/issues/71#issuecomment-742015927

**Comment by highfestiva** [comment]
I added a [function](https://github.com/highfestiva/finplot/commit/e57e04aad7508a53628a5440f44ccae08cd10d20#diff-0bd282be9c1ff9f2b099f7ab6bdcc3dc292c933956dc61dce58ed7577ef9fc83R1460-R1466) in the API to move the viewport. And an [example](https://github.com/highfestiva/finplot/blob/master/finplot/example-animate.py) too.
