### ISSUE TITLE
Feature request: drawing tools

### ISSUE THREAD

**Issue by gryabov** [highfestiva/finplot#82]
Is it possible to add drawing tools with simple tools like: draw line, change line color and width, store drawings to file and open  drawings? Something simple.

**Comment by highfestiva** [comment]
Yes but these features, and other similar ones, are best added in an application. finplot supports those features, but it does not implement them (fully). The main purpose of finplot is backtesting visualisation, and manual drawing is no part of that.

That being said, it would be really nice to have such an example application, which show off such features, and other parts of finplot. If you feel up to it, I would love for you to contribute such an application. Perhaps showing both stock and cryptocurrencies. What do you say?
