### ISSUE TITLE
Usage Question: how to get geometrically distanced horizontal lines without performance impact?

### ISSUE THREAD

**Issue by haimivan** [highfestiva/finplot#83]
Hi,

superb library - you are doing a great job!

I have a question:
In order to see easily my stop-loss levels of 0.25 % during backtesting / analyzing, I used to set in matplotlib my own ticks scale at the y axis (via `.set_yticks()`). 
For that I generated a list in this way:

```
myMin = df.low.min()
myMax = df.high.max()
ratio = 1.0025
myHLines = [myMin * ratio ** i for i in range(1000) if myMin * ratio ** i < myMax]
```
If possible, I would like to have the same for __finplot__ :-)

Is there any possibility to get custom horizontal lines that do not degrade performance? I read in another issue, that `plot` can possibly slow down things a lot (as compared to `candlesticks`).

If I have to create 1000 lines via `plot`, I fear that this could degrade the performance.

Is there any possibility to create a custom (minor or major) tick list  with __finplot__ that is performance neutral?

Thanks in advance!

**Comment by highfestiva** [comment]
You can use the underlying pyqtgraph API `ax.showGrid(False, True)` to enable a grid. Zero performance impact is not feasible, but it is at least it comes at the lowest possible cost. If you're drawing 1k lines, expect a major performance degradation. I haven't looked into how you set the "tick list" for the grid in pyqtgraph, but assume it's doable fairly easy.

**Comment by haimivan** [comment]
```
ax1.axes['left']['item'].setTicks([[(v, str(v)) for v in myHLines]])
```
does the job.
