### ISSUE TITLE
Somehow two candlestick subcharts are not linked together in all situations?

### ISSUE THREAD

**Issue by haimivan** [highfestiva/finplot#84]
Hi,

I am working on the topic to connect two subcharts where the lower one contains the daily version of the upper one.

Somehow the zoom factor of the first does not seem to follow the other one and vice versa.

I hope the following gif illustrates this.

Please find below the code and some additional output.

Thanks in advance for having a look!

![output](https://user-images.githubusercontent.com/10325765/103016235-0d67da00-4542-11eb-914f-15748735db7d.gif)

#### code:
```
import finplot as fplt
import yfinance as yf
import pytz
import pyqtgraph
import pandas as pd
import numpy as np
import datetime
import statsmodels
import statsmodels.api as sm
sm.show_versions()


print("pyqtgraph.__version__=", pyqtgraph.__version__)

periods = 10
datelist = pd.date_range(pd.to_datetime('2020-12-23 06:00'), periods=periods, freq="12h").tolist()
df = pd.DataFrame({'open': [10, 20, 30, 40, 50, 60, 70, 80, 90, 10],
                   'close': [100, 90, 80, 70, 60, 50, 40, 30, 20, 10],
                   'high': [105, 95, 85, 75, 65, 65, 75, 85, 95, 105],
                   'low': [5, 15, 25, 35, 45, 45, 35, 25, 15, 5]}, index=datelist)

fplt.display_timezone = pytz.timezone('UTC')
fplt.max_zoom_points = 1
# no margins
fplt.right_margin_candles = 4
fplt.side_margin = 4
ax1, ax2 = fplt.create_plot(title='123', rows=2)

fplt.candlestick_ochl(df[['open', 'close', 'high', 'low']], ax=ax1)

# second plot shows daily
dfd = df.open.resample('D').first().to_frame()
dfd['close'] = df.close.resample('D').last()
dfd['high'] = df.high.resample('D').max()
dfd['low'] = df.low.resample('D').min()
daily = fplt.candlestick_ochl(dfd.dropna(), ax=ax2)
# daily.x_offset = 1
fplt.show()
```

### output:
```
/home/user/venv/numba/bin/python3.6 /home/user/PycharmProjects/myProject/attic02.py attic02.py

INSTALLED VERSIONS
------------------
Python: 3.6.8.final.0
OS: Linux 4.4.0-197-generic #229-Ubuntu SMP Wed Nov 25 11:05:42 UTC 2020 x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

statsmodels
===========

Installed: 0.12.1 (/home/user/venv/numba/lib/python3.6/site-packages/statsmodels)

Required Dependencies
=====================

cython: 0.29.14 (/home/user/venv/numba/lib/python3.6/site-packages/Cython)
numpy: 1.19.4 (/home/user/venv/numba/lib/python3.6/site-packages/numpy)
scipy: 1.5.2 (/home/user/venv/numba/lib/python3.6/site-packages/scipy)
pandas: 1.1.5 (/home/user/venv/numba/lib/python3.6/site-packages/pandas)
    dateutil: 2.8.1 (/home/user/venv/numba/lib/python3.6/site-packages/dateutil)
patsy: 0.5.1 (/home/user/venv/numba/lib/python3.6/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.3.3 (/home/user/venv/numba/lib/python3.6/site-packages/matplotlib)
    backend: Qt5Agg 
cvxopt: Not installed
joblib: 0.13.2 (/home/user/venv/numba/lib/python3.6/site-packages/joblib)

Developer Tools
================

IPython: 7.8.0 (/home/user/venv/numba/lib/python3.6/site-packages/IPython)
    jinja2: 2.11.2 (/home/user/venv/numba/lib/python3.6/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.4.2 (/home/user/venv/numba/lib/python3.6/site-packages/pygments)
pytest: 5.2.2 (/home/user/venv/numba/lib/python3.6/site-packages)
virtualenv: Not installed


pyqtgraph.__version__= 0.11.1
fin

Process finished with exit code 1

```

**Comment by highfestiva** [comment]
finplot works sub-optimal with different time scales, and it's not a trivial problem to solve. For instance, zooming into three candles on the top chart corresponds to 1.5 candles in the bottom chart. (Showing half candles are not supported.) Also, the `max_zoom_points` are applied to the axis you're currently zooming in. So if you do it at the top, the bottom one will be "overzoomed", and won't update until you zoom out enough for it to have more than `max_zoom_points` candles. In your case, the candles are at least double the frequency on the top axis, but there's nothing stopping a user from having 2½ times as many candles there either.

As you might gather by now, finplot does a bad job of housekeeping the whitespace on the sides.

A temporary solution for you is to only zoom+pan at the bottom axis. Having more candles helps, as the top chart won't as easily "run out" when zooming out at the bottom. Setting `right_margin_candles` and `side_margin` to `0` might help a little.

I'll think about a permanent solution, please keep this issue open.

**Comment by haimivan** [comment]
Ok, I will wait. 

Thanks for the time being! :-)

**Comment by highfestiva** [comment]
Fix in https://github.com/highfestiva/finplot/commit/9b0f7ce918afb84b7f312f06f6ac2ed59f310b17 helps, but doesn't remove 100% of the quirks. Under normal circumstances, this shouldn't be a problem. Using longer time series, and setting `max_zoom_points` to 20-ish or more should be enough for most use cases.

**Comment by haimivan** [comment]
Ok, thanks a lot also for this!. :+1: 

And you are right, that the example above is not so common. 

Perhaps time will show whether others will be ok with this solution when using longer time series and setting `max_zoom_points` accordingly.

Thanks again!
