### ISSUE TITLE
Is it possible to see plot() data before candlestick_ochl() data?

### ISSUE THREAD

**Issue by haimivan** [highfestiva/finplot#87]
Hi (and merry christmas :-) ),

If I have an intraday `candlestick_ochl()` and a daily `candlestick_ochl()`, I can get the intraday data visible by creating it _after_ my daily data (and take different colours).

However, this rule does not seem to apply for the combination of `candlestick_ochl()` with `plot()`.

Independent of order, the `plot()` data gets invisible, if a candlestick is at the same position.

Is there any way to get the `plot()` data visible in such a situation?

Thanks in advance!

_Stopwords: opaque, background, foreground_

**Comment by highfestiva** [comment]
Please post minimal example.

**Comment by haimivan** [comment]
yes, if you look at the modified example from the readme.md, the `plot()` is created after the `candlestick_ochl()`, but still the line of the plot is hidden after the candlestick:

```python
#!/usr/bin/env python3

import finplot as fplt
import numpy as np
import pandas as pd
import requests

# pull some data
symbol = 'USDT-BTC'
url = 'https://bittrex.com/Api/v2.0/pub/market/GetTicks?marketName=%s&tickInterval=fiveMin' % symbol
data = requests.get(url).json()

# format it in pandas
df = pd.DataFrame(data['result'])
df = df.rename(columns={'T':'time', 'O':'open', 'C':'close', 'H':'high', 'L':'low', 'V':'volume'})
df = df.astype({'time':'datetime64[ns]'})

# create two axes
ax = fplt.create_plot(symbol, rows=1)

# plot candle sticks
candles = df[['time','open','close','high','low']]
fplt.candlestick_ochl(candles, ax=ax)

# put an MA on the close price
fplt.plot(df['time'], df['close'].rolling(25).mean(), ax=ax, legend='ma-25')

# restore view (X-position and zoom) if we ever run this example again
fplt.autoviewrestore()

# we're done
fplt.show()
```

![image](https://user-images.githubusercontent.com/10325765/103137730-c1e13780-46cb-11eb-94f1-50b1dec2d2e1.png)

**Comment by highfestiva** [comment]
Put the line in front by having a high Z-value (pyqtgraph stuff):

````python
p = fplt.plot(df['time'], df['close'].rolling(25).mean(), ax=ax, legend='ma-25')
p.setZValue(100)
````

**Comment by haimivan** [comment]
Thanks a lot. This helped me again! :-)
