### ISSUE TITLE
Feature Request: x axis ticks at "round" positions

### ISSUE THREAD

**Issue by haimivan** [highfestiva/finplot#88]
_Hi,_

_if possible, it would be very helpful to me if the following could be implemented. Thanks a lot in advance!_

Presently, the x axis ticks do not adhere any "round" positions. 

As visible in the screen shot below, the ticks appear at 

- 2020-12-17 22:30
- 2020-12-18 15:10
- 2020-12-19 07:50
- 2020-12-20 00:30

It would be very nice, if they could appear at 
- 2020-12-17 00:00
- 2020-12-18 00:00
- 2020-12-19 00:00
- 2020-12-20 00:00

Background: with this, for intraday data it is much easier for me to identify any price gaps in the chart as being 'generated' due to the closed exchange.

The possible "round" positions, that I could image are accordingly:
- 1 min
- 5 min
- 1 hour
- 1 day
- 7 days (fixed to Mondays - or configurable?)
- 1 month
- 3 months
- 1 year
- 5 years

Remark (if this makes a difference for the implementation): over the years for some instruments the opening hours of the referring exchange might have changed - or might change regularly, if  the exchange is daylight saving time dependant and e. g. `UTC` is taken for backtesting.

![image](https://user-images.githubusercontent.com/10325765/103122359-32626700-4680-11eb-8db0-33528b03503b.png)

**Comment by highfestiva** [comment]
Sounds like a nice feature, but hard to implement due to time zones and daylight savings, etc. If you want to do it yourself, you can extend the class `finplot.EpochAxisItem`. If you get a good implementation, I'd be happy to take a pull request from you, but I'm not going to spend time on it though.

**Comment by haimivan** [comment]
Ok, thanks. I will think about it!
