### ISSUE TITLE
Feature Request: increase/decrease zoom with arrow up / down

### ISSUE THREAD

**Issue by haimivan** [highfestiva/finplot#89]
_Hi,_

_I have another suggestion... Thanks again_  :smile:

as a user of a _touch pad only laptop_, it would be very helpful to zoom into / out of the plot with the arrow keys.

My laptop does not have a mouse scroll wheel, therefore I have to zoom with two fingers on the touchpad. This is a little bit complicated presently (sometimes a very similar action produces a zoom in or a zoom out). 

For me it would be much easier if I could use the arrow keys also for zooming (I can concentrate on the plot / the data and do not have to move my fingers away from the arrow keys). 

As the mouse zooming behaviour seems to be dependant from the presently active subplot, the arrow key zooming could possibly be dependant from the present position of the mouse pointer.

- zoom in: arrow up
- zoom out: arrow down

**Comment by highfestiva** [comment]
You could take over the keyboard handling. Something like so:

````python
def _key_pressed(vb, ev):
    if ev.key() == QtCore.Qt.Key_Up:
        vr = vb.targetRect()
        vb.zoom_rect(vr, 1.1, vr.center())
    elif ev.key() == QtCore.Qt.Key_Down:
        vr = vb.targetRect()
        vb.zoom_rect(vr, 0.9, vr.center())
    else:
        return False
    return True

finplot._key_pressed = my_key_handler
````

**Comment by haimivan** [comment]
Thanks a lot.

I was able to do so - also with incorporating the keys that are already defined in __finplot__.

Just the 'g' does not seem to be substitutable from "outside" because of the `global` variable `clamp_grid`.

Please find below my solution:

```python
        def my_key_handler(vb, ev):
            # if ev.text() == 'g':  # grid
            #     global clamp_grid
            #     clamp_grid = not clamp_grid
            #     for win in fplt.windows:
            #         for ax in win.axs:
            #             ax.crosshair.update()
            if ev.text() in ('\r', ' '):  # enter, space
                vb.set_draw_line_color(fplt.draw_done_color)
                vb.draw_line = None
            elif ev.text() in ('\x7f', '\b'):  # del, backspace
                if not vb.remove_last_roi():
                    return False
            elif ev.key() == fplt.QtCore.Qt.Key_Left:
                vb.pan_x(percent=-15)
            elif ev.key() == fplt.QtCore.Qt.Key_Right:
                vb.pan_x(percent=+15)
            elif ev.key() == fplt.QtCore.Qt.Key_Home:
                vb.pan_x(steps=-1e10)
                _repaint_candles()
            elif ev.key() == fplt.QtCore.Qt.Key_End:
                vb.pan_x(steps=+1e10)
                _repaint_candles()
            elif ev.key() == fplt.QtCore.Qt.Key_Escape:
                vb.win.close()

            elif ev.key() == fplt.QtCore.Qt.Key_Up:
                vr = vb.targetRect()
                vb.zoom_rect(vr, 1.1, vr.center())
            elif ev.key() == fplt.QtCore.Qt.Key_Down:
                vr = vb.targetRect()
                vb.zoom_rect(vr, 0.9, vr.center())
            else:
                return False
            return True

        fplt._key_pressed = my_key_handler
```

**Comment by highfestiva** [comment]
`finplot.clamp_grid`? If you're still keeping the old functionality, just call the old function when you're done instead.
