### ISSUE TITLE
Not compatible with pyqt5 5.12 which is needed for pyqt-tools & pyqt5

### ISSUE THREAD

**Issue by triple-v3** [highfestiva/finplot#9]
This seems like a good package but I haven't used it yet because when I install it it goes with pyqt 5.9. Anyway around it?

**Comment by highfestiva** [comment]
Nope, there is an incompatibility in the newer QT versions, see https://github.com/pyqtgraph/pyqtgraph/issues/1057 for more info.

**Comment by highfestiva** [comment]
It however seems there was some kind of temporary fix during PyQt 5.13.0. I'll bump my versions and pipify.

**Comment by triple-v3** [comment]
Thanks!
