### ISSUE TITLE
candle plot bug？

### ISSUE THREAD

**Issue by wenjinglee** [highfestiva/finplot#90]
when zoom the pic, sometime the candle disappear.
https://user-images.githubusercontent.com/25558368/103132259-ee527f00-46de-11eb-8fe8-1a88f9e3885d.mp4

code is simple:
```
bars = get_hdf5('data/hs300_1m_demo.h5', 'hs300')
bars['datetime'] = pd.to_datetime(bars['datetime'])
bars.set_index(["datetime"], inplace=True)
candles= bars[['open', 'close', 'high', 'low', 'volume']]

ax = fplt.create_plot('demo')
fplt.candlestick_ochl(candles)

fplt.show()
```

**Comment by wenjinglee** [comment]
here is the data，thanks~

[hs300_1m_demo.zip](https://github.com/highfestiva/finplot/files/5741778/hs300_1m_demo.zip)

**Comment by wenjinglee** [comment]
I find the answer：the cursor must on the candle~

**Comment by highfestiva** [comment]
Interesting. What was the cause?
