### ISSUE TITLE
can't display additional line in candle Chart

### ISSUE THREAD

**Issue by wenjinglee** [highfestiva/finplot#91]
**I can display a additional line in others chart,but can't display it in candle Chart.
 what is wrong with my code? need your help,thanks!**

![Snipaste_2020-12-25_20-40-56](https://user-images.githubusercontent.com/25558368/103135410-25329000-46f3-11eb-8cca-869a3d159bc5.jpg)

![Snipaste_2020-12-25_20-46-14](https://user-images.githubusercontent.com/25558368/103135413-2d8acb00-46f3-11eb-8627-bb6df1f62d6f.jpg)

the code is :
```
import finplot as fplt
import numpy as np
import pandas as pd

from chanChart.data.data_source import get_hdf5

bars = get_hdf5('data/hs300_1m_demo.h5', 'hs300')
bars['datetime'] = pd.to_datetime(bars['datetime'])
bars.set_index(["datetime"], inplace=True)
candles= bars[['open', 'close', 'high', 'low', 'volume']]

fplt.plot(bars.index, bars.high.values, width=3)
# fplt.candlestick_ochl(candles)

start_row = bars[100:101]
start_x = start_row.index[0]
end_row = bars[500:501]
end_x = end_row.index[0]

line = fplt.add_line((start_x, 5000), (end_x, 5050), color='#9900ff')

fplt.show()
```

**Comment by wenjinglee** [comment]
Btw,Merry Christmas,everybody!

**Comment by highfestiva** [comment]
I want a complete running example, preferably with a pinch of data in the code, or at least a zip of both. I don't have time to find your old posts and puzzle up a reproducible version. Marry Christmas!

**Comment by highfestiva** [comment]
Possibly fixed by https://github.com/highfestiva/finplot/commit/822a229bbf2498a36a82588516500093937b9142 which has to do with non-interactive lines not being rendered properly.
