### ISSUE TITLE
Remove all lines & text added at once - what is the best approach?

### ISSUE THREAD

**Issue by msarm** [highfestiva/finplot#93]
As the data is getting refreshed, the horizontal lines & text created need to removed & re-created with the latest data. What is the best approach?

I'm able to remove lines successfully but it takes awhile to remove all the lines but unable to remove text

```
  for item in plots.ax.items:
      if (isinstance(item, pg.TextItem)): 
          fplt.remove_text(item)  # AttributeError: 'builtin_function_or_method' object has no attribute 'ax'
      if (isinstance(item, fplt.FinLine)): 
          fplt.remove_line(item) # works fine
```

**Comment by highfestiva** [comment]
Sounds like you didn't add the texts using "finplot.add_text()`?

How many lines are you adding? Could you use a polyline instead – that's probably faster to both add and remove. If there's very many lines you might consider implementing it as a `FinPlotItem`, which probably would help rendering performance.

**Comment by msarm** [comment]
It worked!

As recommended, I'm storing the list of created text objects and use them to destroy. It pretty fast!

I'm adding ~300-400 lines and after cleaning up some of my logic I'm able to remove lines fast now. I'll give a try later with FinPlotItem for drawing lines & test the performance.

BTW, I love your finplot so much and I've explored several charts in the past but no one is close to finplot performance & easy-to-use.

**Comment by MohdSaleh** [comment]
Could you please provide a sample code for plotting line using polyline  and FinPlotItem

**Comment by highfestiva** [comment]
@MohdSaleh No, sorry, don't have the time for that.
