### ISSUE TITLE
Intermittent errors plotting 2 series on 1 chart as highlighting

### ISSUE THREAD

**Issue by BeeSee20Eye35** [highfestiva/finplot#95]
Hi 
Thanks for creating this library. It's fantastic. Exactly what I was looking for. 

I am having a problem with the plotting of two series. I wonder if you could help me work out what I am doing wrong? 

I have been trying to plot two series so that one creates a highlighting box around certain candles on the other series. 
It sometimes works once or twice and then it goes wrong in several ways. 
Sometimes it temporarily plots the highlight boxes in a group at the left end of the chart and corrects this when panning or zoom is changed.  At other times it raises one of two errors and fails. 

I cannot see where it is going wrong. I tried to reuse ideas you demonstrated in some of the examples, namely the overlay in "example-overlay-correlate.py" and the updating in "example-bfx.py" so I am sure it should work in theory. 

The code is attached in : "testinghighlightplotting.txt"
[testinghighlightplotting.txt](https://github.com/highfestiva/finplot/files/5743909/testinghighlightplotting.txt)

The two errors returned are in : "testing highlight plotting errors.txt"
[testing highlight plotting errors.txt](https://github.com/highfestiva/finplot/files/5743887/testing.highlight.plotting.errors.txt)

Images of the plots are below. 

Please let me know if there is anything else that would help. 

Thanks in advance for any help. 

1. Image of the highlighting boxes in a group
![testingplothighlights-clumpedbeforeworking-pair1](https://user-images.githubusercontent.com/68307682/103161037-3f906a80-47d4-11eb-8570-ba4085be9951.png)

2. Images of the highlighting working
![testingplothighlights-workingafterclumped-pair1](https://user-images.githubusercontent.com/68307682/103161061-76668080-47d4-11eb-8967-ed8d1a54a0a3.png)

![testingplothighlights-working2afterclumped-pair1](https://user-images.githubusercontent.com/68307682/103161163-7450f180-47d5-11eb-90d9-6bd702c6326e.png)

3. Image of the chart after the highlighting has entirely stopped plotting
![testingplothighlights-nocandlesafterworking-pair1](https://user-images.githubusercontent.com/68307682/103161065-88482380-47d4-11eb-9ccb-26f71f116d5a.png)

**Comment by highfestiva** [comment]
````bash
FileNotFoundError: [Errno 2] No such file or directory: 'mt4datafortest.csv'
````

Please send zips, 7zips or tar.gzips if you have both code and data.

**Comment by BeeSee20Eye35** [comment]
Really sorry. Here is the code with the data. 
[datawithcode.zip](https://github.com/highfestiva/finplot/files/5744296/datawithcode.zip)

**Comment by highfestiva** [comment]
You're not using unique indices in your `highlighted`. Randomize like so:

````python
seed(int(time.time()))
num_select = randint(40,70)
selected = randint(0, len(data), num_select)
selected = sorted(set(selected)) # only use unique indices
highlighted = data.iloc[selected, :].copy()
highlighted = prep_highlighted(highlighted, 0.003)
````

You should also set the index right after loading:
````python
data = pd.read_csv(filename)
data.set_index(['Date'], inplace=True)
data.index = pd.to_datetime(data.index)
````

... and perhaps simplify the prep function:
````python
def prep_highlighted(highlighted, scale):
    down_scale = 1 - scale
    up_scale = 1 + scale
    highlighted[['High']] = highlighted[['High']].mul(up_scale, axis=1)
    highlighted[['Low']] = highlighted[['Low']].mul(down_scale, axis=1)
    highlighted = highlighted['High Low High Low'.split()]
    highlighted.columns = ['Open Close High Low'.split()]
    return highlighted
````

Good luck!

**Comment by BeeSee20Eye35** [comment]
Thanks very much! I'll try it.

**Comment by BeeSee20Eye35** [comment]
That solves my problem. Thank you very much.
I will need to understand it better to incorporate it into my application without reintroducing issues but I hope I can do that independently. 
 
I'll close the issue now. 

Appreciate the help.

**Comment by BeeSee20Eye35** [comment]
I have reopened this issue. I hope you don't mind? I wasn't sure of the convention re starting a new one vs continuing this one.

Thank you once again for your suggestions. They solved the errors I was getting from pandas.

However, there is a more subtle and insidious plotting issue which you may be interested in having a look at.

Here is the behaviour:
1. every plot update the highlight boxes first appear at the left hand end of the plot as if they are just plotted consecutively with no
interpretation of the datetime. They reset to their correct positions once the chart is panned and zoomed. 
2. if there is no interaction with the plot, the plot appears to update with no other visible problems other than the above.
    However, without interaction to zoom in, it is hard to check whether the highlights have plotted properly.
3. MAIN ISSUE : sometimes, if I scroll and zoom a plot, it fails after a few updates.. specifically the chart :
    - will no longer zoom from the mouse
    - if panned the scale does not adjust for the data
    - menu 'view all' option still works but autoscaling does not
    - box zooming still works but cannot zoom out without using the menu option above
 This happens more quickly if there are fewer highlight bars. If there are 30 or so, it usually works for quite a while.
 If 10 highlight bars or less it fails quickly. If there are 1-3 it rarely works more than for one update.

I wondered if the Main issue and the issue 1. may be because the datetime range for the highlight bars can be much smaller than the full range,
especially if there are very few bars. I tried adding a first and last bar to match the range of the main data series. This appeared to have no impact though.

Data and code attached.
[highlightedplottingerror2.zip](https://github.com/highfestiva/finplot/files/5757996/highlightedplottingerror2.zip)

1. zoom freeze - autoscale fail:
![1  zoom freeze - autoscale fail](https://user-images.githubusercontent.com/68307682/103421294-7929f280-4b93-11eb-83a8-445e07d95b75.png)

2. box zoomed post zoom freeze
![2  box zoomed post zoom freeze](https://user-images.githubusercontent.com/68307682/103421351-d02fc780-4b93-11eb-8134-9edb5bd8cd3f.png)

3. menu zoom out
![3  menu zoom out](https://user-images.githubusercontent.com/68307682/103421369-da51c600-4b93-11eb-96c2-4eb1af341d05.png)

**Comment by highfestiva** [comment]
Great find! Fixed the bug in https://github.com/highfestiva/finplot/commit/6c74cdd80b37b74a2efeb67beb28ab677561535d. Please note that your python code is not very "idiomatic." For instance, you'll get duplicate indices as you'll insert `.iloc[0]` and `.iloc[-1]` *after* making your indices unique. Best is probably to not insert any extra indices at all (not sure the point of those), but if you must, insert them during `set()` uniquification, like so:

````python
selected = sorted(set(selected)|set([0,len(data)-1]))  # only use unique indices
````
... and remove the `wrapfirst_and_last()` function. Good luck!

**Comment by BeeSee20Eye35** [comment]
Thank you for the great response. 

I'm afraid I am very much a home (and incompletely) taught amateur when it comes to coding. It helps a lot to get any improvement comments so, thank you. I am slowly getting better I think. I hope!

The wrap function is very sloppy I know. I just wanted to quickly test the idea of guaranteeing at least one point in the data set at the extreme ranges of the time series. It quickly became apparent though that this was not relevant. It's not something I need to include in my actual code. 

I will be trying the fix as soon as I can. 

I am using finplot through anaconda.  This might be a very simplistic question, but at what point after the fixes are pushed do they become available through the repositories that anaconda is likely to use?

Best and thanks again.

**Comment by BeeSee20Eye35** [comment]
Just one thing seems strange. 
When I plot fewer data as an update than the previous plot, the x scale stays the same leaving a blank piece of chart. 
Did I implement the fix incorrectly?

Data and code. This version plots a subset of the data every 3rd cycle. 
[code and data.zip](https://github.com/highfestiva/finplot/files/5759551/code.and.data.zip)

Plotting 2 years after having plotted 5 years of data. 
![3  scale does not reflect fewer data](https://user-images.githubusercontent.com/68307682/103447804-f59dfd80-4c87-11eb-9188-230c0c9fdf99.png)

Previously plotted with all 5 years of data
![3  full data plotted](https://user-images.githubusercontent.com/68307682/103447808-0a7a9100-4c88-11eb-83c7-1280860ea469.png)

**Comment by highfestiva** [comment]
Good question, I can't tell as I don't know anaconda at all. My guess is immediately after I create a patch release. I just created 1.5.1, try updating now.

**Comment by BeeSee20Eye35** [comment]
I can see 1.5.1 already. 
It doesn't default to it when I ask it to install but I can specify the version and it installed it OK.

**Comment by highfestiva** [comment]
Sorry, missed your question. That requires you to remove the unwanted parts of the time series in the internal data frames of finplot. Something like this:

````python
# clip dates appropriately...
plots[0].datasrc.df = plots[1].datasrc.df = plots[1].datasrc.df.iloc[-len(data):, :]
plots[0].update_data(highlighted)
plots[1].update_data(data)
````

Since that's updating a bunch of internals, expect quirks. Unfortunately updates are slapped on, and not very stable nor thought-through.

**Comment by BeeSee20Eye35** [comment]
No problem. Thanks for the help.
