### ISSUE TITLE
Is it possible to configure the width of a candle shadow?

### ISSUE THREAD

**Issue by haimivan** [highfestiva/finplot#98]
Hi,

if possible, I would like to be able to configure the width of a candle shadow.

This helps me to distinguish the shadows of candles with different time solutions.

For the example below, it will get difficult to distinguish between the candle shadows of the finer and the coarser candles.

### Example:

![a](https://user-images.githubusercontent.com/10325765/103340097-8b1c7000-4a83-11eb-90c4-25951c139e60.png)

**Comment by highfestiva** [comment]
Hadn't thought of that, but added a patch https://github.com/highfestiva/finplot/commit/7f3e9fb34b7ddf5ce5ddbbc4197dcf08edd93d04 in which you can do

````python
candles = fplt.candlestick_ochl(df)
candles.shadow_width = 3
````

**Comment by haimivan** [comment]
Super, this looks very good! Thanks!!!
